package buffmanifest

import "github.com/wowsims/forever/sim/core/proto"

// The paladin auras state a healing-taken row of 0, and Concentration Aura two mechanic rows of 0,
// none of which the raid's copy applies.
var paladinAuraSkips = []string{"A_MOD_HEALING_PCT", "A_MECHANIC_DURATION_MOD"}

// Manifest holds one row per proto field of RaidBuffs, PartyBuffs, IndividualBuffs
// and Debuffs. Rows follow the UI registry order: PARTY_BUFFS_CONFIG, then
// BUFFS_CONFIG, then DEBUFFS_CONFIG, with the fields of a scope that have no UI
// input appended after that scope's last input in proto declaration order. The two
// quadstate companion fields sit next to the row whose input renders them.
var Manifest = []BuffSpec{
	{
		Field: "blood_pact", Number: 1, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 11767,
		Go:      "BloodPact", Name: "Blood Pact", Owner: proto.Class_ClassWarlock,
		Stats: []proto.Stat{proto.Stat_StatStamina},
		Notes: "Improved Imp (18694) modifies Firebolt and Fire Shield, not Blood Pact, so the improved state has no source in warlock tree 1116.",
	},
	{
		Field: "battle_shout", Number: 14, Scope: ScopeParty, Proto: ProtoTristate, Kind: KindStatFlat,
		SpellID: 25289,
		Go:      "BattleShout", Name: "Battle Shout", Owner: proto.Class_ClassWarrior,
		Category: "BattleShout", SingleAura: true, Driver: true,
		ImpAction: &ActionRef{SpellID: 23563},
		Stats:     []proto.Stat{proto.Stat_StatAttackPower},
		Notes:     "Booming Voice (12321) is in warrior tree 1117 but modifies radius only (misc 6), so no talent prices the improved state: it says the warrior who shouted for the party wears three pieces of Battlegear of Wrath, item set 218, whose ItemSetSpell at three (2336) is 23563 for +30 on every effect of the Battle Shout family. The resolver reads no ItemSetSpell, so driveBattleShout adds the amount. The single A_MOD_ATTACK_POWER effect is melee attack power, which is why the row tags that alone.",
	},
	{
		Field: "devotion_aura", Number: 4, Scope: ScopeParty, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 10293,
		Go:      "DevotionAura", Name: "Devotion Aura", Owner: proto.Class_ClassPaladin,
		Category: "DevotionAura", SharedCategory: "PaladinAura", SingleAura: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatArmor},
		Notes:     "no Improved Devotion Aura node in paladin tree 1100.",
	},
	{
		Field: "leader_of_the_pack", Number: 3, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 24932,
		Go:      "LeaderOfThePack", Name: "Leader of the Pack", AuraName: "Leader of the Pack",
		Owner:    proto.Class_ClassDruid,
		Category: "DruidCritAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatMeleeCritRating, proto.Stat_StatSpellCritRating},
		Notes: "SkillLineAbility resolves the name to the talent passive 17007; the party aura is the second spell of the same name, 24932. Neither carries a rank subtext, so the aura-family rule takes the one that applies a party aura, 24932, which the row pins. No improving talent in druid tree 1089. Spell 24932 reads \"Increases critical strike chance by $s1%\" and names no school, so the 3 goes on every kind of crit: PhysicalCritPercent is melee and ranged, SpellCritPercent the rest. Spell 17007 calls it exclusive with Moonkin Aura, which is the DruidCritAura category the two rows share.",
	},
	{
		Field: "mana_spring_totem", Number: 9, Scope: ScopeParty, Proto: ProtoTristate, Kind: KindStatFlat,
		SpellID: 10494,
		Go:      "ManaSpringTotem", Name: "Mana Spring Totem", AuraName: "Mana Spring",
		Owner:    proto.Class_ClassShaman,
		Talent:   &TalentMod{SpellID: 16187, Name: "Restorative Totems", Effect: 0, Applies: TalentScalesValue},
		Category: "ManaSpringTotem",
		Stats:    []proto.Stat{proto.Stat_StatMP5},
		Notes:    "Restorative Totems (16187, TraitDefinition 134191) effect 0 scales the Mana Spring aura family (class mask 16384), not the totem cast.",
	},
	{
		Field: "mana_tide_totems", Number: 10, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindExternalCD,
		SpellID: 17360, CastID: 17359,
		Go: "ManaTideTotems", Name: "Mana Tide Totem", AuraName: "Mana Tide",
		Owner: proto.Class_ClassShaman, Category: "ManaTideTotem",
		Stats: []proto.Stat{proto.Stat_StatMP5}, Label: "Mana Tide Totem",
		Notes: "the totem cast 17359 states the 13 s life and the 5 min cooldown; the aura 17360 states the mana.",
	},
	{
		Field: "moonkin_aura", Number: 2, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 24907,
		Go:      "MoonkinAura", Name: "Moonkin Aura", Owner: proto.Class_ClassDruid,
		Category: "DruidCritAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatMeleeCritRating, proto.Stat_StatSpellCritRating},
		Notes: "A_MOD_CRIT_PCT names no school, so spell 24907's 3 goes on every kind of crit: PhysicalCritPercent is melee and ranged, SpellCritPercent the rest. It shares the DruidCritAura category with Leader of the Pack, which spell 17007 calls it exclusive with. No improving talent in druid tree 1089.",
	},
	{
		Field: "retribution_aura", Number: 5, Scope: ScopeParty, Proto: ProtoBool, Kind: KindDamageShield,
		SpellID: 10301,
		Go:      "RetributionAura", Name: "Retribution Aura", Owner: proto.Class_ClassPaladin,
		Category: "RetributionAura", SharedCategory: "PaladinAura", SingleAura: true, Driver: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatArmor, proto.Stat_StatDefenseRating},
		Notes:     "the only paladin trait matching Retribution Aura is Benediction (20101), which modifies cost (misc 14). Driven because the damage scales with the providing paladin's Holy spell power, which retribution_aura_spell_power states.",
	},
	{
		Field: "retribution_aura_spell_power", Number: 19, Scope: ScopeParty, Proto: ProtoDouble, Kind: KindFlag,
		Go:    "RetributionAuraSpellPower",
		Notes: "the Holy spell power of the paladin providing Retribution Aura, which driveRetributionAura scales the damage with; a sim input with no spell source, rendered under Other Inputs.",
	},
	{
		Field: "concentration_aura", Number: 18, Scope: ScopeParty, Proto: ProtoBool, Kind: KindPseudoMult,
		SpellID: 19746,
		Go:      "ConcentrationAura", Name: "Concentration Aura", Owner: proto.Class_ClassPaladin,
		Category: "ConcentrationAura", SharedCategory: "PaladinAura", SingleAura: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatDefenseRating},
		Notes:     "no Improved Concentration Aura node in paladin tree 1100.",
	},
	{
		Field: "trueshot_aura", Number: 6, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 20906,
		Go:      "TrueshotAura", Name: "Trueshot Aura", Owner: proto.Class_ClassHunter,
		Stats: []proto.Stat{proto.Stat_StatRangedAttackPower},
		Notes: "the row follows rank 5 (20906), which states 50 ranged attack power. TODO: in-game testing is needed, because the ladder is non-monotonic - rank 4 (20905) states 75 - and the resolver takes the top rank. The single A_MOD_RANGED_ATTACK_POWER effect is why the row tags ranged attack power alone.",
	},
	{
		Field: "atiesh_mage", Number: 7, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		SpellID: 28142,
		Go:      "AtieshMage", Owner: proto.Class_ClassMage,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage, proto.Stat_StatHealingPower}, Label: "Atiesh - Mage",
		Notes: "aura-only spell; 28142 is named Power of the Guardian.",
	},
	{
		Field: "atiesh_warlock", Number: 8, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		SpellID: 28143,
		Go:      "AtieshWarlock", Owner: proto.Class_ClassWarlock,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage, proto.Stat_StatHealingPower}, Label: "Atiesh - Warlock",
		Notes: "aura-only spell; 28143 is named Power of the Guardian.",
	},
	{
		Field: "strength_of_earth_totem", Number: 12, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 25362,
		Go:      "StrengthOfEarthTotem", Name: "Strength of Earth Totem", AuraName: "Strength of Earth",
		Owner: proto.Class_ClassShaman, Category: "StrengthOfEarthTotem",
		Stats: []proto.Stat{proto.Stat_StatStrength},
		Notes: "Enhancing Totems (16295) exists as a spell but has no node in shaman tree 1082.",
	},
	{
		Field: "grace_of_air_totem", Number: 11, Scope: ScopeParty, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 25360,
		Go:      "GraceOfAirTotem", Name: "Grace of Air Totem", AuraName: "Grace of Air",
		Owner: proto.Class_ClassShaman, Category: "GraceOfAirTotem", Driver: true,
		Stats: []proto.Stat{proto.Stat_StatAgility},
		Notes: "Enhancing Totems (16295) exists as a spell but has no node in shaman tree 1082. Driven because totem_twisting shortens the aura to the 9 s of every 10 a twisting shaman keeps it up.",
	},
	{
		Field: "windfury_totem", Number: 13, Scope: ScopeParty, Proto: ProtoBool, Kind: KindProc,
		SpellID: 10610,
		Go:      "WindfuryTotem", Name: "Windfury Totem", AuraName: "Windfury Totem",
		Owner: proto.Class_ClassShaman, Category: "WindfuryTotem",
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "the cast family (8512/10613/10614) and the aura family (8516/10608/10610) share the name; the aura carries the proc. Improved Weapon Totems (29193) has no node in shaman tree 1082.",
	},
	{
		Field: "atiesh_druid", Number: 16, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		SpellID: 28145,
		Go:      "AtieshDruid", Owner: proto.Class_ClassDruid, Label: "Atiesh - Druid",
		Notes: "no UI input today; aura-only spell 28145 is named Power of the Guardian.",
	},
	{
		Field: "atiesh_priest", Number: 17, Scope: ScopeParty, Proto: ProtoInt32, Kind: KindItemCount,
		SpellID: 28144,
		Go:      "AtieshPriest", Owner: proto.Class_ClassPriest, Label: "Atiesh - Priest",
		Notes: "no UI input today; aura-only spell 28144 is named Power of the Guardian.",
	},
	{
		Field: "totem_twisting", Number: 15, Scope: ScopeParty, Proto: ProtoBool, Kind: KindFlag,
		Go:    "TotemTwisting",
		Notes: "sim behaviour toggle with no spell source; rendered under Other Inputs.",
	},
	{
		Field: "arcane_brilliance", Number: 1, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 23028,
		Go:      "ArcaneBrilliance", Name: "Arcane Brilliance", Owner: proto.Class_ClassMage,
		Category: "StatBuff",
		Stats:    []proto.Stat{proto.Stat_StatIntellect},
		Notes:    "the ungranted twin 364161 has no SkillLineAbility row.",
	},
	{
		Field: "greater_blessing_of_kings", Number: 1, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatPct,
		SpellID: 25898,
		Go:      "GreaterBlessingOfKings", Name: "Greater Blessing of Kings", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatAgility, proto.Stat_StatIntellect, proto.Stat_StatSpirit, proto.Stat_StatStamina, proto.Stat_StatStrength},
		Notes: "the greater blessing is the raid's copy: 25898 reaches every ally of the target's class, where the single-target 20217 of the same 10% reaches one.",
	},
	{
		Field: "prayer_of_spirit", Number: 4, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 27681,
		Go:      "PrayerOfSpirit", Name: "Prayer of Spirit", Owner: proto.Class_ClassPriest,
		Category: "StatBuff",
		Stats:    []proto.Stat{proto.Stat_StatSpirit, proto.Stat_StatSpellDamage},
		Notes:    "the prayer is the raid's copy: 27681 reaches the caster's raid, where the single-target Divine Spirit of the same 40 spirit reaches one ally. No Improved Divine Spirit node in priest tree 1114; Twin Disciplines (135379) and Spiritual Healing (135382) overlap the prayer's class mask but modify damage and healing done (misc 0), which a spirit buff has none of.",
	},
	{
		Field: "gift_of_the_wild", Number: 5, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 21850,
		Go:      "GiftOfTheWild", Name: "Gift of the Wild", Owner: proto.Class_ClassDruid,
		Stats: []proto.Stat{proto.Stat_StatArmor, proto.Stat_StatStrength, proto.Stat_StatAgility, proto.Stat_StatIntellect, proto.Stat_StatSpirit, proto.Stat_StatStamina},
		Notes: "no Improved Mark of the Wild node in druid tree 1089; the ungranted twins 1291335/1310503 have no SkillLineAbility row. The per-school resistance categories this aura joins are derived from the effect school mask by KindResistance, not carried in the manifest.",
	},
	{
		Field: "thorns", Number: 6, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindDamageShield,
		SpellID: 9910,
		Go:      "Thorns", Name: "Thorns", Owner: proto.Class_ClassDruid,
		Category: "Thorns", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatDefenseRating, proto.Stat_StatStamina},
		Notes: "no Brambles node in druid tree 1089; the only matching trait is Moonglow (16845), which modifies cost (misc 14).",
	},
	{
		Field: "prayer_of_fortitude", Number: 2, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 21564,
		Go:      "PrayerOfFortitude", Name: "Prayer of Fortitude", Owner: proto.Class_ClassPriest,
		Stats: []proto.Stat{proto.Stat_StatStamina},
		Notes: "the prayer is the raid's copy: rank 2 (21564) reaches the caster's raid, where the single-target Power Word: Fortitude of the same 70 stamina reaches one ally; the ungranted twin 450086 has no SkillLineAbility row. No Improved Power Word: Fortitude node in priest tree 1114.",
	},
	{
		Field: "greater_blessing_of_might", Number: 4, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 25916,
		Go:      "GreaterBlessingOfMight", Name: "Greater Blessing of Might", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "the greater blessing is the raid's copy: rank 2 (25916) reaches every ally of the target's class, where the single-target Blessing of Might of the same 133 melee attack power reaches one. No Improved Blessing of Might node in paladin tree 1100; Benediction (20101) modifies cost (misc 14).",
	},
	{
		Field: "greater_blessing_of_wisdom", Number: 3, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindStatFlat,
		SpellID: 25918,
		Go:      "GreaterBlessingOfWisdom", Name: "Greater Blessing of Wisdom", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatMP5},
		Notes: "the greater blessing is the raid's copy: rank 2 (25918) reaches every ally of the target's class, where the single-target Blessing of Wisdom of the same 40 mana per 5 seconds reaches one. No Improved Blessing of Wisdom node in paladin tree 1100; Benediction (20101) modifies cost (misc 14).",
	},
	{
		Field: "greater_blessing_of_salvation", Number: 2, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindPseudoMult,
		SpellID: 25895,
		Go:      "GreaterBlessingOfSalvation", Name: "Greater Blessing of Salvation", Owner: proto.Class_ClassPaladin,
		Notes: "the greater blessing is the raid's copy: 25895 reaches every ally of the target's class, where the single-target Blessing of Salvation of the same -30% threat reaches one.",
	},
	{
		Field: "greater_blessing_of_light", Number: 7, Scope: ScopeIndividual, Proto: ProtoBool, Kind: KindManual,
		SpellID: 25890,
		Go:      "GreaterBlessingOfLight", Name: "Greater Blessing of Light", Owner: proto.Class_ClassPaladin,
		Category: "BlessingOfLight",
		Stats:    []proto.Stat{proto.Stat_StatHealingPower},
		Notes:    "25890 raises the healing the target receives from Holy Light and Flash of Light through flat modifiers on those spell families; the paladin's heals read the bonus off their own rows and only look for the aura, which the category tags.",
	},
	{
		Field: "prayer_of_shadow_protection", Number: 3, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 27683,
		Go:      "PrayerOfShadowProtection", Name: "Prayer of Shadow Protection", Owner: proto.Class_ClassPriest,
		Category: "ResistanceShadow",
		Stats:    []proto.Stat{proto.Stat_StatShadowResistance, proto.Stat_StatStamina},
		Notes:    "the prayer is the raid's copy: 27683 reaches the caster's raid for 20 minutes, where the single-target Shadow Protection of the same 60 shadow resistance reaches one ally for 10.",
	},
	{
		Field: "fire_resistance_aura", Number: 7, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 19900,
		Go:      "FireResistanceAura", Name: "Fire Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "FireResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatFireResistance},
	},
	{
		Field: "frost_resistance_aura", Number: 8, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 19898,
		Go:      "FrostResistanceAura", Name: "Frost Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "FrostResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatFrostResistance},
	},
	{
		Field: "shadow_resistance_aura", Number: 9, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 19896,
		Go:      "ShadowResistanceAura", Name: "Shadow Resistance Aura", Owner: proto.Class_ClassPaladin,
		Category: "ShadowResistanceAura", SharedCategory: "PaladinAura", SingleAura: true,
		SkipAuras: paladinAuraSkips,
		Stats:     []proto.Stat{proto.Stat_StatShadowResistance},
	},
	{
		Field: "fire_resistance_totem", Number: 10, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 10535,
		Go:      "FireResistanceTotem", Name: "Fire Resistance Totem", AuraName: "Fire Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceFire",
		Stats: []proto.Stat{proto.Stat_StatFireResistance},
	},
	{
		Field: "frost_resistance_totem", Number: 11, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 10477,
		Go:      "FrostResistanceTotem", Name: "Frost Resistance Totem", AuraName: "Frost Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceFrost",
		Stats: []proto.Stat{proto.Stat_StatFrostResistance},
	},
	{
		Field: "nature_resistance_totem", Number: 12, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 10599,
		Go:      "NatureResistanceTotem", Name: "Nature Resistance Totem", AuraName: "Nature Resistance",
		Owner: proto.Class_ClassShaman, Category: "ResistanceNature",
		Stats: []proto.Stat{proto.Stat_StatNatureResistance},
	},
	{
		Field: "aspect_of_the_wild", Number: 13, Scope: ScopeRaid, Proto: ProtoBool, Kind: KindResistance,
		SpellID: 20190,
		Go:      "AspectOfTheWild", Name: "Aspect of the Wild", Owner: proto.Class_ClassHunter,
		Category: "ResistanceNature",
		Stats:    []proto.Stat{proto.Stat_StatNatureResistance},
	},
	{
		Field: "innervates", Number: 5, Scope: ScopeIndividual, Proto: ProtoInt32, Kind: KindExternalCD,
		SpellID: 29166,
		Go:      "Innervates", Name: "Innervate", Owner: proto.Class_ClassDruid,
		Category: "Innervate",
		Stats:    []proto.Stat{proto.Stat_StatMP5}, Label: "Innervates",
		Notes: "auras 134 and 110 of spell 29166 are the spirit regen the driver applies; no Improved Innervate node in druid tree 1089.",
	},
	{
		Field: "power_infusions", Number: 6, Scope: ScopeIndividual, Proto: ProtoInt32, Kind: KindExternalCD,
		SpellID: 10060,
		Go:      "PowerInfusions", Name: "Power Infusion", Owner: proto.Class_ClassPriest,
		Category: "PowerInfusion",
		Stats:    []proto.Stat{proto.Stat_StatSpellHasteRating}, Label: "Power Infusions",
		Notes: "Power Infusion (10060) grants +20% damage and healing done for 15 s.",
	},
	{
		Field: "hunters_mark", Number: 10, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 14325,
		Go:      "HuntersMark", Name: "Hunter's Mark", Owner: proto.Class_ClassHunter,
		Category: "HuntersMark", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatRangedAttackPower, proto.Stat_StatAttackPower},
		Notes: "no Improved Hunter's Mark node in hunter tree 1091; CumulativeAura is 0, so rank 4 (14325) is a flat value.",
	},
	{
		Field: "judgement_of_the_crusader", Number: 3, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 20303,
		Go:      "JudgementOfTheCrusader", Name: "Judgement of the Crusader", Owner: proto.Class_ClassPaladin,
		Category: "Judgement of the Crusader", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatHolyDamage, proto.Stat_StatSpellDamage},
		Notes: "the Holy damage taken the judgement adds is applied by JudgementOfTheCrusaderAura in debuffs.go, which the paladin's own ranks share. Improved Seal of the Crusader (20337) exists as a spell but has no node in paladin tree 1100.",
	},
	{
		Field: "judgement_of_light", Number: 2, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindProc,
		SpellID: 20346,
		Go:      "JudgementOfLight", Name: "Judgement of Light", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatDefenseRating},
	},
	{
		Field: "judgement_of_wisdom", Number: 1, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindProc,
		SpellID: 20355,
		Go:      "JudgementOfWisdom", Name: "Judgement of Wisdom", Owner: proto.Class_ClassPaladin,
		Stats: []proto.Stat{proto.Stat_StatMP5},
	},
	{
		Field: "curse_of_elements", Number: 4, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffDamageTaken,
		SpellID: 1311680,
		Go:      "CurseOfElements", Name: "Curse of the Elements", Owner: proto.Class_ClassWarlock,
		Category: "CurseOfElements", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatSpellDamage},
		Notes: "Malediction (1225177) is in warlock tree 1116 but its modifier masks do not cover Curse of the Elements (mask 4194304); the only overlapping trait is Amplify Curse (18288), an ability with a 3 minute cooldown, so there is no passive improved state. The ungranted ranks 11723/11724 have no SkillLineAbility row.",
	},
	{
		Field: "curse_of_recklessness", Number: 9, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 11717,
		Go:      "CurseOfRecklessness", Name: "Curse of Recklessness", Owner: proto.Class_ClassWarlock,
		Category: "CurseOfRecklessness", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
	},
	{
		Field: "faerie_fire", Number: 7, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 9907,
		Go:      "FaerieFire", Name: "Faerie Fire", Owner: proto.Class_ClassDruid,
		Category: "FaerieFireAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower, proto.Stat_StatMeleeHitRating},
		Notes: "no Improved Faerie Fire node in druid tree 1089; the ungranted twins 1288561/1289452 have no SkillLineAbility row.",
	},
	{
		Field: "expose_armor", Number: 6, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 11198,
		Go:      "ExposeArmor", Name: "Expose Armor", Owner: proto.Class_ClassRogue,
		Category: "MajorArmorReduction", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "effect 0 states 0 and -450 per combo point, so the row is resolved as the five-point finisher, which is what the raid config applies; a rogue casting it for fewer combo points needs a driver that prices the aura, and there is none. Improved Expose Armor (14168) is in rogue tree 1111 but its only 107/108 effect is misc 14 (cost); effects 1 and 2 are dummy auras.",
	},
	{
		Field: "sunder_armor", Number: 8, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStacking,
		SpellID: 11597,
		Go:      "SunderArmor", Name: "Sunder Armor", Owner: proto.Class_ClassWarrior,
		Category: "MajorArmorReduction", SingleAura: true, Driver: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower},
		Notes: "CumulativeAura is 5, and a stack is worth nothing until it is there, so the raid's copy is ramped by a driver; Improved Sunder Armor (12308) modifies cost only (misc 14).",
	},
	{
		Field: "gift_of_arthas", Number: 5, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffDamageTaken,
		SpellID: 11374,
		Go:      "GiftOfArthas", Category: "GiftOfArthasAura", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatAttackPower, proto.Stat_StatDefenseRating},
		Notes: "applied by an elixir, so 11374 has no SkillLineAbility row and the anchor is explicit.",
	},
	{
		Field: "demoralizing_roar", Number: 11, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 9898,
		Go:      "DemoralizingRoar", Name: "Demoralizing Roar", Owner: proto.Class_ClassDruid,
		Category: "Demoralizing", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatDefenseRating},
		Notes: "no Feral Aggression node in druid tree 1089.",
	},
	{
		Field: "demoralizing_shout", Number: 12, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 11556,
		Go:      "DemoralizingShout", Name: "Demoralizing Shout", Owner: proto.Class_ClassWarrior,
		Category: "Demoralizing", SingleAura: true,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatDefenseRating},
		Notes: "no Improved Demoralizing Shout node in warrior tree 1117.",
	},
	{
		Field: "thunder_clap", Number: 13, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffAtkSpeed,
		SpellID: 11581,
		Go:      "ThunderClap", Name: "Thunder Clap", Owner: proto.Class_ClassWarrior,
		Category: "AtkSpdReduction",
		Stats:    []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatDefenseRating},
		Notes:    "Improved Thunder Clap (12287) is in warrior tree 1117 but its only 107/108 effect is misc 14 (cost).",
	},
	{
		Field: "insect_swarm", Number: 14, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 24977,
		Go:      "InsectSwarm", Name: "Insect Swarm", Owner: proto.Class_ClassDruid,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatDefenseRating},
		Notes: "Nature's Splendor (1223083) effect 2 extends the duration (misc 1); the field is a plain bool, so the talent is not carried.",
	},
	{
		Field: "scorpid_sting", Number: 15, Scope: ScopeDebuff, Proto: ProtoBool, Kind: KindDebuffStat,
		SpellID: 3043,
		Go:      "ScorpidSting", Name: "Scorpid Sting", Owner: proto.Class_ClassHunter,
		Stats: []proto.Stat{proto.Stat_StatStamina, proto.Stat_StatDefenseRating},
		Notes: "Improved Stings (1310661) effect 2 extends the duration (misc 1); the field is a plain bool, so the talent is not carried.",
	},
}
