package buffmanifest

import (
	"fmt"
	"strings"
)

type message struct {
	Name        string
	Scope       BuffScope
	Description string
}

// messages is the emission order of the four buff messages.
var messages = []message{
	{Name: "RaidBuffs", Scope: ScopeRaid, Description: "Buffs that affect the entire raid."},
	{Name: "PartyBuffs", Scope: ScopeParty, Description: "Buffs that affect a single party."},
	{Name: "IndividualBuffs", Scope: ScopeIndividual, Description: "These are usually individual actions taken by other Characters."},
	{Name: "Debuffs", Scope: ScopeDebuff},
}

const header = `// Code generated by tools/gen_buffs_proto from tools/database/buffmanifest. DO NOT EDIT.
syntax = "proto3";
package proto;
option go_package = "./proto";

import "common.proto";
`

// protoTypeNames is the proto type each manifest type emits. TristateEffect is declared in
// common.proto, which this file imports.
var protoTypeNames = map[BuffProtoType]string{
	ProtoBool:     "bool",
	ProtoTristate: "TristateEffect",
	ProtoInt32:    "int32",
	ProtoDouble:   "double",
}

// RenderProto emits proto/buffs.proto from the manifest. A field's number is its position in its
// scope's slice.
func RenderProto() []byte {
	var b strings.Builder
	b.WriteString(header)

	for _, msg := range messages {
		b.WriteString("\n")
		if msg.Description != "" {
			fmt.Fprintf(&b, "// %s\n", msg.Description)
		}

		specs := ByScope(msg.Scope)
		fmt.Fprintf(&b, "// Next index: %d\n", len(specs)+1)

		fmt.Fprintf(&b, "message %s {\n", msg.Name)
		for i, spec := range specs {
			fmt.Fprintf(&b, "\t%s %s = %d;\n", protoType(spec), spec.Field, i+1)
		}
		b.WriteString("}\n")
	}

	return []byte(b.String())
}

func protoType(spec BuffSpec) string {
	name, ok := protoTypeNames[spec.ProtoType()]
	if !ok {
		panic(fmt.Sprintf("%s has no proto type for %s", spec.Field, spec.ProtoType()))
	}
	return name
}
