package buffmanifest

import (
	"fmt"
	"sort"
	"strings"
)

type message struct {
	Name        string
	Scope       BuffScope
	Description string
}

// messages is the emission order of the four buff messages.
var messages = []message{
	{Name: "RaidBuffs", Scope: ScopeRaid, Description: "Buffs that affect the entire raid."},
	{Name: "PartyBuffs", Scope: ScopeParty, Description: "Buffs that affect a single party."},
	{Name: "IndividualBuffs", Scope: ScopeIndividual, Description: "These are usually individual actions taken by other Characters."},
	{Name: "Debuffs", Scope: ScopeDebuff},
}

const header = `// Code generated by tools/gen_buffs_proto from tools/database/buffmanifest. DO NOT EDIT.
syntax = "proto3";
package proto;
option go_package = "./proto";

import "common.proto";
`

// protoTypeNames is the proto type each manifest type emits. TristateEffect is declared in
// common.proto, which this file imports.
var protoTypeNames = map[BuffProtoType]string{
	ProtoBool:     "bool",
	ProtoTristate: "TristateEffect",
	ProtoInt32:    "int32",
	ProtoDouble:   "double",
}

// RenderProto emits proto/buffs.proto for the given manifest rows. Field numbers come from
// the manifest, which owns them, and fields are written in ascending number order.
func RenderProto(manifest []BuffSpec) []byte {
	var b strings.Builder
	b.WriteString(header)

	for _, msg := range messages {
		b.WriteString("\n")
		if msg.Description != "" {
			fmt.Fprintf(&b, "// %s\n", msg.Description)
		}

		specs := scopeRows(manifest, msg.Scope)

		next := int32(1)
		for _, spec := range specs {
			if spec.Number >= next {
				next = spec.Number + 1
			}
		}
		fmt.Fprintf(&b, "// Next index: %d\n", next)

		fmt.Fprintf(&b, "message %s {\n", msg.Name)
		for _, spec := range specs {
			fmt.Fprintf(&b, "\t%s %s = %d;\n", protoType(spec), spec.Field, spec.Number)
		}
		b.WriteString("}\n")
	}

	return []byte(b.String())
}

func protoType(spec BuffSpec) string {
	name, ok := protoTypeNames[spec.Proto]
	if !ok {
		panic(fmt.Sprintf("%s has no proto type for %s", spec.Field, spec.Proto))
	}
	return name
}

func scopeRows(manifest []BuffSpec, scope BuffScope) []BuffSpec {
	var rows []BuffSpec
	for _, spec := range manifest {
		if spec.Scope == scope {
			rows = append(rows, spec)
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Number < rows[j].Number })
	return rows
}
