package buffmanifest

import (
	"fmt"
	"strings"
	"testing"
)

func TestRenderProtoNextIndex(t *testing.T) {
	rendered := string(RenderProto())

	for _, msg := range messages {
		want := fmt.Sprintf("// Next index: %d\nmessage %s {\n", len(ByScope(msg.Scope))+1, msg.Name)
		if !strings.Contains(rendered, want) {
			t.Errorf("%s is not preceded by %q", msg.Name, want)
		}
	}
}

func TestRenderProtoHeader(t *testing.T) {
	rendered := string(RenderProto())
	want := `// Code generated by tools/gen_buffs_proto from tools/database/buffmanifest. DO NOT EDIT.
syntax = "proto3";
package proto;
option go_package = "./proto";

import "common.proto";
`
	if !strings.HasPrefix(rendered, want) {
		t.Errorf("rendered header is\n%s\nwant\n%s", rendered[:len(want)], want)
	}
	for _, line := range strings.Split(rendered, "\n") {
		if strings.HasPrefix(line, " ") {
			t.Errorf("line %q is space-indented; common.proto uses tabs", line)
		}
	}
}
