package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/stats"
)

const ExpertiseRatingPerExpertisePercent = 10.000000
const DefenseRatingPerDefenseLevel = 1.000000
const DodgeRatingPerDodgePercent = 12.000000
const ParryRatingPerParryPercent = 15.000000
const BlockRatingPerBlockPercent = 5.000000
const PhysicalHitRatingPerHitPercent = 10.000000
const SpellHitRatingPerHitPercent = 10.000000
const PhysicalCritRatingPerCritPercent = 14.000000
const SpellCritRatingPerCritPercent = 14.000000
const PhysicalHasteRatingPerHastePercent = 10.000000
const SpellHasteRatingPerHastePercent = 10.000000

var CritPerAgiMaxLevel = map[proto.Class]float64{
	proto.Class_ClassUnknown: 0.0,
	proto.Class_ClassWarrior: 0.05000000,
	proto.Class_ClassPaladin: 0.05060000,
	proto.Class_ClassHunter:  0.01890000,
	proto.Class_ClassRogue:   0.03450000,
	proto.Class_ClassPriest:  0.05000000,
	proto.Class_ClassShaman:  0.05080000,
	proto.Class_ClassMage:    0.05140000,
	proto.Class_ClassWarlock: 0.05000000,
	proto.Class_ClassDruid:   0.05000000,
}
var CritPerIntMaxLevel = map[proto.Class]float64{
	proto.Class_ClassUnknown: 0.0,
	proto.Class_ClassWarrior: 0.00000000,
	proto.Class_ClassPaladin: 0.01670000,
	proto.Class_ClassHunter:  0.01650000,
	proto.Class_ClassRogue:   0.00000000,
	proto.Class_ClassPriest:  0.01680000,
	proto.Class_ClassShaman:  0.01690000,
	proto.Class_ClassMage:    0.01680000,
	proto.Class_ClassWarlock: 0.01650000,
	proto.Class_ClassDruid:   0.01670000,
}
var ExtraClassBaseStats = map[proto.Class]stats.Stats{
	proto.Class_ClassUnknown: {},
	proto.Class_ClassWarrior: {
		stats.Mana:                0.0000,
		stats.SpellCritPercent:    0.0000,
		stats.PhysicalCritPercent: 1.1400,
	},
	proto.Class_ClassPaladin: {
		stats.Mana:                1512.0000,
		stats.SpellCritPercent:    3.3355,
		stats.PhysicalCritPercent: 0.6520,
	},
	proto.Class_ClassHunter: {
		stats.Mana:                1720.0000,
		stats.SpellCritPercent:    3.6020,
		stats.PhysicalCritPercent: -1.5320,
	},
	proto.Class_ClassRogue: {
		stats.Mana:                0.0000,
		stats.SpellCritPercent:    0.0000,
		stats.PhysicalCritPercent: -0.2950,
	},
	proto.Class_ClassPriest: {
		stats.Mana:                1376.0000,
		stats.SpellCritPercent:    1.2375,
		stats.PhysicalCritPercent: 3.1830,
	},
	proto.Class_ClassShaman: {
		stats.Mana:                1520.0000,
		stats.SpellCritPercent:    2.2010,
		stats.PhysicalCritPercent: 1.6750,
	},
	proto.Class_ClassMage: {
		stats.Mana:                1213.0000,
		stats.SpellCritPercent:    0.9075,
		stats.PhysicalCritPercent: 3.4575,
	},
	proto.Class_ClassWarlock: {
		stats.Mana:                1373.0000,
		stats.SpellCritPercent:    1.7000,
		stats.PhysicalCritPercent: 2.0000,
	},
	proto.Class_ClassDruid: {
		stats.Mana:                1244.0000,
		stats.SpellCritPercent:    1.8515,
		stats.PhysicalCritPercent: 0.9610,
	},
}
