// Code generated by "stringer -type=DefenseType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefenseTypeNone-0]
	_ = x[DefenseTypeMagic-1]
	_ = x[DefenseTypeMelee-2]
	_ = x[DefenseTypeRanged-3]
	_ = x[DefenseTypeLen-4]
}

const _DefenseType_name = "DefenseTypeNoneDefenseTypeMagicDefenseTypeMeleeDefenseTypeRangedDefenseTypeLen"

var _DefenseType_index = [...]uint8{0, 15, 31, 47, 64, 78}

func (i DefenseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DefenseType_index)-1 {
		return "DefenseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DefenseType_name[_DefenseType_index[idx]:_DefenseType_index[idx+1]]
}
