// Code generated by "stringer -type=SpellFlag flags.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellFlagNone-0]
	_ = x[SpellFlagIgnoreResists-2]
	_ = x[SpellFlagIgnoreTargetModifiers-4]
	_ = x[SpellFlagIgnoreAttackerModifiers-8]
	_ = x[SpellFlagApplyArmorReduction-16]
	_ = x[SpellFlagCannotBeDodged-32]
	_ = x[SpellFlagIncludeTargetBonusDamage-64]
	_ = x[SpellFlagBinary-128]
	_ = x[SpellFlagChanneled-256]
	_ = x[SpellFlagDisease-512]
	_ = x[SpellFlagPoison-1024]
	_ = x[SpellFlagHauntSE-2048]
	_ = x[SpellFlagHelpful-4096]
	_ = x[SpellFlagMeleeMetrics-8192]
	_ = x[SpellFlagNoOnCastComplete-16384]
	_ = x[SpellFlagNoMetrics-32768]
	_ = x[SpellFlagNoLogs-65536]
	_ = x[SpellFlagAPL-131072]
	_ = x[SpellFlagMCD-262144]
	_ = x[SpellFlagReactive-524288]
	_ = x[SpellFlagNoOnDamageDealt-1048576]
	_ = x[SpellFlagPrepullOnly-2097152]
	_ = x[SpellFlagEncounterOnly-4194304]
	_ = x[SpellFlagPotion-8388608]
	_ = x[SpellFlagConjured-16777216]
	_ = x[SpellFlagExplosive-33554432]
	_ = x[SpellFlagCombatPotion-67108864]
	_ = x[SpellFlagNoSpellMods-134217728]
	_ = x[SpellFlagCanCastWhileMoving-268435456]
	_ = x[SpellFlagPassiveSpell-536870912]
	_ = x[SpellFlagSuppressWeaponProcs-1073741824]
	_ = x[SpellFlagProc-2147483648]
	_ = x[SpellFlagSupressDoTApply-4294967296]
	_ = x[SpellFlagSwapped-8589934592]
	_ = x[SpellFlagCastWhileIncapacitated-17179869184]
	_ = x[SpellFlagPushback-34359738368]
	_ = x[SpellFlagAgentReserved1-68719476736]
	_ = x[SpellFlagAgentReserved2-137438953472]
	_ = x[SpellFlagAgentReserved3-274877906944]
	_ = x[SpellFlagAgentReserved4-549755813888]
}

const _SpellFlag_name = "SpellFlagNoneSpellFlagIgnoreResistsSpellFlagIgnoreTargetModifiersSpellFlagIgnoreAttackerModifiersSpellFlagApplyArmorReductionSpellFlagCannotBeDodgedSpellFlagIncludeTargetBonusDamageSpellFlagBinarySpellFlagChanneledSpellFlagDiseaseSpellFlagPoisonSpellFlagHauntSESpellFlagHelpfulSpellFlagMeleeMetricsSpellFlagNoOnCastCompleteSpellFlagNoMetricsSpellFlagNoLogsSpellFlagAPLSpellFlagMCDSpellFlagReactiveSpellFlagNoOnDamageDealtSpellFlagPrepullOnlySpellFlagEncounterOnlySpellFlagPotionSpellFlagConjuredSpellFlagExplosiveSpellFlagCombatPotionSpellFlagNoSpellModsSpellFlagCanCastWhileMovingSpellFlagPassiveSpellSpellFlagSuppressWeaponProcsSpellFlagProcSpellFlagSupressDoTApplySpellFlagSwappedSpellFlagCastWhileIncapacitatedSpellFlagPushbackSpellFlagAgentReserved1SpellFlagAgentReserved2SpellFlagAgentReserved3SpellFlagAgentReserved4"

var _SpellFlag_map = map[SpellFlag]string{
	0:            _SpellFlag_name[0:13],
	2:            _SpellFlag_name[13:35],
	4:            _SpellFlag_name[35:65],
	8:            _SpellFlag_name[65:97],
	16:           _SpellFlag_name[97:125],
	32:           _SpellFlag_name[125:148],
	64:           _SpellFlag_name[148:181],
	128:          _SpellFlag_name[181:196],
	256:          _SpellFlag_name[196:214],
	512:          _SpellFlag_name[214:230],
	1024:         _SpellFlag_name[230:245],
	2048:         _SpellFlag_name[245:261],
	4096:         _SpellFlag_name[261:277],
	8192:         _SpellFlag_name[277:298],
	16384:        _SpellFlag_name[298:323],
	32768:        _SpellFlag_name[323:341],
	65536:        _SpellFlag_name[341:356],
	131072:       _SpellFlag_name[356:368],
	262144:       _SpellFlag_name[368:380],
	524288:       _SpellFlag_name[380:397],
	1048576:      _SpellFlag_name[397:421],
	2097152:      _SpellFlag_name[421:441],
	4194304:      _SpellFlag_name[441:463],
	8388608:      _SpellFlag_name[463:478],
	16777216:     _SpellFlag_name[478:495],
	33554432:     _SpellFlag_name[495:513],
	67108864:     _SpellFlag_name[513:534],
	134217728:    _SpellFlag_name[534:554],
	268435456:    _SpellFlag_name[554:581],
	536870912:    _SpellFlag_name[581:602],
	1073741824:   _SpellFlag_name[602:630],
	2147483648:   _SpellFlag_name[630:643],
	4294967296:   _SpellFlag_name[643:667],
	8589934592:   _SpellFlag_name[667:683],
	17179869184:  _SpellFlag_name[683:714],
	34359738368:  _SpellFlag_name[714:731],
	68719476736:  _SpellFlag_name[731:754],
	137438953472: _SpellFlag_name[754:777],
	274877906944: _SpellFlag_name[777:800],
	549755813888: _SpellFlag_name[800:823],
}

func (i SpellFlag) String() string {
	if str, ok := _SpellFlag_map[i]; ok {
		return str
	}
	return "SpellFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
