// Code generated by "stringer -type=SpellSchool"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpellSchoolNone-0]
	_ = x[SpellSchoolPhysical-1]
	_ = x[SpellSchoolHoly-2]
	_ = x[SpellSchoolFire-4]
	_ = x[SpellSchoolNature-8]
	_ = x[SpellSchoolFrost-16]
	_ = x[SpellSchoolShadow-32]
	_ = x[SpellSchoolArcane-64]
	_ = x[SpellSchoolChaos-126]
	_ = x[SpellSchoolShadowFlame-36]
	_ = x[SpellSchoolShadowFrost-48]
	_ = x[SpellSchoolPlague-40]
	_ = x[SpellSchoolFirestorm-12]
	_ = x[SpellSchoolFrostfire-20]
	_ = x[SpellSchoolElemental-28]
}

const _SpellSchool_name = "SpellSchoolNoneSpellSchoolPhysicalSpellSchoolHolySpellSchoolFireSpellSchoolNatureSpellSchoolFirestormSpellSchoolFrostSpellSchoolFrostfireSpellSchoolElementalSpellSchoolShadowSpellSchoolShadowFlameSpellSchoolPlagueSpellSchoolShadowFrostSpellSchoolArcaneSpellSchoolChaos"

var _SpellSchool_map = map[SpellSchool]string{
	0:   _SpellSchool_name[0:15],
	1:   _SpellSchool_name[15:34],
	2:   _SpellSchool_name[34:49],
	4:   _SpellSchool_name[49:64],
	8:   _SpellSchool_name[64:81],
	12:  _SpellSchool_name[81:101],
	16:  _SpellSchool_name[101:117],
	20:  _SpellSchool_name[117:137],
	28:  _SpellSchool_name[137:157],
	32:  _SpellSchool_name[157:174],
	36:  _SpellSchool_name[174:196],
	40:  _SpellSchool_name[196:213],
	48:  _SpellSchool_name[213:235],
	64:  _SpellSchool_name[235:252],
	126: _SpellSchool_name[252:268],
}

func (i SpellSchool) String() string {
	if str, ok := _SpellSchool_map[i]; ok {
		return str
	}
	return "SpellSchool(" + strconv.FormatInt(int64(i), 10) + ")"
}
