// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
)

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var SynthPaladinAuraCategory = "SynthPaladinAura"

// Mana Spring Totem
var SynthManaSpringCategory = "ManaSpringTotem"
var synthManaSpringSpell = spelldata.MustFind(10494)
var synthManaSpringMeta = &Meta{
	Label:        "Mana Spring Totem",
	Spell:        synthManaSpringSpell,
	Category:     SynthManaSpringCategory,
	Talent:       spelldata.Talent(16187, 5),
	TalentEffect: 1,
}

func SynthManaSpringValue(talentPoints int32) float64 {
	return synthManaSpringMeta.Value(talentPoints)
}
func SynthManaSpringDuration(talentPoints int32) time.Duration {
	return synthManaSpringMeta.Duration(talentPoints)
}
func SynthManaSpringAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthManaSpringMeta, isPlayer, talentPoints)
}

// Mana Tide Totem
var SynthManaTideCategory = "ManaTideTotem"
var synthManaTideSpell = spelldata.MustFind(17360)
var synthManaTideMeta = &Meta{
	Label:    "Mana Tide Totem",
	Spell:    synthManaTideSpell,
	Cast:     spelldata.MustFind(17359),
	Category: SynthManaTideCategory,
}

func SynthManaTideValue(talentPoints int32) float64 {
	return synthManaTideMeta.Value(talentPoints)
}
func SynthManaTideDuration(talentPoints int32) time.Duration {
	return synthManaTideMeta.Duration(talentPoints)
}
func SynthManaTideCooldown() time.Duration {
	return synthManaTideMeta.Cooldown()
}
func SynthManaTideAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthManaTideMeta, isPlayer, talentPoints)
}

// Blessing of Kings
var synthBlessingOfKingsSpell = spelldata.MustFind(20217)
var synthBlessingOfKingsMeta = &Meta{
	Label: "Blessing of Kings",
	Spell: synthBlessingOfKingsSpell,
}

func SynthBlessingOfKingsValue(talentPoints int32) float64 {
	return synthBlessingOfKingsMeta.Value(talentPoints)
}
func SynthBlessingOfKingsDuration(talentPoints int32) time.Duration {
	return synthBlessingOfKingsMeta.Duration(talentPoints)
}
func SynthBlessingOfKingsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthBlessingOfKingsMeta, isPlayer, talentPoints)
}

// Battle Shout
var SynthBattleShoutCategory = "SynthBattleShout"
var synthBattleShoutSpell = spelldata.MustFind(25289)
var synthBattleShoutMeta = &Meta{
	Label:      "Battle Shout",
	Spell:      synthBattleShoutSpell,
	Category:   SynthBattleShoutCategory,
	SingleAura: true,
}

func SynthBattleShoutValue(talentPoints int32) float64 {
	return synthBattleShoutMeta.Value(talentPoints)
}
func SynthBattleShoutDuration(talentPoints int32) time.Duration {
	return synthBattleShoutMeta.Duration(talentPoints)
}
func SynthBattleShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthBattleShoutMeta, isPlayer, talentPoints)
}

// Devotion Aura
var SynthDevotionAuraCategory = "DevotionAura"
var synthDevotionAuraSpell = spelldata.MustFind(10293)
var synthDevotionAuraMeta = &Meta{
	Label:                "Devotion Aura",
	Spell:                synthDevotionAuraSpell,
	Category:             SynthDevotionAuraCategory,
	SharedCategory:       SynthPaladinAuraCategory,
	SingleAura:           true,
	Talent:               spelldata.Talent(20140, 2),
	TalentEffect:         2,
	TalentScalesDuration: true,
	SkipAuras:            []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func SynthDevotionAuraValue(talentPoints int32) float64 {
	return synthDevotionAuraMeta.Value(talentPoints)
}
func SynthDevotionAuraDuration(talentPoints int32) time.Duration {
	return synthDevotionAuraMeta.Duration(talentPoints)
}
func SynthDevotionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthDevotionAuraMeta, isPlayer, talentPoints)
}

// Frost Resistance Aura
var SynthFrostResistanceAuraCategory = "FrostResistanceAura"
var synthFrostResistanceAuraSpell = spelldata.MustFind(19898)
var synthFrostResistanceAuraMeta = &Meta{
	Label:          "Frost Resistance Aura",
	Spell:          synthFrostResistanceAuraSpell,
	Category:       SynthFrostResistanceAuraCategory,
	SharedCategory: SynthPaladinAuraCategory,
	SingleAura:     true,
}

func SynthFrostResistanceAuraValue(talentPoints int32) float64 {
	return synthFrostResistanceAuraMeta.Value(talentPoints)
}
func SynthFrostResistanceAuraDuration(talentPoints int32) time.Duration {
	return synthFrostResistanceAuraMeta.Duration(talentPoints)
}
func SynthFrostResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthFrostResistanceAuraMeta, isPlayer, talentPoints)
}

// Frost Resistance Totem
var synthFrostResistanceTotemSpell = spelldata.MustFind(10477)
var synthFrostResistanceTotemMeta = &Meta{
	Label: "Frost Resistance Totem",
	Spell: synthFrostResistanceTotemSpell,
}

func SynthFrostResistanceTotemValue(talentPoints int32) float64 {
	return synthFrostResistanceTotemMeta.Value(talentPoints)
}
func SynthFrostResistanceTotemDuration(talentPoints int32) time.Duration {
	return synthFrostResistanceTotemMeta.Duration(talentPoints)
}
func SynthFrostResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthFrostResistanceTotemMeta, isPlayer, talentPoints)
}

// Innervates
// Left out: effect 1 A_MOD_MANA_REGEN_INTERRUPT(134) misc 0
// Left out: effect 2 A_MOD_POWER_REGEN_PERCENT(110) misc 0
var SynthInnervatesCategory = "Innervate"
var synthInnervatesSpell = spelldata.MustFind(29166)
var synthInnervatesMeta = &Meta{
	Label:    "Innervates",
	Spell:    synthInnervatesSpell,
	Category: SynthInnervatesCategory,
}

func SynthInnervatesDuration(talentPoints int32) time.Duration {
	return synthInnervatesMeta.Duration(talentPoints)
}
func SynthInnervatesCooldown() time.Duration {
	return synthInnervatesMeta.Cooldown()
}
func SynthInnervatesAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthInnervatesMeta, isPlayer, talentPoints)
}

// Power Infusions
var SynthPowerInfusionsCategory = "PowerInfusion"
var synthPowerInfusionsSpell = spelldata.MustFind(10060)
var synthPowerInfusionsMeta = &Meta{
	Label:    "Power Infusions",
	Spell:    synthPowerInfusionsSpell,
	Category: SynthPowerInfusionsCategory,
}

func SynthPowerInfusionsValue(talentPoints int32) float64 {
	return synthPowerInfusionsMeta.Value(talentPoints)
}
func SynthPowerInfusionsDuration(talentPoints int32) time.Duration {
	return synthPowerInfusionsMeta.Duration(talentPoints)
}
func SynthPowerInfusionsCooldown() time.Duration {
	return synthPowerInfusionsMeta.Cooldown()
}
func SynthPowerInfusionsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, synthPowerInfusionsMeta, isPlayer, talentPoints)
}

// func SynthAbsentAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // totem_twisting, KindFlag: the client has no row for it

// Atiesh - Mage
var synthAtieshMageSpell = spelldata.MustFind(28142)
var synthAtieshMageMeta = &Meta{
	Label: "Atiesh - Mage",
	Spell: synthAtieshMageSpell,
}

func SynthAtieshMageValue(talentPoints int32) float64 {
	return synthAtieshMageMeta.Value(talentPoints)
}
func SynthAtieshMageDuration(talentPoints int32) time.Duration {
	return synthAtieshMageMeta.Duration(talentPoints)
}
func SynthAtieshMageAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return newItemCountBuff(unit, synthAtieshMageMeta, isPlayer, count)
}

// Thorns
var SynthThornsCategory = "Thorns"
var synthThornsSpell = spelldata.MustFind(9910)
var synthThornsMeta = &Meta{
	Label:        "Thorns",
	Spell:        synthThornsSpell,
	Category:     SynthThornsCategory,
	Talent:       spelldata.Talent(16836, 2),
	TalentEffect: 1,
}

func SynthThornsValue(talentPoints int32) float64 {
	return synthThornsMeta.Value(talentPoints)
}
func SynthThornsDuration(talentPoints int32) time.Duration {
	return synthThornsMeta.Duration(talentPoints)
}
func SynthThornsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDamageShield(unit, synthThornsMeta, isPlayer, talentPoints)
}

func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	if party.ManaSpringTotem != proto.TristateEffect_TristateEffectMissing {
		core.MakePermanent(SynthManaSpringAura(&char.Unit, false, core.GetTristateValueInt32(party.ManaSpringTotem, 0, 5)))
	}
	if party.ManaTideTotems > 0 {
		driveSynthManaTide(char, party)
	}
	if individual.GreaterBlessingOfKings {
		core.MakePermanent(SynthBlessingOfKingsAura(&char.Unit, false, 0))
	}
	if party.BattleShout != proto.TristateEffect_TristateEffectMissing {
		driveSynthBattleShout(char, party)
	}
	if party.DevotionAura {
		core.MakePermanent(SynthDevotionAuraAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceAura {
		core.MakePermanent(SynthFrostResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceTotem {
		core.MakePermanent(SynthFrostResistanceTotemAura(&char.Unit, false, 0))
	}
	if individual.Innervates > 0 {
		driveSynthInnervates(char, individual)
	}
	if individual.PowerInfusions > 0 {
		driveSynthPowerInfusions(char, individual)
	}
	if party.AtieshMage > 0 {
		driveSynthAtieshMage(char, party)
	}
	if raid.Thorns {
		core.MakePermanent(SynthThornsAura(&char.Unit, false, 0))
	}
}
