// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package shaman

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Healing Grace: missing rank 1 of 3
//   Lightning Mastery: missing rank 1 of 5

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Earthbound: effect 0 of spell 1222988 has no rank curve and is held at its base points
//   Improved Ghost Wolf: effect 1, 2 of spell 16262 has no rank curve and is held at its base points
//   Improved Stormstrike: effect 2 of spell 1223031 has no rank curve and is held at its base points
//   Maelstrom Weapon: effect 1, 2 of spell 408498 has no rank curve and is held at its base points
//   Mental Dexterity: effect 1 of spell 415140 has no rank curve and is held at its base points
//   Shamanistic Focus: effect 0 of spell 1223030 has no rank curve and is held at its base points

type generatedSpellData struct {
	AncestralFortitude             spelldata.Ladder
	AncestralHealing               spelldata.Ladder
	AncestralHealingTriggered      spelldata.Ladder
	AncestralKnowledge             spelldata.Ladder
	AncestralSpirit                spelldata.Ladder
	Anticipation                   spelldata.Ladder
	AstralRecall                   spelldata.Ladder
	CallOfFlame                    spelldata.Ladder
	CallOfThunder                  spelldata.Ladder
	CallOfTheAncestors             spelldata.Ladder
	CallOfTheElements              spelldata.Ladder
	CallOfTheSpirits               spelldata.Ladder
	ChainHeal                      spelldata.Ladder
	ChainLightning                 spelldata.Ladder
	Concussion                     spelldata.Ladder
	Convection                     spelldata.Ladder
	CureDisease                    spelldata.Ladder
	CurePoison                     spelldata.Ladder
	DiseaseCleansingTotem          spelldata.Ladder
	DiseaseCleansingTotemTriggered spelldata.Ladder
	EarthShock                     spelldata.Ladder
	EarthsGrasp                    spelldata.Ladder
	EarthbindTotem                 spelldata.Ladder
	EarthbindTotemTriggered        spelldata.Ladder
	Earthbound                     spelldata.Ladder
	EarthboundTriggered            spelldata.Ladder
	ElementalAlacrity              spelldata.Ladder
	ElementalDevastation           spelldata.Ladder
	ElementalDevastationTriggered  spelldata.Ladder
	ElementalFocus                 spelldata.Ladder
	ElementalFocusTriggered        spelldata.Ladder
	ElementalFury                  spelldata.Ladder
	ElementalReach                 spelldata.Ladder
	ElementalWarding               spelldata.Ladder
	ElementalWeapons               spelldata.Ladder
	EnhancingTotems                spelldata.Ladder
	EyeOfTheStorm                  spelldata.Ladder
	FarSight                       spelldata.Ladder
	FireNova                       spelldata.Ladder
	FireNovaTriggered              spelldata.Ladder
	FireResistanceTotem            spelldata.Ladder
	FireResistanceTotemTriggered   spelldata.Ladder
	FlameShock                     spelldata.Ladder
	FlametongueTotem               spelldata.Ladder
	FlametongueTotemTriggered      spelldata.Ladder
	FlametongueWeapon              spelldata.Ladder
	FlametongueWeaponTriggered     spelldata.Ladder
	Flurry                         spelldata.Ladder
	FlurryTriggered                spelldata.Ladder
	FrostResistanceTotem           spelldata.Ladder
	FrostResistanceTotemTriggered  spelldata.Ladder
	FrostShock                     spelldata.Ladder
	FrostbrandWeapon               spelldata.Ladder
	FrostbrandWeaponTriggered      spelldata.Ladder
	GhostWolf                      spelldata.Ladder
	GraceOfAirTotem                spelldata.Ladder
	GraceOfAirTotemTriggered       spelldata.Ladder
	GroundingTotem                 spelldata.Ladder
	GroundingTotemTriggered        spelldata.Ladder
	GuardianTotems                 spelldata.Ladder
	HealingFocus                   spelldata.Ladder
	HealingStreamTotem             spelldata.Ladder
	HealingStreamTotemTriggered    spelldata.Ladder
	HealingWave                    spelldata.Ladder
	HealingWay                     spelldata.Ladder
	ImprovedFireNova               spelldata.Ladder
	ImprovedGhostWolf              spelldata.Ladder
	ImprovedHealingWave            spelldata.Ladder
	ImprovedLightningShield        spelldata.Ladder
	ImprovedReincarnation          spelldata.Ladder
	ImprovedStormstrike            spelldata.Ladder
	ImprovedStormstrikeTriggered   spelldata.Ladder
	ImprovedWeaponTotems           spelldata.Ladder
	LavaBurst                      spelldata.Ladder
	LesserHealingWave              spelldata.Ladder
	LightningBolt                  spelldata.Ladder
	LightningOverload              spelldata.Ladder
	LightningShield                spelldata.Ladder
	LightningShieldTriggered       spelldata.Ladder
	MaelstromWeapon                spelldata.Ladder
	MaelstromWeaponTriggered       spelldata.Ladder
	MagmaTotem                     spelldata.Ladder
	MagmaTotemTriggered            spelldata.Ladder
	ManaSpringTotem                spelldata.Ladder
	ManaSpringTotemTriggered       spelldata.Ladder
	ManaTideTotem                  spelldata.Ladder
	ManaTideTotemTriggered         spelldata.Ladder
	MentalDexterity                spelldata.Ladder
	MentalQuickness                spelldata.Ladder
	Mindfulness                    spelldata.Ladder
	NaturalGrace                   spelldata.Ladder
	NatureResistanceTotem          spelldata.Ladder
	NatureResistanceTotemTriggered spelldata.Ladder
	NaturesGuidance                spelldata.Ladder
	NaturesSwiftness               spelldata.Ladder
	PoisonCleansingTotem           spelldata.Ladder
	PoisonCleansingTotemTriggered  spelldata.Ladder
	Purge                          spelldata.Ladder
	Purification                   spelldata.Ladder
	RageOfTheFarseer               spelldata.Ladder
	Reincarnation                  spelldata.Ladder
	RestorativeTotems              spelldata.Ladder
	Reverberation                  spelldata.Ladder
	Riptide                        spelldata.Ladder
	RockbiterWeapon                spelldata.Ladder
	RockbiterWeaponTriggered       spelldata.Ladder
	SearingTotem                   spelldata.Ladder
	SearingTotemTriggered          spelldata.Ladder
	SentryTotem                    spelldata.Ladder
	ShamanisticFocus               spelldata.Ladder
	ShieldSpecialization           spelldata.Ladder
	SpiritWeapons                  spelldata.Ladder
	StoneclawTotem                 spelldata.Ladder
	StoneclawTotemTriggered        spelldata.Ladder
	StoneskinTotem                 spelldata.Ladder
	StoneskinTotemTriggered        spelldata.Ladder
	Stormstrike                    spelldata.Ladder
	StrengthOfEarthTotem           spelldata.Ladder
	StrengthOfEarthTotemTriggered  spelldata.Ladder
	ThunderingStrikes              spelldata.Ladder
	TidalFocus                     spelldata.Ladder
	TidalMastery                   spelldata.Ladder
	TotemicFocus                   spelldata.Ladder
	TotemicProjection              spelldata.Ladder
	TotemicRecall                  spelldata.Ladder
	Toughness                      spelldata.Ladder
	TremorTotem                    spelldata.Ladder
	TremorTotemTriggered           spelldata.Ladder
	TwoHandedAxesAndMaces          spelldata.Ladder
	TwoHandedAxesAndMacesTriggered spelldata.Ladder
	WaterBreathing                 spelldata.Ladder
	WaterWalking                   spelldata.Ladder
	WeaponMastery                  spelldata.Ladder
	WindfuryTotem                  spelldata.Ladder
	WindfuryTotemTriggered         spelldata.Ladder
	WindfuryWeapon                 spelldata.Ladder
	WindfuryWeaponTriggered        spelldata.Ladder
	WindwallTotem                  spelldata.Ladder
	WindwallTotemTriggered         spelldata.Ladder
}

var spellData = generatedSpellData{
	AncestralFortitude:             spelldata.Ranked(16177),
	AncestralHealing:               spelldata.Talent(16176, 3),
	AncestralHealingTriggered:      spelldata.Ranked(16177),
	AncestralKnowledge:             spelldata.Talent(17485, 5),
	AncestralSpirit:                spelldata.Ranked(2008, 20609, 20610, 20776, 20777),
	Anticipation:                   spelldata.Talent(16254, 3),
	AstralRecall:                   spelldata.Ranked(556),
	CallOfFlame:                    spelldata.Talent(16038, 3),
	CallOfThunder:                  spelldata.Ranked(16120),
	CallOfTheAncestors:             spelldata.Ranked(66843),
	CallOfTheElements:              spelldata.Ranked(66842),
	CallOfTheSpirits:               spelldata.Ranked(66844),
	ChainHeal:                      spelldata.Ranked(1064, 10622, 10623),
	ChainLightning:                 spelldata.Ranked(421, 930, 2860, 10605),
	Concussion:                     spelldata.Talent(16035, 5),
	Convection:                     spelldata.Talent(16039, 5),
	CureDisease:                    spelldata.Ranked(2870),
	CurePoison:                     spelldata.Ranked(526),
	DiseaseCleansingTotem:          spelldata.Ranked(8170),
	DiseaseCleansingTotemTriggered: spelldata.Ranked(8171, 8172),
	EarthShock:                     spelldata.Ranked(8042, 8044, 8045, 8046, 10412, 10413, 10414),
	EarthsGrasp:                    spelldata.Talent(16043, 2),
	EarthbindTotem:                 spelldata.Ranked(2484),
	EarthbindTotemTriggered:        spelldata.Ranked(3600),
	Earthbound:                     spelldata.Talent(1222988, 1),
	EarthboundTriggered:            spelldata.Ranked(1238289),
	ElementalAlacrity:              spelldata.Talent(16578, 3),
	ElementalDevastation:           spelldata.Talent(30160, 3),
	ElementalDevastationTriggered:  spelldata.Ranked(30165),
	ElementalFocus:                 spelldata.Ranked(16164),
	ElementalFocusTriggered:        spelldata.Ranked(16246),
	ElementalFury:                  spelldata.Talent(16089, 5),
	ElementalReach:                 spelldata.Talent(28999, 2),
	ElementalWarding:               spelldata.Talent(28996, 3),
	ElementalWeapons:               spelldata.Talent(16266, 3),
	EnhancingTotems:                spelldata.Ranked(16259, 16295),
	EyeOfTheStorm:                  spelldata.Talent(29062, 3),
	FarSight:                       spelldata.Ranked(6196),
	FireNova:                       spelldata.Ranked(408341, 408342, 408343, 408344, 408345),
	FireNovaTriggered:              spelldata.Ranked(8349, 8502, 8503, 11306, 11307),
	FireResistanceTotem:            spelldata.Ranked(8184, 10537, 10538),
	FireResistanceTotemTriggered:   spelldata.Ranked(8185, 10534, 10535),
	FlameShock:                     spelldata.Ranked(8050, 8052, 8053, 10447, 10448, 29228),
	FlametongueTotem:               spelldata.Ranked(8227, 8249, 10526, 16387),
	FlametongueTotemTriggered:      spelldata.Ranked(8230, 8248, 8250, 8253, 10521, 10523, 15036, 16389),
	FlametongueWeapon:              spelldata.Ranked(8024, 8027, 8030, 16339, 16341, 16342),
	FlametongueWeaponTriggered:     spelldata.Ranked(8026, 8028, 8029, 10445, 16343, 16344),
	Flurry:                         spelldata.Talent(16256, 5),
	FlurryTriggered:                spelldata.Ranked(16257),
	FrostResistanceTotem:           spelldata.Ranked(8181, 10478, 10479),
	FrostResistanceTotemTriggered:  spelldata.Ranked(8182, 10476, 10477),
	FrostShock:                     spelldata.Ranked(8056, 8058, 10472, 10473),
	FrostbrandWeapon:               spelldata.Ranked(8033, 8038, 10456, 16355, 16356),
	FrostbrandWeaponTriggered:      spelldata.Ranked(8034, 8037, 10458, 16352, 16353),
	GhostWolf:                      spelldata.Ranked(2645),
	GraceOfAirTotem:                spelldata.Ranked(8835, 10627, 25359),
	GraceOfAirTotemTriggered:       spelldata.Ranked(8836, 10626, 25360),
	GroundingTotem:                 spelldata.Ranked(8177),
	GroundingTotemTriggered:        spelldata.Ranked(8179),
	GuardianTotems:                 spelldata.Talent(16258, 2),
	HealingFocus:                   spelldata.Talent(16181, 3),
	HealingStreamTotem:             spelldata.Ranked(5394, 6375, 6377, 10462, 10463),
	HealingStreamTotemTriggered:    spelldata.Ranked(5672, 6371, 6372, 10460, 10461),
	HealingWave:                    spelldata.Ranked(331, 332, 547, 913, 939, 959, 8005, 10395, 10396, 25357),
	HealingWay:                     spelldata.Talent(29206, 3),
	ImprovedFireNova:               spelldata.Talent(16086, 2),
	ImprovedGhostWolf:              spelldata.Talent(16262, 2),
	ImprovedHealingWave:            spelldata.Talent(16182, 5),
	ImprovedLightningShield:        spelldata.Talent(16261, 3),
	ImprovedReincarnation:          spelldata.Talent(16184, 2),
	ImprovedStormstrike:            spelldata.Talent(1223031, 2),
	ImprovedStormstrikeTriggered:   spelldata.Ranked(1238931),
	ImprovedWeaponTotems:           spelldata.Ranked(29192, 29193),
	LavaBurst:                      spelldata.Ranked(408490, 1238299, 1238300),
	LesserHealingWave:              spelldata.Ranked(8004, 8008, 8010, 10466, 10467, 10468),
	LightningBolt:                  spelldata.Ranked(403, 529, 548, 915, 943, 6041, 10391, 10392, 15207, 15208),
	LightningOverload:              spelldata.Talent(408438, 3),
	LightningShield:                spelldata.Ranked(324, 325, 905, 945, 8134, 10431, 10432),
	LightningShieldTriggered:       spelldata.Ranked(26363, 26364, 26365, 26366, 26367, 26369, 26370, 26545),
	MaelstromWeapon:                spelldata.Talent(408498, 5),
	MaelstromWeaponTriggered:       spelldata.Ranked(408505),
	MagmaTotem:                     spelldata.Ranked(8190, 10585, 10586, 10587),
	MagmaTotemTriggered:            spelldata.Ranked(8187, 8188, 10579, 10580, 10581, 10582, 10583, 10584),
	ManaSpringTotem:                spelldata.Ranked(5675, 10495, 10496, 10497),
	ManaSpringTotemTriggered:       spelldata.Ranked(5677, 10491, 10493, 10494),
	ManaTideTotem:                  spelldata.Ranked(16190, 17354, 17359),
	ManaTideTotemTriggered:         spelldata.Ranked(16191, 17355, 17360),
	MentalDexterity:                spelldata.Talent(415140, 3),
	MentalQuickness:                spelldata.Talent(30812, 2),
	Mindfulness:                    spelldata.Talent(1223033, 3),
	NaturalGrace:                   spelldata.Talent(29187, 3),
	NatureResistanceTotem:          spelldata.Ranked(10595, 10600, 10601),
	NatureResistanceTotemTriggered: spelldata.Ranked(10596, 10598, 10599),
	NaturesGuidance:                spelldata.Ranked(16180, 16196, 16198),
	NaturesSwiftness:               spelldata.Ranked(16188),
	PoisonCleansingTotem:           spelldata.Ranked(8166),
	PoisonCleansingTotemTriggered:  spelldata.Ranked(8167, 8168),
	Purge:                          spelldata.Ranked(370, 8012),
	Purification:                   spelldata.Talent(16178, 5),
	RageOfTheFarseer:               spelldata.Ranked(425336),
	Reincarnation:                  spelldata.Ranked(21169),
	RestorativeTotems:              spelldata.Talent(16187, 5),
	Reverberation:                  spelldata.Talent(16040, 5),
	Riptide:                        spelldata.Ranked(408521, 1239242, 1239243),
	RockbiterWeapon:                spelldata.Ranked(8017, 8018, 8019, 10399, 16314, 16315, 16316),
	RockbiterWeaponTriggered:       spelldata.Ranked(10400, 15567, 15568, 15569, 16311, 16312, 16313),
	SearingTotem:                   spelldata.Ranked(3599, 6363, 6364, 6365, 10437, 10438),
	SearingTotemTriggered:          spelldata.Ranked(3606, 6350, 6351, 6352, 10435, 10436),
	SentryTotem:                    spelldata.Ranked(6495),
	ShamanisticFocus:               spelldata.Talent(1223030, 1),
	ShieldSpecialization:           spelldata.Ranked(16253, 16298, 16299, 16300, 16301),
	SpiritWeapons:                  spelldata.Ranked(16268),
	StoneclawTotem:                 spelldata.Ranked(5730, 6390, 6391, 6392, 10427, 10428),
	StoneclawTotemTriggered:        spelldata.Ranked(5729, 6393, 6394, 6395, 10423, 10424),
	StoneskinTotem:                 spelldata.Ranked(8071, 8154, 8155, 10406, 10407, 10408),
	StoneskinTotemTriggered:        spelldata.Ranked(8072, 8156, 8157, 10403, 10404, 10405),
	Stormstrike:                    spelldata.Ranked(17364),
	StrengthOfEarthTotem:           spelldata.Ranked(8075, 8160, 8161, 10442, 25361),
	StrengthOfEarthTotemTriggered:  spelldata.Ranked(8076, 8162, 8163, 10441, 25362),
	ThunderingStrikes:              spelldata.Talent(16255, 5),
	TidalFocus:                     spelldata.Talent(16179, 5),
	TidalMastery:                   spelldata.Talent(16194, 5),
	TotemicFocus:                   spelldata.Talent(16173, 5),
	TotemicProjection:              spelldata.Ranked(437009),
	TotemicRecall:                  spelldata.Ranked(36936),
	Toughness:                      spelldata.Talent(16252, 5),
	TremorTotem:                    spelldata.Ranked(8143),
	TremorTotemTriggered:           spelldata.Ranked(8146),
	TwoHandedAxesAndMaces:          spelldata.Ranked(16269),
	TwoHandedAxesAndMacesTriggered: spelldata.Ranked(197, 199),
	WaterBreathing:                 spelldata.Ranked(131),
	WaterWalking:                   spelldata.Ranked(546),
	WeaponMastery:                  spelldata.Ranked(29082, 29084, 29086, 29087, 29088),
	WindfuryTotem:                  spelldata.Ranked(8512, 10613, 10614),
	WindfuryTotemTriggered:         spelldata.Ranked(8515, 8516, 10608, 10609, 10610, 10612),
	WindfuryWeapon:                 spelldata.Ranked(8232, 8235, 10486, 16362),
	WindfuryWeaponTriggered:        spelldata.Ranked(8233, 8236, 10484, 16361),
	WindwallTotem:                  spelldata.Ranked(15107, 15111, 15112),
	WindwallTotemTriggered:         spelldata.Ranked(15108, 15109, 15110),
}
