package paladin

import (
	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
)

// Righteous Fury
// https://www.wowhead.com/forever/spell=25780
//
// Increases the threat generated by your Holy attacks by 60%. Lasts 30 min.
//
// Improved Righteous Fury adds a damage-taken reduction to the buff, and Instrument of Law's
// threat reduction only applies while it is down; both attach to the aura from their talents.
func (paladin *Paladin) registerRighteousFury() {
	rank := spellData.RighteousFury.Highest()
	actionID := core.ActionID{SpellID: rank.ID}

	paladin.RighteousFuryAura = paladin.RegisterAura(core.Aura{
		Label:    "Righteous Fury",
		ActionID: actionID,
		Duration: core.NeverExpires,
	}).AttachSpellMod(core.SpellModConfig{
		Kind:       core.SpellMod_ThreatMultiplier_Pct,
		School:     core.SpellSchoolHoly,
		FloatValue: rank.Effect(dbcenums.A_MOD_THREAT, 2).Percent(),
	})

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    rank.SpellSchool(),
		DefenseType:    rank.DefenseTypeCore(),
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskRighteousFury,

		ManaCost: manaCost(rank),
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: rank.GCD(),
			},
		},

		ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
			spell.RelatedSelfBuff.Activate(sim)
		},

		RelatedSelfBuff: paladin.RighteousFuryAura,
	})
}
