package paladin

import (
	"github.com/wowsims/forever/sim/common/shared"
	"github.com/wowsims/forever/sim/core"
)

var RighteousFuryRankMap = spellData.RighteousFury

// Righteous Fury
// https://www.wowhead.com/forever/spell=25780
//
// Increases the threat generated by your Holy attacks by 60%. Lasts 30 min.
//
// Improved Righteous Fury adds a damage-taken reduction to the buff, and Instrument of Law's
// threat reduction only applies while it is down; both attach to the aura from their talents.
func (paladin *Paladin) registerRighteousFury() {
	row := RighteousFuryRankMap.HighestRank()
	actionID := core.ActionID{SpellID: row.SpellID}

	paladin.RighteousFuryAura = paladin.RegisterAura(core.Aura{
		Label:    "Righteous Fury",
		ActionID: actionID,
		Duration: core.NeverExpires,
	}).AttachSpellMod(core.SpellModConfig{
		Kind:       core.SpellMod_ThreatMultiplier_Pct,
		School:     core.SpellSchoolHoly,
		FloatValue: row.Effect(shared.A_MOD_THREAT, 2).Value / 100,
	})

	paladin.RegisterSpell(core.SpellConfig{
		ActionID:       actionID,
		SpellSchool:    row.SpellSchool,
		DefenseType:    row.DefenseType,
		ProcMask:       core.ProcMaskEmpty,
		Flags:          core.SpellFlagAPL | core.SpellFlagHelpful,
		ClassSpellMask: SpellMaskRighteousFury,

		ManaCost: manaCost(row),
		Cast: core.CastConfig{
			DefaultCast: core.Cast{
				GCD: row.GCD,
			},
		},

		ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
			spell.RelatedSelfBuff.Activate(sim)
		},

		RelatedSelfBuff: paladin.RighteousFuryAura,
	})
}
