package database

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/wowsims/forever/sim/core/dbcenums"
)

// The two enums a rank effect names. Their constants live in sim/core/dbcenums and are mirrored into
// sim/common/shared because that mirror is what the generated family tables read; the follow-up that
// retires those tables for the store retires the mirror with them.
var rankEnumTypes = []struct {
	dbcType    string
	sharedType string
	fieldDoc   string
	name       func(value int32) (string, bool)
}{
	{"SpellEffectType", "SpellDataEffectKind", "What the effect does - E_SCHOOL_DAMAGE, E_APPLY_AURA.",
		func(value int32) (string, bool) { return dbcenums.Named(dbcenums.SpellEffectType(value)) }},
	{"EffectAuraType", "SpellDataAura", "Which aura it applies, when the effect is E_APPLY_AURA.",
		func(value int32) (string, bool) { return dbcenums.Named(dbcenums.EffectAuraType(value)) }},
}

// The names the generated tables reference, for the values they actually use. A value the client data
// carries but dbcenums has not named keeps its number, so a new aura shows up as a bare int rather
// than failing the build.
type rankEnumNamer struct {
	used map[string]map[int32]bool
}

func newRankEnumNamer() *rankEnumNamer {
	return &rankEnumNamer{used: map[string]map[int32]bool{}}
}

func enumName(dbcType string, value int32) (string, bool) {
	for _, t := range rankEnumTypes {
		if t.dbcType == dbcType {
			return t.name(value)
		}
	}
	return "", false
}

// The expression to write for a value, recording it so the constant gets emitted.
func (n *rankEnumNamer) name(dbcType string, value int32) string {
	name, named := enumName(dbcType, value)
	if !named {
		return fmt.Sprintf("%d", value)
	}
	if n.used[dbcType] == nil {
		n.used[dbcType] = map[int32]bool{}
	}
	n.used[dbcType][value] = true
	return "shared." + name
}

func (n *rankEnumNamer) Effect(value dbcenums.SpellEffectType) string {
	return n.name("SpellEffectType", int32(value))
}

func (n *rankEnumNamer) Aura(value dbcenums.EffectAuraType) string {
	return n.name("EffectAuraType", int32(value))
}

// The store's rows name the same two enums, through the package that declares them. A value the
// client data carries and dbcenums has not named keeps its number, marked so a reader is not left
// looking for a constant.
func (n *rankEnumNamer) storeEffect(value dbcenums.SpellEffectType) string {
	return n.storeName("SpellEffectType", int32(value))
}

func (n *rankEnumNamer) storeAura(value dbcenums.EffectAuraType) string {
	return n.storeName("EffectAuraType", int32(value))
}

func (n *rankEnumNamer) storeName(dbcType string, value int32) string {
	name, named := enumName(dbcType, value)
	if !named {
		return fmt.Sprintf("%d /* unnamed */", value)
	}
	return "dbcenums." + name
}

func (n *rankEnumNamer) render() ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/database/gen_spelldata. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The aura and effect names the generated spell data tables reference, mirrored from\n")
	b.WriteString("// sim/core/dbcenums. Only the values the tables use are emitted, and every name is the one\n")
	b.WriteString("// dbcenums declares, so a name here cannot drift from the one the extractor reads.\n\n")
	b.WriteString("package shared\n")

	for _, t := range rankEnumTypes {
		values := make([]int32, 0, len(n.used[t.dbcType]))
		for v := range n.used[t.dbcType] {
			values = append(values, v)
		}
		sort.Slice(values, func(i, j int) bool { return values[i] < values[j] })
		if len(values) == 0 {
			continue
		}

		fmt.Fprintf(&b, "\n// %s\n", t.fieldDoc)
		fmt.Fprintf(&b, "const (\n")
		for _, v := range values {
			name, _ := t.name(v)
			fmt.Fprintf(&b, "\t%s %s = %d\n", name, t.sharedType, v)
		}
		fmt.Fprintf(&b, ")\n")
	}
	// Refuse to write rather than write something unformatted: the class files go through the same
	// gate, and an unformatted emit would show up as a spurious diff on the next run.
	return format.Source([]byte(b.String()))
}
