package database

// The two generated sim/core/buffs files. A row the generator could not express keeps
// its place as a commented shell naming the reason, the same idiom the on-use
// effects file uses, so a reader of the generated file sees every manifest row.

const tmplStrBuffRows = `
{{- range .SharedCategories}}

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var {{.Var}} = "{{.Name}}"
{{- end}}
{{- range .Rows}}
{{if .Supported}}
// {{.Label}}
{{- range .LeftOut}}
// Left out: {{.}}
{{- end}}
{{- if .CategoryVar}}
var {{.CategoryVar}} = "{{.Category}}"
{{- end}}
var {{.SpellVar}} = spelldata.MustFind({{.SpellID}})
var {{.MetaVar}} = &Meta{
{{.MetaFields}}}
{{- if .HasValue}}
func {{.Go}}Value(talentPoints int32) float64 {
	return {{.MetaVar}}.Value(talentPoints)
}
{{- end}}
func {{.Go}}Duration(talentPoints int32) time.Duration {
	return {{.MetaVar}}.Duration(talentPoints)
}
{{- if .HasCooldown}}
func {{.Go}}Cooldown() time.Duration {
	return {{.MetaVar}}.Cooldown()
}
{{- end}}
func {{.Go}}Aura(unit *core.Unit, isPlayer bool, talentPoints int32{{.ExtraParams}}) *core.Aura {
	{{.Constructor}}
}
{{- else}}
{{if .HasSpell}}// {{.Label}}
{{end}}// func {{.Go}}Aura(unit *core.Unit, isPlayer bool, talentPoints int32{{.ExtraParams}}) *core.Aura // {{.Field}}, {{.Kind}}: {{.Reason}}
{{- end}}
{{- end}}
`

const TmplStrBuffs = `// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
{{- if .NeedsSpells}}
	"time"

{{ end }}
	"github.com/wowsims/forever/sim/core"
{{- if .NeedsEnums}}
	"github.com/wowsims/forever/sim/core/dbcenums"
{{- end}}
	"github.com/wowsims/forever/sim/core/proto"
{{- if .NeedsSpells}}
	"github.com/wowsims/forever/sim/core/spelldata"
{{- end}}
)
` + tmplStrBuffRows + `
func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
{{- range .Rows}}
{{- if and .Supported .HasApply}}
	if {{.ApplyIf}} {
		{{.ApplyBody}}
	}
{{- end}}
{{- end}}
}
`

const TmplStrDebuffs = `// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
{{- if .NeedsSpells}}
	"time"

{{ end }}
	"github.com/wowsims/forever/sim/core"
{{- if .NeedsEnums}}
	"github.com/wowsims/forever/sim/core/dbcenums"
{{- end}}
	"github.com/wowsims/forever/sim/core/proto"
{{- if .NeedsSpells}}
	"github.com/wowsims/forever/sim/core/spelldata"
{{- end}}
)
` + tmplStrBuffRows + `
func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
{{- range .Rows}}
{{- if and .Supported .HasApply}}
	if {{.ApplyIf}} {
		{{.ApplyBody}}
	}
{{- end}}
{{- end}}
}
`
