package database

import (
	"database/sql"
	"fmt"
	"go/format"
	"maps"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
	"github.com/wowsims/forever/sim/core/spelldata"
	"github.com/wowsims/forever/tools/database/overrides"
)

// The generated half of sim/core/spelldata: every spell the sim can reach, with its effects and
// power costs, and the talent curves a trait talent's ranks are priced from. The hand-written half
// of the package states the contract this file writes to - see the comment on store.go - and the
// init below is what installs the data, since package variables are set before any init runs.
func renderStoreFile(rows []storeSpell, curves map[int32][][]float64, hand map[int32][]overrides.HandTrigger,
	namer *rankEnumNamer) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by tools/database/gen_spelldata. DO NOT EDIT.\n\n")
	b.WriteString("package spelldata\n\n")
	b.WriteString("import (\n\"github.com/wowsims/forever/sim/core\"\n\"github.com/wowsims/forever/sim/core/dbcenums\"\n)\n\n")

	b.WriteString("var generatedSpells = []Spell{\n")
	for _, row := range rows {
		b.WriteString(formatStoreRow(row, namer))
	}
	b.WriteString("}\n\n")

	b.WriteString("var generatedCurves = map[int32][][]float64{\n")
	for _, id := range slices.Sorted(maps.Keys(curves)) {
		var rows []string
		for _, row := range curves[id] {
			values := make([]string, len(row))
			for i, v := range row {
				values[i] = num(v)
			}
			rows = append(rows, "{"+strings.Join(values, ", ")+"}")
		}
		fmt.Fprintf(&b, "\t%d: {%s},\n", id, strings.Join(rows, ", "))
	}
	b.WriteString("}\n\n")

	b.WriteString("var generatedHandTriggers = map[int32][]int32{\n")
	for _, id := range slices.Sorted(maps.Keys(hand)) {
		var triggered, reasons []string
		for _, link := range hand[id] {
			triggered = append(triggered, strconv.Itoa(int(link.Triggers)))
			reasons = append(reasons, link.Reason)
		}
		fmt.Fprintf(&b, "\t%d: {%s}, // %s\n", id, strings.Join(triggered, ", "), strings.Join(reasons, "; "))
	}
	b.WriteString("}\n\n")

	b.WriteString("func init() { install(generatedSpells, generatedCurves, generatedHandTriggers) }\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("the generated store does not parse, refusing to write it: %w", err)
	}
	return out, nil
}

// One row per line, with its effects and powers under it: a field the client leaves at zero is left
// out, so what the row states is what the client states. The fields are the mirror's, in the order
// it declares them; spelldata_mirror_test.go holds their names to the store's own.
func formatStoreRow(s storeSpell, namer *rankEnumNamer) string {
	var b strings.Builder
	fmt.Fprintf(&b, "{%s", storeFields(reflect.ValueOf(s), namer))
	if len(s.Effects) > 0 {
		b.WriteString(",\nEffects: []Effect{\n")
		for _, e := range s.Effects {
			fmt.Fprintf(&b, "{%s},\n", storeFields(reflect.ValueOf(e), namer))
		}
		b.WriteString("}")
	}
	if len(s.Powers) > 0 {
		powers := make([]string, len(s.Powers))
		for i, p := range s.Powers {
			powers[i] = "{" + storeFields(reflect.ValueOf(p), namer) + "}"
		}
		fmt.Fprintf(&b, ",\nPowers: []Power{%s}", strings.Join(powers, ", "))
	}
	b.WriteString("},")
	for _, note := range s.overrideNotes {
		fmt.Fprintf(&b, " // %s", note)
	}
	b.WriteString("\n")
	return b.String()
}

// The store type each mirror fills, which says how its float fields are printed.
var storeTypes = map[reflect.Type]reflect.Type{
	reflect.TypeOf(storeSpell{}):  reflect.TypeOf(spelldata.Spell{}),
	reflect.TypeOf(storeEffect{}): reflect.TypeOf(spelldata.Effect{}),
	reflect.TypeOf(storePower{}):  reflect.TypeOf(spelldata.Power{}),
}

// The exported fields a row states, as "Name: value". The effects and the powers are lists of rows
// of their own, which formatStoreRow writes under the row.
func storeFields(row reflect.Value, namer *rankEnumNamer) string {
	store := storeTypes[row.Type()]
	var parts []string
	for i := 0; i < row.NumField(); i++ {
		field, value := row.Type().Field(i), row.Field(i)
		if !field.IsExported() || value.IsZero() || field.Name == "Effects" || field.Name == "Powers" {
			continue
		}
		storeField, _ := store.FieldByName(field.Name)
		parts = append(parts, field.Name+": "+storeValue(value, storeField.Type, namer))
	}
	return strings.Join(parts, ", ")
}

// A value as the store's literal states it. The enums are written by name, a bit field as hex, and a
// float at the precision of the store's field: the mirror keeps every float as a float64.
func storeValue(v reflect.Value, store reflect.Type, namer *rankEnumNamer) string {
	switch x := v.Interface().(type) {
	case string:
		return strconv.Quote(x)
	case dbcenums.SpellEffectType:
		return namer.storeEffect(x)
	case dbcenums.EffectAuraType:
		return namer.storeAura(x)
	case storeProcChanceSource:
		return x.String()
	case core.ProcHint:
		return formatProcHint(x)
	case core.ClassFlags:
		return formatClassFlags(x)
	}

	switch v.Kind() {
	case reflect.Float32, reflect.Float64:
		if store.Kind() == reflect.Float32 {
			return num32(v.Float())
		}
		return num(v.Float())
	case reflect.Uint64:
		return fmt.Sprintf("%#x", v.Uint())
	case reflect.Array, reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Uint32 {
			return fmt.Sprintf("%s{%s}", v.Type(), hexWords(v))
		}
		elems := make([]string, v.Len())
		for i := range elems {
			elems[i] = fmt.Sprintf("%d", v.Index(i).Interface())
		}
		return fmt.Sprintf("%s{%s}", v.Type(), strings.Join(elems, ", "))
	}
	// %d rather than %v, so an integer type with a String method is still written as its number.
	return fmt.Sprintf("%d", v.Interface())
}

// The family is the namespace the mask words are read in, so a mask alone is never emitted without
// one; the client states the mask in decimal, which is how the sim's talent code names it.
func formatClassFlags(f core.ClassFlags) string {
	var words []string
	for i, word := range f.Mask {
		if word != 0 {
			words = append(words, fmt.Sprintf("%d: %d", i, word))
		}
	}
	if len(words) == 0 {
		return fmt.Sprintf("core.ClassFlags{Family: %d}", f.Family)
	}
	return fmt.Sprintf("core.ClassFlags{Family: %d, Mask: [4]uint32{%s}}", f.Family, strings.Join(words, ", "))
}

// A bit field is written as the words that carry bits, by index: most of the 17 attribute words are
// empty on any one spell, and hex is how the client's flag names read.
func hexWords(words reflect.Value) string {
	var set []string
	for i := 0; i < words.Len(); i++ {
		if word := words.Index(i).Uint(); word != 0 {
			set = append(set, fmt.Sprintf("%d: %#x", i, word))
		}
	}
	return strings.Join(set, ", ")
}

// A float32 column is printed at float32 precision: the DB widens it, and the shortest float32 form
// converts back to the same bits without carrying the widening's digits into the file.
func num32(f float64) string {
	return strconv.FormatFloat(f, 'g', -1, 32)
}

// The store's data, ready to write: the rows and the curves. Everything is rendered before anything
// is written, the way the class files are.
func loadStoreInputs(db *sql.DB, ladderIDs []int32, trees map[int]int) (*storeInputs, error) {
	tables, err := loadSpellTables(db)
	if err != nil {
		return nil, err
	}

	roots, gearRoots, err := storeRoots(db, tables, ladderIDs)
	if err != nil {
		return nil, err
	}

	// The extra spells are captured as rows but not as roots: the rendering adds them again from
	// overrides.ExtraSpells, so what is captured has to be everything that rendering will reach - or an extra
	// id would render as a row with a name and nothing else, whether or not the store was
	// regenerated - while the roots stay what the client alone says they are.
	withExtras, err := withExtraIDs(tables, roots)
	if err != nil {
		return nil, err
	}

	// The spells a rank reads a number off by name are roots of their own: nothing inside the closure
	// points at them, so they are asked for once everything else has been reached.
	siblings, err := siblingSpells(db, reachableSpells(tables, withExtras))
	if err != nil {
		return nil, err
	}
	roots = namedIDs(tables, roots, siblings)

	rendered, err := withExtraIDs(tables, roots)
	if err != nil {
		return nil, err
	}
	ids := reachableSpells(tables, rendered)

	nodes, points, err := traitPoints(db, trees)
	if err != nil {
		return nil, err
	}

	in := captureStoreInputs(tables, roots, ids, nodes, points)
	in.ItemRoots = gearRoots
	return in, nil
}

// The store's data, from the client rows it is built from rather than from the database: the same
// path the regeneration check runs, so what it checks is what the generator writes.
func renderStore(in *storeInputs, namer *rankEnumNamer) ([]byte, error) {
	tables := in.tables()

	roots, err := withExtraIDs(tables, in.Roots)
	if err != nil {
		return nil, err
	}
	ids := reachableSpells(tables, roots)
	inStore := map[int32]bool{}
	for _, id := range ids {
		inStore[id] = true
	}

	hand, err := storeHandTriggers(inStore)
	if err != nil {
		return nil, err
	}

	curves := storeCurves(tables, in.TraitNodes, in.TraitPoints, inStore)

	effects := 0
	for _, id := range ids {
		effects += len(tables.Effects[id])
	}
	fmt.Fprintf(progress, "spelldata: %d roots, %d reachable spells, %d effects\n", len(roots), len(ids), effects)

	rows := make([]storeSpell, len(ids))
	for i, id := range ids {
		rows[i] = tables.row(id)
		applyTooltipHints(tables, &rows[i])
	}
	if err := applyOverrides(rows, overrides.Spells); err != nil {
		return nil, err
	}
	if err := applyAreaBonuses(rows, overrides.AreaBonuses); err != nil {
		return nil, err
	}

	return renderStoreFile(rows, curves, hand, namer)
}

// The trigger edges the client's server-side handlers make and the data does not state, by the spell
// that casts them, where the store carries both ends. The store merges them into Drivers() and
// Triggered() beside the edges its effects state; an entry without a reason is refused, the way an
// extra spell is.
func storeHandTriggers(inStore map[int32]bool) (map[int32][]overrides.HandTrigger, error) {
	hand := map[int32][]overrides.HandTrigger{}
	for _, link := range overrides.HandTriggers {
		if link.Reason == "" {
			return nil, fmt.Errorf("the hand trigger %d -> %d states no reason", link.Spell, link.Triggers)
		}
		if inStore[link.Spell] && inStore[link.Triggers] {
			hand[link.Spell] = append(hand[link.Spell], link)
		}
	}
	return hand, nil
}

// A trait talent is one spell whose per-rank numbers sit on the tree's curves. The store indexes
// them by the position EffectN counts by rather than by the client's EffectIndex, which has gaps,
// and a position the tree prices no curve for repeats the spell's own base value: Ladder.Talent
// wants one value per rank on every position up to the last one the tree prices.
//
// Every node of every class tree is read, not only the ones the class files turned into ladders: a
// talent the class file could not name is still a spell the sim can register by id.
//
// A node of one rank has no ladder to state, and its single priced value goes onto the effect's base
// points instead: that is the number the class table states for it, and writing it into the row
// rather than into a curve is what makes Find(id) and Talent(id, 1).Rank(1) agree about it.
func storeCurves(t *spellTables, nodes []traitNode, points map[int32]map[int32]map[int32]float64,
	inStore map[int32]bool) map[int32][][]float64 {
	curves := map[int32][][]float64{}
	pricedBy := map[int32]int32{}

	// What each priced spell was priced at, whether that went into a curve or onto the row's base
	// points, so that a second definition stating the same numbers is not reported as a disagreement.
	pricedRows := map[int32][][]float64{}
	for _, node := range nodes {
		if !inStore[node.SpellID] {
			continue
		}

		// The class generator takes the tree's numbers only where the tree states more ranks than the
		// skill line's own ladder does, so a one-rank node whose spell a skill line teaches is
		// described by its own rows and not by the tree: Ice Block, Last Stand and Relentless Strikes
		// are priced by a node and state the client's base all the same. A node no skill line teaches
		// - a talent Forever added, like Thousand Cuts - has nothing else describing it.
		if node.MaxRanks == 1 && node.TaughtBySkillLine {
			continue
		}

		priced := map[int32]map[int32]float64{}
		for index, curve := range points[node.DefinitionID] {
			if values, ok := curveRanks(curve, node.MaxRanks); ok {
				priced[index] = values
			}
		}

		rows := curveRows(t.Effects[node.SpellID], priced, node.MaxRanks)
		if len(rows) == 0 {
			continue
		}

		// The client keeps retired talent nodes around, and a retired twin prices the same
		// spell as the node the game uses: hunter Lightning Reflexes 19168 is 3/6/9/12/15 on
		// definition 134447 and 2/4/6/8/10 on 142605. The lowest definition id within the
		// first tree by id is the one kept, which is what the class tables generate from, and a
		// disagreement is named on stderr rather than resolved silently.
		if seen, ok := pricedBy[node.SpellID]; ok {
			if !slices.EqualFunc(pricedRows[node.SpellID], rows, slices.Equal) {
				fmt.Fprintf(progress,
					"spelldata: talent definitions %d and %d price spell %d differently, keeping %d\n",
					seen, node.DefinitionID, node.SpellID, seen)
			}
			continue
		}
		pricedBy[node.SpellID] = node.DefinitionID
		pricedRows[node.SpellID] = rows

		if node.MaxRanks == 1 {
			bakeRank(t.Effects[node.SpellID], rows)
			continue
		}
		curves[node.SpellID] = rows
	}
	return curves
}

// The one rank's values onto the effects they belong to, by the position curveRows counted in.
func bakeRank(effects []storeEffect, rows [][]float64) {
	for position, row := range rows {
		effects[position].BasePoints = row[0]
	}
}

// Every class tree's nodes in the order the curves are read in - tree by tree, lowest id first, so
// that the first definition to price a spell is the same one whether the points come from the
// database or from the committed inputs - and the points each definition states.
func traitPoints(db *sql.DB, trees map[int]int) ([]traitNode, map[int32]map[int32]map[int32]float64, error) {
	var all []traitNode
	points := map[int32]map[int32]map[int32]float64{}

	for _, treeID := range slices.Sorted(maps.Values(trees)) {
		nodes, err := traitNodes(db, treeID)
		if err != nil {
			return nil, nil, err
		}
		for _, node := range nodes {
			all = append(all, node)
			if _, ok := points[node.DefinitionID]; ok {
				continue
			}
			curve, err := traitCurves(db, node.DefinitionID)
			if err != nil {
				return nil, nil, err
			}
			points[node.DefinitionID] = curve
		}
	}
	return all, points, nil
}

// One talent node: the definition its curves hang off, the spell it grants and the rank cap the game
// enforces. A one-rank node states no ladder, and its single value is baked into the spell's base
// points by storeCurves rather than kept as a curve of one.
type traitNode struct {
	DefinitionID int32
	SpellID      int32
	MaxRanks     int32

	// Whether a skill line teaches the spell, which is what says the tree is not the only thing
	// describing it - see storeCurves.
	TaughtBySkillLine bool
}

func traitNodes(db *sql.DB, treeID int) ([]traitNode, error) {
	var nodes []traitNode
	err := eachRow(db, fmt.Sprintf(`
		SELECT DISTINCT d.ID, COALESCE(d.SpellID, 0), e.MaxRanks,
		       EXISTS (SELECT 1 FROM SkillLineAbility sla WHERE sla.Spell = d.SpellID)
		FROM TraitNode tn
		JOIN TraitNodeXTraitNodeEntry x ON x.TraitNodeID = tn.ID
		JOIN TraitNodeEntry e ON e.ID = x.TraitNodeEntryID
		JOIN TraitDefinition d ON d.ID = e.TraitDefinitionID
		WHERE tn.TraitTreeID = %d AND d.SpellID > 0 AND e.MaxRanks > 0
		ORDER BY d.ID, e.MaxRanks`, treeID), func(rows *sql.Rows) error {
		var n traitNode
		if err := rows.Scan(&n.DefinitionID, &n.SpellID, &n.MaxRanks, &n.TaughtBySkillLine); err != nil {
			return err
		}
		nodes = append(nodes, n)
		return nil
	})
	return nodes, err
}

// The rank values by effect position, from the curves the tree prices by the client's EffectIndex.
func curveRows(effects []storeEffect, priced map[int32]map[int32]float64, maxRanks int32) [][]float64 {
	last := -1
	for position, e := range effects {
		if priced[int32(e.Index)] != nil {
			last = position
		}
	}
	if last < 0 {
		return nil
	}

	rows := make([][]float64, last+1)
	for position := 0; position <= last; position++ {
		e := effects[position]
		row := make([]float64, maxRanks)
		for rank := int32(1); rank <= maxRanks; rank++ {
			value, ok := priced[int32(e.Index)][rank]
			if !ok {
				value = e.BasePoints
			}
			row[rank-1] = value
		}
		rows[position] = row
	}
	return rows
}
