package database

import (
	"database/sql"
	"fmt"
	"go/format"
	"strings"

	"github.com/wowsims/forever/sim/core/dbcenums"
)

type formRow struct {
	ID    int32
	Name  string
	Flags int64
}

func loadShapeshiftForms(db *sql.DB) ([]formRow, error) {
	var rows []formRow
	err := eachRow(db, `
		SELECT ID, COALESCE(Name_lang, ''), COALESCE(Flags, 0)
		FROM SpellShapeshiftForm ORDER BY ID`, func(r *sql.Rows) error {
		var row formRow
		if err := r.Scan(&row.ID, &row.Name, &row.Flags); err != nil {
			return err
		}
		rows = append(rows, row)
		return nil
	})
	return rows, err
}

// sim/core/dbcenums/forms_auto_gen.go: a FORM_ constant per player-facing form, and stanceForms,
// which sim/core/dbcenums/forms.go's IsStance reads. A row whose name is blank, or starts with
// "Creature - " or "S03 - ", names no form the sim registers a spell against and is skipped in the
// const block, but still counts toward stanceForms if its Flags mark it a stance.
func renderFormsFile(rows []formRow) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by gen_spelldata. DO NOT EDIT.\n\n")
	b.WriteString("package dbcenums\n\n")

	b.WriteString("const (\n")
	seen := map[string]bool{}
	for _, row := range rows {
		if !formIsNamed(row.Name) {
			continue
		}
		name := "FORM_" + strings.ToUpper(toSnakeCase(row.Name))
		if seen[name] {
			return nil, fmt.Errorf("SpellShapeshiftForm %d: %s collides with an earlier row's name", row.ID, name)
		}
		seen[name] = true
		fmt.Fprintf(&b, "\t%s ShapeshiftForm = %d\n", name, row.ID)
	}
	b.WriteString(")\n\n")

	b.WriteString("// The forms whose SpellShapeshiftForm.Flags set bit 1.\n")
	var stances uint64
	for _, row := range rows {
		if row.Flags&1 != 0 {
			stances |= dbcenums.ShapeshiftForm(row.ID).Mask()
		}
	}
	fmt.Fprintf(&b, "const stanceForms uint64 = %#x\n", stances)

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("the generated forms file does not parse, refusing to write it: %w", err)
	}
	return out, nil
}

func formIsNamed(name string) bool {
	return name != "" && !strings.HasPrefix(name, "Creature - ") && !strings.HasPrefix(name, "S03 - ")
}
