package database

// Renders the settings-UI buff and debuff inputs from the resolved manifest into
// ui/features/settings/model/buffs_debuffs_auto_gen.ts.
//
// It is rendered in the same pass as the Go buff files, from the same resolved
// rows, and committed like them.

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
	"text/template"

	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/tools/database/buffmanifest"
)

const buffsDebuffsTSFile = "ui/features/settings/model/buffs_debuffs_auto_gen.ts"

// The state count a multistate input counts up to, copied from the hand-written
// input for that field in ui/features/settings/model/buffs_debuffs.ts. An int32
// field counts casts or mana, and how far it counts is a UI choice the client
// database does not state.
var buffInputNumStates = map[string]int{
	"atiesh_mage":      5,
	"atiesh_warlock":   5,
	"mana_tide_totems": 5,
	"innervates":       11,
	"power_infusions":  11,
}

// The rows whose settings input stays hand-written: it needs something no manifest
// row carries, or the field has no input at all.
var manualBuffInputs = map[string]string{
	"greater_blessing_of_salvation": "the hand-written input hides itself for tank and healing specs, a role gate no manifest row carries.",
	"greater_blessing_of_light":     "the hand-written input shows itself for tank and healing specs only, a role gate no manifest row carries.",
	"retribution_aura":              "the hand-written input shows itself for tank specs only, since a damage shield only matters on the unit being hit; a role gate no manifest row carries.",
	"atiesh_druid":                  "no settings input over this field.",
	"atiesh_priest":                 "no settings input over this field.",
}

type tsBuffInput struct {
	Const     string
	Factory   string
	SpellID   int32
	ImpID     string // the improved icon expression, "" when the input has no improved state
	NumStates int    // 0 when the input is not a multistate one
	FieldName string
	Label     string // already quoted
}

// One manifest row: either the input it renders, or the comment that says why it
// renders none.
type tsBuffRow struct {
	Input   *tsBuffInput
	Comment string
}

type tsBuffRegistryEntry struct {
	Const      string
	Stats      []string
	OwnerClass string // "" when the manifest names no owning class
}

type tsBuffsDebuffs struct {
	Imports    string
	Rows       []tsBuffRow
	Raid       []tsBuffRegistryEntry
	Party      []tsBuffRegistryEntry
	Individual []tsBuffRegistryEntry
	Debuff     []tsBuffRegistryEntry
}

const buffsDebuffsTSTemplate = `// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

{{ .Imports }}
{{- range .Rows }}
{{- if .Comment }}
{{ .Comment }}
{{- else }}
export const {{ .Input.Const }} = {{ .Input.Factory }}({
	actionId: ActionId.fromSpellId({{ .Input.SpellID }}),
{{- if .Input.ImpID }}
	impId: {{ .Input.ImpID }},
{{- end }}
{{- if .Input.NumStates }}
	numStates: {{ .Input.NumStates }},
{{- end }}
	fieldName: '{{ .Input.FieldName }}',
	label: {{ .Input.Label }},
});
{{- end }}
{{ end }}
{{ template "registry" dict "Name" "GENERATED_RAID_BUFFS_CONFIG" "Entries" .Raid }}
{{ template "registry" dict "Name" "GENERATED_PARTY_BUFFS_CONFIG" "Entries" .Party }}
{{ template "registry" dict "Name" "GENERATED_INDIVIDUAL_BUFFS_CONFIG" "Entries" .Individual }}
{{ template "registry" dict "Name" "GENERATED_DEBUFFS_CONFIG" "Entries" .Debuff }}
{{- define "registry" -}}
export const {{ .Name }}: RenderableStatOptions[] = [
{{- range .Entries }}
	{
		config: {{ .Const }},
		stats: [{{ range $index, $stat := .Stats }}{{ if $index }}, {{ end }}Stat.{{ $stat }}{{ end }}],
{{- if .OwnerClass }}
		ownerClass: Class.{{ .OwnerClass }},
{{- end }}
	},
{{- end }}
{{- if .Entries }}
{{ end -}}
];
{{ end }}`

// RenderBuffsDebuffsTS renders one input per resolved row that has one, plus the
// four registries the settings tab reads.
func RenderBuffsDebuffsTS(rows []ResolvedBuff) ([]byte, error) {
	if err := checkBuffInputTables(); err != nil {
		return nil, err
	}

	file := tsBuffsDebuffs{}
	factories := map[string]bool{}
	registries := map[buffmanifest.BuffScope]*[]tsBuffRegistryEntry{
		buffmanifest.ScopeRaid:       &file.Raid,
		buffmanifest.ScopeParty:      &file.Party,
		buffmanifest.ScopeIndividual: &file.Individual,
		buffmanifest.ScopeDebuff:     &file.Debuff,
	}

	for _, row := range rows {
		reason := skipBuffInputReason(row)
		if reason != "" {
			file.Rows = append(file.Rows, tsBuffRow{Comment: strings.Join(wrapTSComment(row.Field+": "+reason), "\n")})
			continue
		}

		input, err := buffInput(row)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", row.Field, err)
		}
		factories[input.Factory] = true
		file.Rows = append(file.Rows, tsBuffRow{Input: input})

		registry, ok := registries[row.Scope]
		if !ok {
			return nil, fmt.Errorf("%s: %s has no registry", row.Field, row.Scope)
		}
		entry := tsBuffRegistryEntry{Const: input.Const}
		for _, stat := range row.BuffSpec.Stats {
			entry.Stats = append(entry.Stats, stat.String())
		}
		if row.Owner != proto.Class_ClassUnknown {
			entry.OwnerClass = row.Owner.String()
		}
		*registry = append(*registry, entry)
	}

	file.Imports = buffsDebuffsTSImports(factories)

	tmpl, err := template.New("buffs_debuffs_ts").Funcs(template.FuncMap{"dict": templateDict}).Parse(buffsDebuffsTSTemplate)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, file); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// A key of either table that names no manifest field is a row that was renamed or
// dropped, and the input it stands for would silently disappear from the settings
// tab, so the generator refuses to render.
func checkBuffInputTables() error {
	fields := map[string]bool{}
	for _, spec := range buffmanifest.All() {
		fields[spec.Field] = true
	}
	for field := range manualBuffInputs {
		if !fields[field] {
			return fmt.Errorf("manualBuffInputs names %q, which is no manifest field", field)
		}
	}
	for field := range buffInputNumStates {
		if !fields[field] {
			return fmt.Errorf("buffInputNumStates names %q, which is no manifest field", field)
		}
	}
	return nil
}

// Why a row renders no input: its hand-written input does something no manifest
// row states, its kind or proto type has no icon input at all, or the client
// describes no spell to hang an icon on.
func skipBuffInputReason(row ResolvedBuff) string {
	if reason, ok := manualBuffInputs[row.Field]; ok {
		return reason
	}
	if reason := uninputtableBuffReason(row); reason != "" {
		return reason
	}
	if row.SpellID == 0 {
		if row.Reason != "" {
			return row.Reason
		}
		return "the client database resolves no spell for it."
	}
	return ""
}

// A row the settings UI never renders an icon for whatever the client says about
// it: the client does not describe the buff at all, the field is a sim toggle or
// a swatch pick rather than a buff, or no icon factory takes its proto type.
func uninputtableBuffReason(row ResolvedBuff) string {
	var fixed string
	switch {
	case row.Kind == buffmanifest.KindFlag:
		fixed = fmt.Sprintf("%s renders no settings input.", row.Kind)
	case row.Proto == buffmanifest.ProtoDouble:
		fixed = fmt.Sprintf("%s has no settings factory.", row.Proto)
	default:
		return ""
	}
	if row.Reason != "" {
		return row.Reason
	}
	return fixed
}

func buffInput(row ResolvedBuff) (*tsBuffInput, error) {
	input := &tsBuffInput{
		Const:     row.Go,
		SpellID:   row.SpellID,
		FieldName: row.TSField(),
		Label:     tsString(buffLabel(row)),
	}

	scopes := map[buffmanifest.BuffScope]string{
		buffmanifest.ScopeRaid:       "RaidBuff",
		buffmanifest.ScopeParty:      "PartyBuff",
		buffmanifest.ScopeIndividual: "IndividualBuff",
	}
	switch row.Proto {
	case buffmanifest.ProtoBool:
		if row.Scope == buffmanifest.ScopeDebuff {
			input.Factory = "makeBooleanDebuffInput"
		} else {
			input.Factory = "makeBoolean" + scopes[row.Scope] + "Input"
		}
	case buffmanifest.ProtoTristate:
		if row.Scope == buffmanifest.ScopeDebuff {
			input.Factory = "makeTristateDebuffInput"
		} else {
			input.Factory = "makeTristate" + scopes[row.Scope] + "Input"
		}
		impID, err := buffInputImpID(row)
		if err != nil {
			return nil, err
		}
		input.ImpID = impID
	case buffmanifest.ProtoInt32:
		if row.Scope == buffmanifest.ScopeDebuff {
			return nil, fmt.Errorf("an int32 debuff has no multistate factory in ui/ui-kit/icon_inputs.ts")
		}
		input.Factory = "makeMultistate" + scopes[row.Scope] + "Input"
		numStates, ok := buffInputNumStates[row.Field]
		if !ok {
			return nil, fmt.Errorf("an int32 row needs a numStates entry in buffInputNumStates")
		}
		input.NumStates = numStates
	default:
		return nil, fmt.Errorf("%s has no settings factory", row.Proto)
	}
	return input, nil
}

// The icon the improved state of a tristate input shows: the item the manifest
// names, or the talent that prices the improvement.
func buffInputImpID(row ResolvedBuff) (string, error) {
	if row.ImpAction != nil {
		switch {
		case row.ImpAction.ItemID != 0:
			return fmt.Sprintf("ActionId.fromItemId(%d)", row.ImpAction.ItemID), nil
		case row.ImpAction.SpellID != 0:
			return fmt.Sprintf("ActionId.fromSpellId(%d)", row.ImpAction.SpellID), nil
		}
	}
	if row.TalentSpellID == 0 {
		return "", fmt.Errorf("a tristate row needs the talent that prices its improved state")
	}
	return fmt.Sprintf("ActionId.fromSpellId(%d)", row.TalentSpellID), nil
}

func buffsDebuffsTSImports(factories map[string]bool) string {
	names := make([]string, 0, len(factories))
	for name := range factories {
		names = append(names, name)
	}
	slices.Sort(names)

	var b strings.Builder
	b.WriteString(tsImport([]string{"Class", "Stat"}, "@generated/proto/common"))
	b.WriteString(tsImport([]string{"ActionId"}, "@sim/proto/action_id"))
	b.WriteString(tsImport(names, "@ui-kit/icon_inputs"))
	b.WriteString("\n")
	b.WriteString("import type { RenderableStatOptions } from './stat_options';\n")
	return b.String()
}

// One import statement, broken over one line per name when the single-line form is
// wider than the formatter's print width.
func tsImport(names []string, from string) string {
	oneLine := fmt.Sprintf("import { %s } from '%s';\n", strings.Join(names, ", "), from)
	if len(oneLine) <= tsPrintWidth+1 {
		return oneLine
	}
	var b strings.Builder
	b.WriteString("import {\n")
	for _, name := range names {
		b.WriteString("\t" + name + ",\n")
	}
	b.WriteString(fmt.Sprintf("} from '%s';\n", from))
	return b.String()
}

// The printWidth of .oxfmtrc.json, which the rendered file has to respect for
// `npx oxfmt --check` to pass without a formatting pass.
const tsPrintWidth = 160

// A TypeScript string literal in the quote style the formatter keeps: single
// quotes, unless the text holds one and double quotes would escape less.
func tsString(text string) string {
	if strings.Contains(text, "'") && !strings.Contains(text, `"`) {
		return `"` + text + `"`
	}
	return "'" + strings.ReplaceAll(text, "'", `\'`) + "'"
}

// A comment broken into lines that fit the print width. The formatter never
// reflows a comment, so the renderer has to.
func wrapTSComment(text string) []string {
	var lines []string
	line := "//"
	for _, word := range strings.Fields(text) {
		if len(line)+1+len(word) > tsPrintWidth {
			lines = append(lines, line)
			line = "//"
		}
		line += " " + word
	}
	return append(lines, line)
}

func templateDict(pairs ...any) (map[string]any, error) {
	if len(pairs)%2 != 0 {
		return nil, fmt.Errorf("a template dict needs an even number of arguments, got %d", len(pairs))
	}
	out := map[string]any{}
	for i := 0; i < len(pairs); i += 2 {
		key, ok := pairs[i].(string)
		if !ok {
			return nil, fmt.Errorf("template dict key %v is not a string", pairs[i])
		}
		out[key] = pairs[i+1]
	}
	return out, nil
}
