// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package mage

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Magic Attunement: missing rank 1 of 2

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Arcane Concentration: effect 1 of spell 11213 has no rank curve and is held at its base points
//   Fingers of Frost: effect 1 of spell 400647 has no rank curve and is held at its base points
//   Hot Streak: effect 0 of spell 400624 has no rank curve and is held at its base points
//   Missile Barrage: effect 0, 1 of spell 400588 has no rank curve and is held at its base points
//   Piercing Ice: effect 1 of spell 11151 has no rank curve and is held at its base points

type generatedSpellData struct {
	AmplifyMagic                 spelldata.Ladder
	ArcaneBlast                  spelldata.Ladder
	ArcaneBlastTriggered         spelldata.Ladder
	ArcaneBrilliance             spelldata.Ladder
	ArcaneConcentration          spelldata.Ladder
	ArcaneConcentrationTriggered spelldata.Ladder
	ArcaneExplosion              spelldata.Ladder
	ArcaneFocus                  spelldata.Ladder
	ArcaneGeometry               spelldata.Ladder
	ArcaneImpact                 spelldata.Ladder
	ArcaneInstability            spelldata.Ladder
	ArcaneIntellect              spelldata.Ladder
	ArcaneMeditation             spelldata.Ladder
	ArcaneMind                   spelldata.Ladder
	ArcaneMissiles               spelldata.Ladder
	ArcaneMissilesTriggered      spelldata.Ladder
	ArcanePower                  spelldata.Ladder
	ArcaneResilience             spelldata.Ladder
	ArcaneShielding              spelldata.Ladder
	ArcaneSubtlety               spelldata.Ladder
	ArcticReach                  spelldata.Ladder
	BlastWave                    spelldata.Ladder
	Blink                        spelldata.Ladder
	Blizzard                     spelldata.Ladder
	BlizzardTriggered            spelldata.Ladder
	BurningSoul                  spelldata.Ladder
	Chilled                      spelldata.Ladder
	Clearcasting                 spelldata.Ladder
	ColdSnap                     spelldata.Ladder
	Combustion                   spelldata.Ladder
	CombustionTriggered          spelldata.Ladder
	ConeOfCold                   spelldata.Ladder
	ConjureFood                  spelldata.Ladder
	ConjureManaAgate             spelldata.Ladder
	ConjureManaAgateTriggered    spelldata.Ladder
	ConjureManaCitrine           spelldata.Ladder
	ConjureManaCitrineTriggered  spelldata.Ladder
	ConjureManaJade              spelldata.Ladder
	ConjureManaJadeTriggered     spelldata.Ladder
	ConjureManaRuby              spelldata.Ladder
	ConjureManaRubyTriggered     spelldata.Ladder
	ConjureWater                 spelldata.Ladder
	Counterspell                 spelldata.Ladder
	CriticalMass                 spelldata.Ladder
	DampenMagic                  spelldata.Ladder
	ElementalPrecision           spelldata.Ladder
	Evocation                    spelldata.Ladder
	ExpandedIntellect            spelldata.Ladder
	Felfire                      spelldata.Ladder
	FingersOfFrost               spelldata.Ladder
	FingersOfFrostTriggered      spelldata.Ladder
	FireBlast                    spelldata.Ladder
	FirePower                    spelldata.Ladder
	FireVulnerability            spelldata.Ladder
	FireWard                     spelldata.Ladder
	Fireball                     spelldata.Ladder
	FlameThrowing                spelldata.Ladder
	Flamestrike                  spelldata.Ladder
	FlamestrikeTriggered         spelldata.Ladder
	FrostArmor                   spelldata.Ladder
	FrostArmorTriggered          spelldata.Ladder
	FrostChanneling              spelldata.Ladder
	FrostNova                    spelldata.Ladder
	FrostWard                    spelldata.Ladder
	FrostWarding                 spelldata.Ladder
	Frostbite                    spelldata.Ladder
	FrostbiteTriggered           spelldata.Ladder
	Frostbolt                    spelldata.Ladder
	FrostfireBolt                spelldata.Ladder
	HotStreak                    spelldata.Ladder
	HotStreakTriggered           spelldata.Ladder
	IceArmor                     spelldata.Ladder
	IceArmorTriggered            spelldata.Ladder
	IceBarrier                   spelldata.Ladder
	IceBlock                     spelldata.Ladder
	IceLance                     spelldata.Ladder
	IceShards                    spelldata.Ladder
	Ignite                       spelldata.Ladder
	IgniteTriggered              spelldata.Ladder
	Impact                       spelldata.Ladder
	ImpactTriggered              spelldata.Ladder
	ImprovedBlizzard             spelldata.Ladder
	ImprovedBlizzardTriggered    spelldata.Ladder
	ImprovedChanneling           spelldata.Ladder
	ImprovedConeOfCold           spelldata.Ladder
	ImprovedCounterspell         spelldata.Ladder
	ImprovedFireWard             spelldata.Ladder
	ImprovedFireball             spelldata.Ladder
	ImprovedFlamestrike          spelldata.Ladder
	ImprovedFrostNova            spelldata.Ladder
	ImprovedFrostbolt            spelldata.Ladder
	ImprovedScorch               spelldata.Ladder
	ImprovedScorchTriggered      spelldata.Ladder
	Incineration                 spelldata.Ladder
	MageArmor                    spelldata.Ladder
	MagicAbsorption              spelldata.Ladder
	ManaShield                   spelldata.Ladder
	MasterOfElements             spelldata.Ladder
	MissileBarrage               spelldata.Ladder
	MissileBarrageTriggered      spelldata.Ladder
	Permafrost                   spelldata.Ladder
	PiercingIce                  spelldata.Ladder
	Polymorph                    spelldata.Ladder
	PolymorphCow                 spelldata.Ladder
	PortalDarnassus              spelldata.Ladder
	PortalIronforge              spelldata.Ladder
	PortalOrgrimmar              spelldata.Ladder
	PortalStormwind              spelldata.Ladder
	PortalThunderBluff           spelldata.Ladder
	PortalUndercity              spelldata.Ladder
	PresenceOfMind               spelldata.Ladder
	Pyroblast                    spelldata.Ladder
	RemoveLesserCurse            spelldata.Ladder
	Scorch                       spelldata.Ladder
	Shatter                      spelldata.Ladder
	SlowFall                     spelldata.Ladder
	TeleportDalaran              spelldata.Ladder
	TeleportDarnassus            spelldata.Ladder
	TeleportIronforge            spelldata.Ladder
	TeleportOrgrimmar            spelldata.Ladder
	TeleportStormwind            spelldata.Ladder
	TeleportThunderBluff         spelldata.Ladder
	TeleportUndercity            spelldata.Ladder
	WakeOfFire                   spelldata.Ladder
	WakeOfFireTriggered          spelldata.Ladder
	WandSpecialization           spelldata.Ladder
	WintersChill                 spelldata.Ladder
	WintersChillTriggered        spelldata.Ladder
}

var spellData = generatedSpellData{
	AmplifyMagic:                 spelldata.Ranked(1008, 8455, 10169, 10170),
	ArcaneBlast:                  spelldata.Ranked(400574, 1239696, 1239697, 1239699, 1239700),
	ArcaneBlastTriggered:         spelldata.Ranked(400573),
	ArcaneBrilliance:             spelldata.Ranked(23028),
	ArcaneConcentration:          spelldata.Talent(11213, 5),
	ArcaneConcentrationTriggered: spelldata.Ranked(12536),
	ArcaneExplosion:              spelldata.Ranked(1449, 8437, 8438, 8439, 10201, 10202),
	ArcaneFocus:                  spelldata.Talent(11222, 5),
	ArcaneGeometry:               spelldata.Talent(11247, 2),
	ArcaneImpact:                 spelldata.Talent(11242, 3),
	ArcaneInstability:            spelldata.Talent(15058, 3),
	ArcaneIntellect:              spelldata.Ranked(1459, 1460, 1461, 10156, 10157),
	ArcaneMeditation:             spelldata.Talent(18462, 3),
	ArcaneMind:                   spelldata.Talent(11232, 5),
	ArcaneMissiles:               spelldata.Ranked(5143, 5144, 5145, 8416, 8417, 10211, 10212, 25345),
	ArcaneMissilesTriggered:      spelldata.Ranked(7268, 7269, 7270, 8419, 8418, 10273, 10274, 25346),
	ArcanePower:                  spelldata.Ranked(12042),
	ArcaneResilience:             spelldata.Talent(28574, 2),
	ArcaneShielding:              spelldata.Talent(11252, 2),
	ArcaneSubtlety:               spelldata.Talent(11210, 2),
	ArcticReach:                  spelldata.Talent(16757, 2),
	BlastWave:                    spelldata.Ranked(11113, 13018, 13019, 13020, 13021),
	Blink:                        spelldata.Ranked(1953),
	Blizzard:                     spelldata.Ranked(10, 6141, 8427, 10185, 10186, 10187),
	BlizzardTriggered:            spelldata.Ranked(1279976, 1279977, 1279978, 1279979, 1279980, 1279949),
	BurningSoul:                  spelldata.Talent(11083, 3),
	Chilled:                      spelldata.Ranked(12484),
	Clearcasting:                 spelldata.Ranked(12536),
	ColdSnap:                     spelldata.Ranked(12472),
	Combustion:                   spelldata.Ranked(11129),
	CombustionTriggered:          spelldata.Ranked(28682),
	ConeOfCold:                   spelldata.Ranked(120, 8492, 10159, 10160, 10161),
	ConjureFood:                  spelldata.Ranked(587, 597, 990, 6129, 10144, 10145, 28612),
	ConjureManaAgate:             spelldata.Ranked(759),
	ConjureManaAgateTriggered:    spelldata.Ranked(5405),
	ConjureManaCitrine:           spelldata.Ranked(10053),
	ConjureManaCitrineTriggered:  spelldata.Ranked(10057),
	ConjureManaJade:              spelldata.Ranked(3552),
	ConjureManaJadeTriggered:     spelldata.Ranked(10052),
	ConjureManaRuby:              spelldata.Ranked(10054),
	ConjureManaRubyTriggered:     spelldata.Ranked(10058),
	ConjureWater:                 spelldata.Ranked(5504, 5505, 5506, 6127, 10138, 10139, 10140, 468766),
	Counterspell:                 spelldata.Ranked(2139),
	CriticalMass:                 spelldata.Talent(11115, 3),
	DampenMagic:                  spelldata.Ranked(604, 8450, 8451, 10173, 10174),
	ElementalPrecision:           spelldata.Talent(29438, 5),
	Evocation:                    spelldata.Ranked(12051),
	ExpandedIntellect:            spelldata.Ranked(436949),
	Felfire:                      spelldata.Ranked(24530),
	FingersOfFrost:               spelldata.Talent(400647, 2),
	FingersOfFrostTriggered:      spelldata.Ranked(400669),
	FireBlast:                    spelldata.Ranked(2136, 2137, 2138, 8412, 8413, 10197, 10199),
	FirePower:                    spelldata.Talent(11124, 5),
	FireVulnerability:            spelldata.Ranked(22959),
	FireWard:                     spelldata.Ranked(543, 8457, 8458, 10223, 10225),
	Fireball:                     spelldata.Ranked(133, 143, 145, 3140, 8400, 8401, 8402, 10148, 10149, 10150, 10151, 25306),
	FlameThrowing:                spelldata.Talent(11100, 2),
	Flamestrike:                  spelldata.Ranked(2120, 2121, 8422, 8423, 10215, 10216),
	FlamestrikeTriggered:         spelldata.Ranked(1279983, 1279985, 1279987, 1279988, 1279989, 1279990),
	FrostArmor:                   spelldata.Ranked(168, 7300, 7301),
	FrostArmorTriggered:          spelldata.Ranked(6136),
	FrostChanneling:              spelldata.Talent(11160, 3),
	FrostNova:                    spelldata.Ranked(122, 865, 6131, 10230),
	FrostWard:                    spelldata.Ranked(6143, 8461, 8462, 10177, 28609),
	FrostWarding:                 spelldata.Talent(11189, 2),
	Frostbite:                    spelldata.Talent(11071, 3),
	FrostbiteTriggered:           spelldata.Ranked(12494),
	Frostbolt:                    spelldata.Ranked(116, 205, 837, 7322, 8406, 8407, 8408, 10179, 10180, 10181, 25304),
	FrostfireBolt:                spelldata.Ranked(401502, 1237312, 1237313),
	HotStreak:                    spelldata.Talent(400624, 1),
	HotStreakTriggered:           spelldata.Ranked(400625),
	IceArmor:                     spelldata.Ranked(7302, 7320, 10219, 10220),
	IceArmorTriggered:            spelldata.Ranked(7321),
	IceBarrier:                   spelldata.Ranked(11426, 13031, 13032, 13033),
	IceBlock:                     spelldata.Ranked(11958),
	IceLance:                     spelldata.Ranked(1312002, 400640, 1240044, 1240045, 1240046, 1240047),
	IceShards:                    spelldata.Talent(11207, 5),
	Ignite:                       spelldata.Talent(11119, 5),
	IgniteTriggered:              spelldata.Ranked(412538),
	Impact:                       spelldata.Talent(11103, 3),
	ImpactTriggered:              spelldata.Ranked(12355),
	ImprovedBlizzard:             spelldata.Talent(11185, 3),
	ImprovedBlizzardTriggered:    spelldata.Ranked(12484),
	ImprovedChanneling:           spelldata.Talent(11237, 5),
	ImprovedConeOfCold:           spelldata.Talent(11190, 3),
	ImprovedCounterspell:         spelldata.Talent(11255, 2),
	ImprovedFireWard:             spelldata.Talent(11094, 2),
	ImprovedFireball:             spelldata.Talent(11069, 5),
	ImprovedFlamestrike:          spelldata.Talent(11108, 3),
	ImprovedFrostNova:            spelldata.Talent(11165, 2),
	ImprovedFrostbolt:            spelldata.Talent(11070, 5),
	ImprovedScorch:               spelldata.Talent(11095, 3),
	ImprovedScorchTriggered:      spelldata.Ranked(22959),
	Incineration:                 spelldata.Talent(18459, 3),
	MageArmor:                    spelldata.Ranked(6117, 22782, 22783),
	MagicAbsorption:              spelldata.Talent(29441, 2),
	ManaShield:                   spelldata.Ranked(1463, 8494, 8495, 10191, 10192, 10193),
	MasterOfElements:             spelldata.Talent(29074, 3),
	MissileBarrage:               spelldata.Talent(400588, 1),
	MissileBarrageTriggered:      spelldata.Ranked(400589),
	Permafrost:                   spelldata.Talent(11175, 3),
	PiercingIce:                  spelldata.Talent(11151, 3),
	Polymorph:                    spelldata.Ranked(118, 12824, 12825, 12826),
	PolymorphCow:                 spelldata.Ranked(28270),
	PortalDarnassus:              spelldata.Ranked(11419),
	PortalIronforge:              spelldata.Ranked(11416),
	PortalOrgrimmar:              spelldata.Ranked(11417),
	PortalStormwind:              spelldata.Ranked(10059),
	PortalThunderBluff:           spelldata.Ranked(11420),
	PortalUndercity:              spelldata.Ranked(11418),
	PresenceOfMind:               spelldata.Ranked(12043),
	Pyroblast:                    spelldata.Ranked(11366, 12505, 12522, 12523, 12524, 12525, 12526, 18809),
	RemoveLesserCurse:            spelldata.Ranked(475),
	Scorch:                       spelldata.Ranked(2948, 8444, 8445, 8446, 10205, 10206, 10207),
	Shatter:                      spelldata.Talent(11170, 3),
	SlowFall:                     spelldata.Ranked(130),
	TeleportDalaran:              spelldata.Ranked(1297659),
	TeleportDarnassus:            spelldata.Ranked(3565),
	TeleportIronforge:            spelldata.Ranked(3562),
	TeleportOrgrimmar:            spelldata.Ranked(3567),
	TeleportStormwind:            spelldata.Ranked(3561),
	TeleportThunderBluff:         spelldata.Ranked(3566),
	TeleportUndercity:            spelldata.Ranked(3563),
	WakeOfFire:                   spelldata.Talent(11078, 2),
	WakeOfFireTriggered:          spelldata.Ranked(1312934),
	WandSpecialization:           spelldata.Talent(6057, 2),
	WintersChill:                 spelldata.Talent(11180, 5),
	WintersChillTriggered:        spelldata.Ranked(12579),
}
