package dbcenums

// SpellEffect.Effect. Every id is listed: one with no known name is E_<id>, and one that is neither
// named nor read is commented out.
type SpellEffectType int

const (
	E_NONE                                          SpellEffectType = 0
	E_INSTAKILL                                     SpellEffectType = 1
	E_SCHOOL_DAMAGE                                 SpellEffectType = 2
	E_DUMMY                                         SpellEffectType = 3
	E_PORTAL_TELEPORT                               SpellEffectType = 4
	E_UNK_ITEM_MOD                                  SpellEffectType = 5
	E_APPLY_AURA                                    SpellEffectType = 6
	E_ENVIRONMENTAL_DAMAGE                          SpellEffectType = 7
	E_POWER_DRAIN                                   SpellEffectType = 8
	E_HEALTH_LEECH                                  SpellEffectType = 9
	E_HEAL                                          SpellEffectType = 10
	E_BIND                                          SpellEffectType = 11
	E_PORTAL                                        SpellEffectType = 12
	E_TELEPORT_TO_RETURN_POINT                      SpellEffectType = 13
	E_INCREASE_CURRENCY_CAP                         SpellEffectType = 14
	E_TELEPORT_WITH_SPELL_VISUAL_KIT_LOADING_SCREEN SpellEffectType = 15
	E_QUEST_COMPLETE                                SpellEffectType = 16
	E_WEAPON_DAMAGE_NOSCHOOL                        SpellEffectType = 17
	E_RESURRECT                                     SpellEffectType = 18
	E_ADD_EXTRA_ATTACKS                             SpellEffectType = 19
	E_DODGE                                         SpellEffectType = 20
	E_EVADE                                         SpellEffectType = 21
	E_PARRY                                         SpellEffectType = 22
	E_BLOCK                                         SpellEffectType = 23
	E_CREATE_ITEM                                   SpellEffectType = 24
	E_WEAPON                                        SpellEffectType = 25
	E_DEFENSE                                       SpellEffectType = 26
	E_PERSISTENT_AREA_AURA                          SpellEffectType = 27
	E_SUMMON                                        SpellEffectType = 28
	E_LEAP                                          SpellEffectType = 29
	E_ENERGIZE                                      SpellEffectType = 30
	E_WEAPON_PERCENT_DAMAGE                         SpellEffectType = 31
	E_TRIGGER_MISSILE                               SpellEffectType = 32
	E_OPEN_LOCK                                     SpellEffectType = 33
	E_SUMMON_CHANGE_ITEM                            SpellEffectType = 34
	E_APPLY_AREA_AURA_PARTY                         SpellEffectType = 35
	E_LEARN_SPELL                                   SpellEffectType = 36
	E_SPELL_DEFENSE                                 SpellEffectType = 37
	E_DISPEL                                        SpellEffectType = 38
	E_LANGUAGE                                      SpellEffectType = 39
	E_DUAL_WIELD                                    SpellEffectType = 40
	E_JUMP                                          SpellEffectType = 41
	E_JUMP_DEST                                     SpellEffectType = 42
	E_TELEPORT_UNITS_FACE_CASTER                    SpellEffectType = 43
	E_SKILL_STEP                                    SpellEffectType = 44
	E_PLAY_MOVIE                                    SpellEffectType = 45
	E_SPAWN                                         SpellEffectType = 46
	E_TRADE_SKILL                                   SpellEffectType = 47
	E_STEALTH                                       SpellEffectType = 48
	E_DETECT                                        SpellEffectType = 49
	E_TRANS_DOOR                                    SpellEffectType = 50
	E_FORCE_CRITICAL_HIT                            SpellEffectType = 51
	E_SET_MAX_BATTLE_PET_COUNT                      SpellEffectType = 52
	E_ENCHANT_ITEM                                  SpellEffectType = 53
	E_ENCHANT_ITEM_TEMPORARY                        SpellEffectType = 54
	E_TAMECREATURE                                  SpellEffectType = 55
	E_SUMMON_PET                                    SpellEffectType = 56
	E_LEARN_PET_SPELL                               SpellEffectType = 57
	E_WEAPON_DAMAGE                                 SpellEffectType = 58
	E_CREATE_RANDOM_ITEM                            SpellEffectType = 59
	E_PROFICIENCY                                   SpellEffectType = 60
	E_SEND_EVENT                                    SpellEffectType = 61
	E_POWER_BURN                                    SpellEffectType = 62
	E_THREAT                                        SpellEffectType = 63
	E_TRIGGER_SPELL                                 SpellEffectType = 64
	E_APPLY_AREA_AURA_RAID                          SpellEffectType = 65
	E_RECHARGE_ITEM                                 SpellEffectType = 66
	E_HEAL_MAX_HEALTH                               SpellEffectType = 67
	E_INTERRUPT_CAST                                SpellEffectType = 68
	E_DISTRACT                                      SpellEffectType = 69
	E_PULL                                          SpellEffectType = 70
	E_PICKPOCKET                                    SpellEffectType = 71
	E_ADD_FARSIGHT                                  SpellEffectType = 72
	E_UNTRAIN_TALENTS                               SpellEffectType = 73
	E_APPLY_GLYPH                                   SpellEffectType = 74
	E_HEAL_MECHANICAL                               SpellEffectType = 75
	E_SUMMON_OBJECT_WILD                            SpellEffectType = 76
	E_SCRIPT_EFFECT                                 SpellEffectType = 77
	E_ATTACK                                        SpellEffectType = 78
	E_SANCTUARY                                     SpellEffectType = 79
	E_MODIFY_FOLLOWER_ITEM_LEVEL                    SpellEffectType = 80
	E_PUSH_ABILITY_TO_ACTION_BAR                    SpellEffectType = 81
	E_BIND_SIGHT                                    SpellEffectType = 82
	E_DUEL                                          SpellEffectType = 83
	E_STUCK                                         SpellEffectType = 84
	E_SUMMON_PLAYER                                 SpellEffectType = 85
	E_ACTIVATE_OBJECT                               SpellEffectType = 86
	E_GAMEOBJECT_DAMAGE                             SpellEffectType = 87
	E_GAMEOBJECT_REPAIR                             SpellEffectType = 88
	E_GAMEOBJECT_SET_DESTRUCTION_STATE              SpellEffectType = 89
	E_KILL_CREDIT                                   SpellEffectType = 90
	E_THREAT_ALL                                    SpellEffectType = 91
	E_ENCHANT_HELD_ITEM                             SpellEffectType = 92
	E_FORCE_DESELECT                                SpellEffectType = 93
	E_SELF_RESURRECT                                SpellEffectType = 94
	E_SKINNING                                      SpellEffectType = 95
	E_CHARGE                                        SpellEffectType = 96
	E_CAST_BUTTON                                   SpellEffectType = 97
	E_KNOCK_BACK                                    SpellEffectType = 98
	E_DISENCHANT                                    SpellEffectType = 99
	E_INEBRIATE                                     SpellEffectType = 100
	E_FEED_PET                                      SpellEffectType = 101
	E_DISMISS_PET                                   SpellEffectType = 102
	E_REPUTATION                                    SpellEffectType = 103
	E_SUMMON_OBJECT_SLOT1                           SpellEffectType = 104
	E_SURVEY                                        SpellEffectType = 105
	E_CHANGE_RAID_MARKER                            SpellEffectType = 106
	E_SHOW_CORPSE_LOOT                              SpellEffectType = 107
	E_DISPEL_MECHANIC                               SpellEffectType = 108
	E_RESURRECT_PET                                 SpellEffectType = 109
	E_DESTROY_ALL_TOTEMS                            SpellEffectType = 110
	E_DURABILITY_DAMAGE                             SpellEffectType = 111
	// E_112 SpellEffectType = 112
	E_CANCEL_CONVERSATION   SpellEffectType = 113
	E_ATTACK_ME             SpellEffectType = 114
	E_DURABILITY_DAMAGE_PCT SpellEffectType = 115
	E_SKIN_PLAYER_CORPSE    SpellEffectType = 116
	E_SPIRIT_HEAL           SpellEffectType = 117
	E_SKILL                 SpellEffectType = 118
	E_APPLY_AREA_AURA_PET   SpellEffectType = 119
	E_TELEPORT_GRAVEYARD    SpellEffectType = 120
	E_NORMALIZED_WEAPON_DMG SpellEffectType = 121
	// E_122 SpellEffectType = 122
	E_SEND_TAXI                        SpellEffectType = 123
	E_PULL_TOWARDS                     SpellEffectType = 124
	E_MODIFY_THREAT_PERCENT            SpellEffectType = 125
	E_STEAL_BENEFICIAL_BUFF            SpellEffectType = 126
	E_PROSPECTING                      SpellEffectType = 127
	E_APPLY_AREA_AURA_FRIEND           SpellEffectType = 128
	E_APPLY_AREA_AURA_ENEMY            SpellEffectType = 129
	E_REDIRECT_THREAT                  SpellEffectType = 130
	E_PLAY_SOUND                       SpellEffectType = 131
	E_PLAY_MUSIC                       SpellEffectType = 132
	E_UNLEARN_SPECIALIZATION           SpellEffectType = 133
	E_KILL_CREDIT2                     SpellEffectType = 134
	E_CALL_PET                         SpellEffectType = 135
	E_HEAL_PCT                         SpellEffectType = 136
	E_ENERGIZE_PCT                     SpellEffectType = 137
	E_LEAP_BACK                        SpellEffectType = 138
	E_CLEAR_QUEST                      SpellEffectType = 139
	E_FORCE_CAST                       SpellEffectType = 140
	E_FORCE_CAST_WITH_VALUE            SpellEffectType = 141
	E_TRIGGER_SPELL_WITH_VALUE         SpellEffectType = 142
	E_APPLY_AREA_AURA_OWNER            SpellEffectType = 143
	E_KNOCK_BACK_DEST                  SpellEffectType = 144
	E_PULL_TOWARDS_DEST                SpellEffectType = 145
	E_RESTORE_GARRISON_TROOP_VITALITY  SpellEffectType = 146
	E_QUEST_FAIL                       SpellEffectType = 147
	E_TRIGGER_MISSILE_SPELL_WITH_VALUE SpellEffectType = 148
	E_CHARGE_DEST                      SpellEffectType = 149
	E_QUEST_START                      SpellEffectType = 150
	E_TRIGGER_SPELL_2                  SpellEffectType = 151
	E_SUMMON_RAF_FRIEND                SpellEffectType = 152
	E_CREATE_TAMED_PET                 SpellEffectType = 153
	E_DISCOVER_TAXI                    SpellEffectType = 154
	E_TITAN_GRIP                       SpellEffectType = 155
	E_ENCHANT_ITEM_PRISMATIC           SpellEffectType = 156
	E_CREATE_LOOT                      SpellEffectType = 157
	E_MILLING                          SpellEffectType = 158
	E_ALLOW_RENAME_PET                 SpellEffectType = 159
	E_FORCE_CAST_2                     SpellEffectType = 160
	E_TALENT_SPEC_COUNT                SpellEffectType = 161
	E_TALENT_SPEC_SELECT               SpellEffectType = 162
	E_OBLITERATE_ITEM                  SpellEffectType = 163
	E_REMOVE_AURA                      SpellEffectType = 164
	E_DAMAGE_FROM_MAX_HEALTH_PCT       SpellEffectType = 165
	E_GIVE_CURRENCY                    SpellEffectType = 166
	E_UPDATE_PLAYER_PHASE              SpellEffectType = 167
	E_ALLOW_CONTROL_PET                SpellEffectType = 168
	E_DESTROY_ITEM                     SpellEffectType = 169
	E_UPDATE_ZONE_AURAS_AND_PHASES     SpellEffectType = 170
	E_SUMMON_PERSONAL_GAMEOBJECT       SpellEffectType = 171
	E_RESURRECT_WITH_AURA              SpellEffectType = 172
	E_UNLOCK_GUILD_VAULT_TAB           SpellEffectType = 173
	E_APPLY_AURA_ON_PET                SpellEffectType = 174
	// E_175 SpellEffectType = 175
	E_SANCTUARY_2                  SpellEffectType = 176
	E_DESPAWN_PERSISTENT_AREA_AURA SpellEffectType = 177
	// E_178 SpellEffectType = 178
	E_CREATE_AREATRIGGER  SpellEffectType = 179
	E_UPDATE_AREATRIGGER  SpellEffectType = 180
	E_REMOVE_TALENT       SpellEffectType = 181
	E_DESPAWN_AREATRIGGER SpellEffectType = 182
	// E_183 SpellEffectType = 183
	E_REPUTATION_2 SpellEffectType = 184
	// E_185 SpellEffectType = 185
	// E_186 SpellEffectType = 186
	E_RANDOMIZE_ARCHAEOLOGY_DIGSITES SpellEffectType = 187
	E_SUMMON_STABLED_PET_AS_GUARDIAN SpellEffectType = 188
	E_LOOT                           SpellEffectType = 189
	E_CHANGE_PARTY_MEMBERS           SpellEffectType = 190
	E_TELEPORT_TO_DIGSITE            SpellEffectType = 191
	E_UNCAGE_BATTLEPET               SpellEffectType = 192
	E_START_PET_BATTLE               SpellEffectType = 193
	// E_194 SpellEffectType = 194
	E_PLAY_SCENE_SCRIPT_PACKAGE    SpellEffectType = 195
	E_CREATE_SCENE_OBJECT          SpellEffectType = 196
	E_CREATE_PERSONAL_SCENE_OBJECT SpellEffectType = 197
	E_PLAY_SCENE                   SpellEffectType = 198
	E_DESPAWN_SUMMON               SpellEffectType = 199
	E_HEAL_BATTLEPET_PCT           SpellEffectType = 200
	E_ENABLE_BATTLE_PETS           SpellEffectType = 201
	E_APPLY_AURA_ON_UNKNOWN        SpellEffectType = 202 // originally "APPLY_AURA_ON_?"
	E_REMOVE_AURA_2                SpellEffectType = 203
	E_CHANGE_BATTLEPET_QUALITY     SpellEffectType = 204
	E_LAUNCH_QUEST_CHOICE          SpellEffectType = 205
	E_ALTER_ITEM                   SpellEffectType = 206
	E_LAUNCH_QUEST_TASK            SpellEffectType = 207
	E_SET_REPUTATION               SpellEffectType = 208
	// E_209 SpellEffectType = 209
	E_LEARN_GARRISON_BUILDING       SpellEffectType = 210
	E_LEARN_GARRISON_SPECIALIZATION SpellEffectType = 211
	E_REMOVE_AURA_BY_SPELL_LABEL    SpellEffectType = 212
	E_JUMP_TO_DESTINATION_2         SpellEffectType = 213
	E_CREATE_GARRISON               SpellEffectType = 214
	E_UPGRADE_CHARACTER_SPELLS      SpellEffectType = 215
	E_CREATE_SHIPMENT               SpellEffectType = 216
	E_UPGRADE_GARRISON              SpellEffectType = 217
	// E_218 SpellEffectType = 218
	E_CREATE_CONVERSATION        SpellEffectType = 219
	E_ADD_GARRISON_FOLLOWER      SpellEffectType = 220
	E_ADD_GARRISON_MISSION       SpellEffectType = 221
	E_CREATE_HEIRLOOM_ITEM       SpellEffectType = 222
	E_CHANGE_ITEM_BONUSES        SpellEffectType = 223
	E_ACTIVATE_GARRISON_BUILDING SpellEffectType = 224
	E_GRANT_BATTLEPET_LEVEL      SpellEffectType = 225
	E_TRIGGER_ACTION_SET         SpellEffectType = 226
	E_TELEPORT_TO_LFG_DUNGEON    SpellEffectType = 227
	// E_228 SpellEffectType = 228
	E_SET_FOLLOWER_QUALITY         SpellEffectType = 229
	E_INCREASE_FOLLOWER_ITEM_LEVEL SpellEffectType = 230
	E_INCREASE_FOLLOWER_EXPERIENCE SpellEffectType = 231
	E_REMOVE_PHASE                 SpellEffectType = 232
	E_RANDOMIZE_FOLLOWER_ABILITIES SpellEffectType = 233
	// E_234 SpellEffectType = 234
	// E_235 SpellEffectType = 235
	E_GIVE_EXPERIENCE                    SpellEffectType = 236
	E_GIVE_RESTED_EXPERIENCE_BONUS       SpellEffectType = 237
	E_INCREASE_SKILL                     SpellEffectType = 238
	E_END_GARRISON_BUILDING_CONSTRUCTION SpellEffectType = 239
	E_GIVE_ARTIFACT_POWER                SpellEffectType = 240
	// E_241 SpellEffectType = 241
	E_GIVE_ARTIFACT_POWER_NO_BONUS SpellEffectType = 242
	E_APPLY_ENCHANT_ILLUSION       SpellEffectType = 243
	E_LEARN_FOLLOWER_ABILITY       SpellEffectType = 244
	E_UPGRADE_HEIRLOOM             SpellEffectType = 245
	E_FINISH_GARRISON_MISSION      SpellEffectType = 246
	E_ADD_GARRISON_MISSION_SET     SpellEffectType = 247
	E_FINISH_SHIPMENT              SpellEffectType = 248
	E_FORCE_EQUIP_ITEM             SpellEffectType = 249
	E_TAKE_SCREENSHOT              SpellEffectType = 250
	E_SET_GARRISON_CACHE_SIZE      SpellEffectType = 251
	E_TELEPORT_UNITS               SpellEffectType = 252
	E_GIVE_HONOR                   SpellEffectType = 253
	E_JUMP_CHARGE                  SpellEffectType = 254
	E_LEARN_TRANSMOG_SET           SpellEffectType = 255
	// E_256 SpellEffectType = 256
	// E_257 SpellEffectType = 257
	E_MODIFY_KEYSTONE               SpellEffectType = 258
	E_RESPEC_AZERITE_EMPOWERED_ITEM SpellEffectType = 259
	E_SUMMON_STABLED_PET            SpellEffectType = 260
	E_SCRAP_ITEM                    SpellEffectType = 261
	// E_262 SpellEffectType = 262
	E_REPAIR_ITEM                         SpellEffectType = 263
	E_REMOVE_GEM                          SpellEffectType = 264
	E_LEARN_AZERITE_ESSENCE_POWER         SpellEffectType = 265
	E_SET_ITEM_BONUS_LIST_GROUP_ENTRY     SpellEffectType = 266
	E_CREATE_PRIVATE_CONVERSATION         SpellEffectType = 267
	E_APPLY_MOUNT_EQUIPMENT               SpellEffectType = 268
	E_INCREASE_ITEM_BONUS_LIST_GROUP_STEP SpellEffectType = 269
	// E_270 SpellEffectType = 270
	E_APPLY_AREA_AURA_PARTY_NONRANDOM SpellEffectType = 271
	E_SET_COVENANT                    SpellEffectType = 272
	E_CRAFT_RUNEFORGE_LEGENDARY       SpellEffectType = 273
	// E_274 SpellEffectType = 274
	// E_275 SpellEffectType = 275
	E_LEARN_TRANSMOG_ILLUSION SpellEffectType = 276
	E_SET_CHROMIE_TIME        SpellEffectType = 277
	// E_278 SpellEffectType = 278
	E_LEARN_GARR_TALENT SpellEffectType = 279
	// E_280 SpellEffectType = 280
	E_LEARN_SOULBIND_CONDUIT           SpellEffectType = 281
	E_CONVERT_ITEMS_TO_CURRENCY        SpellEffectType = 282
	E_COMPLETE_CAMPAIGN                SpellEffectType = 283
	E_SEND_CHAT_MESSAGE                SpellEffectType = 284
	E_MODIFY_KEYSTONE_2                SpellEffectType = 285
	E_GRANT_BATTLEPET_EXPERIENCE       SpellEffectType = 286
	E_SET_GARRISON_FOLLOWER_LEVEL      SpellEffectType = 287
	E_CRAFT_ITEM                       SpellEffectType = 288
	E_MODIFY_AURA_STACKS               SpellEffectType = 289
	E_MODIFY_COOLDOWN                  SpellEffectType = 290
	E_MODIFY_COOLDOWNS                 SpellEffectType = 291
	E_MODIFY_COOLDOWNS_BY_CATEGORY     SpellEffectType = 292
	E_MODIFY_CHARGES                   SpellEffectType = 293
	E_CRAFT_LOOT                       SpellEffectType = 294
	E_SALVAGE_ITEM                     SpellEffectType = 295
	E_CRAFT_SALVAGE_ITEM               SpellEffectType = 296
	E_RECRAFT_ITEM                     SpellEffectType = 297
	E_CANCEL_ALL_PRIVATE_CONVERSATIONS SpellEffectType = 298
	// E_299 SpellEffectType = 299
	// E_300 SpellEffectType = 300
	E_CRAFT_ENCHANT                     SpellEffectType = 301
	E_GATHERING                         SpellEffectType = 302
	E_CREATE_TRAIT_TREE_CONFIG          SpellEffectType = 303
	E_CHANGE_ACTIVE_COMBAT_TRAIT_CONFIG SpellEffectType = 304
	// E_305 SpellEffectType = 305
	E_UPDATE_INTERACTIONS SpellEffectType = 306
	// E_307 SpellEffectType = 307
	E_CANCEL_PRELOAD_WORLD                                     SpellEffectType = 308
	E_PRELOAD_WORLD                                            SpellEffectType = 309
	E_310                                                      SpellEffectType = 310
	E_ENSURE_WORLD_LOADED                                      SpellEffectType = 311
	E_312                                                      SpellEffectType = 312
	E_CHANGE_ITEM_BONUSES_2                                    SpellEffectType = 313
	E_ADD_SOCKET_BONUS                                         SpellEffectType = 314
	E_LEARN_TRANSMOG_APPEARANCE_FROM_ITEM_MOD_APPEARANCE_GROUP SpellEffectType = 315
	E_KILL_CREDIT_LABEL_1                                      SpellEffectType = 316
	E_KILL_CREDIT_LABEL_2                                      SpellEffectType = 317
	// E_318 SpellEffectType = 318
	// E_319 SpellEffectType = 319
	// E_320 SpellEffectType = 320
	// E_321 SpellEffectType = 321
	// E_322 SpellEffectType = 322
	// E_323 SpellEffectType = 323
	// E_324 SpellEffectType = 324
	// E_325 SpellEffectType = 325
	// E_326 SpellEffectType = 326
	// E_327 SpellEffectType = 327
	E_328 SpellEffectType = 328
	E_329 SpellEffectType = 329
	// E_330 SpellEffectType = 330
	// E_331 SpellEffectType = 331
	// E_332 SpellEffectType = 332
	// E_333 SpellEffectType = 333
	// E_334 SpellEffectType = 334
	E_SET_PLAYER_DATA_ELEMENT_ACCOUNT   SpellEffectType = 335
	E_SET_PLAYER_DATA_ELEMENT_CHARACTER SpellEffectType = 336
	E_SET_PLAYER_DATA_FLAG_ACCOUNT      SpellEffectType = 337
	E_SET_PLAYER_DATA_FLAG_CHARACTER    SpellEffectType = 338
	E_UI_ACTION                         SpellEffectType = 339
	// E_340 SpellEffectType = 340
	E_LEARN_WARBAND_SCENE SpellEffectType = 341
	// E_342 SpellEffectType = 342
	// E_343 SpellEffectType = 343
	// E_344 SpellEffectType = 344
	E_ASSIST_ACTION SpellEffectType = 345
	// E_346 SpellEffectType = 346
	E_EQUIP_TRANSMOG_OUTFIT           SpellEffectType = 347
	E_GIVE_HOUSE_LEVEL                SpellEffectType = 348
	E_LEARN_HOUSING_INTERIOR          SpellEffectType = 349
	E_LEARN_HOUSING_EXTERIOR          SpellEffectType = 350
	E_LEARN_HOUSE_THEME               SpellEffectType = 351
	E_LEARN_HOUSING_COMPONENT_TEXTURE SpellEffectType = 352
	E_CREATE_AREA_TRIGGER_2           SpellEffectType = 353
	E_SET_NEIGHBORHOOD_INITIATIVE     SpellEffectType = 354
	// E_355 SpellEffectType = 355
	// E_356 SpellEffectType = 356
	E_APPLY_ITEM_BONUS  SpellEffectType = 357
	E_REMOVE_ITEM_BONUS SpellEffectType = 358
	E_359               SpellEffectType = 359
	E_360               SpellEffectType = 360
)
