// Code generated by gen_spelldata. DO NOT EDIT.

package dbcenums

const (
	FORM_CAT_FORM             ShapeshiftForm = 1
	FORM_TREE_FORM            ShapeshiftForm = 2
	FORM_TRAVEL_FORM          ShapeshiftForm = 3
	FORM_AQUATIC_FORM         ShapeshiftForm = 4
	FORM_BEAR_FORM            ShapeshiftForm = 5
	FORM_AMBIENT              ShapeshiftForm = 6
	FORM_GHOUL                ShapeshiftForm = 7
	FORM_DIRE_BEAR_FORM       ShapeshiftForm = 8
	FORM_GHOST_WOLF           ShapeshiftForm = 16
	FORM_BATTLE_STANCE        ShapeshiftForm = 17
	FORM_DEFENSIVE_STANCE     ShapeshiftForm = 18
	FORM_BERSERKER_STANCE     ShapeshiftForm = 19
	FORM_METAMORPHOSIS        ShapeshiftForm = 22
	FORM_SHADOWFORM           ShapeshiftForm = 28
	FORM_STEALTH              ShapeshiftForm = 30
	FORM_MOONKIN_FORM         ShapeshiftForm = 31
	FORM_SPIRIT_OF_REDEMPTION ShapeshiftForm = 32
)

// The forms whose SpellShapeshiftForm.Flags set bit 1.
const stanceForms uint64 = 0x68a70002
