package dbcenums

// ImplicitTarget_0/_1, under TrinityCore's Targets names. Every id is listed: one with no known name
// is TARGET_<id>, and one that is neither named nor read is commented out.
type ImplicitTarget uint8

const (
	TARGET_NONE                 ImplicitTarget = 0
	TARGET_UNIT_CASTER          ImplicitTarget = 1
	TARGET_UNIT_NEARBY_ENEMY    ImplicitTarget = 2
	TARGET_UNIT_NEARBY_ALLY     ImplicitTarget = 3
	TARGET_UNIT_NEARBY_PARTY    ImplicitTarget = 4
	TARGET_UNIT_PET             ImplicitTarget = 5
	TARGET_UNIT_TARGET_ENEMY    ImplicitTarget = 6
	TARGET_UNIT_SRC_AREA_ENTRY  ImplicitTarget = 7
	TARGET_UNIT_DEST_AREA_ENTRY ImplicitTarget = 8
	TARGET_DEST_HOME            ImplicitTarget = 9
	// TARGET_10 ImplicitTarget = 10
	TARGET_UNIT_SRC_AREA_UNK_11 ImplicitTarget = 11
	// TARGET_12 ImplicitTarget = 12
	// TARGET_13 ImplicitTarget = 13
	// TARGET_14 ImplicitTarget = 14
	TARGET_UNIT_SRC_AREA_ENEMY  ImplicitTarget = 15
	TARGET_UNIT_DEST_AREA_ENEMY ImplicitTarget = 16
	TARGET_DEST_DB              ImplicitTarget = 17
	TARGET_DEST_CASTER          ImplicitTarget = 18
	// TARGET_19 ImplicitTarget = 19
	TARGET_UNIT_CASTER_AREA_PARTY               ImplicitTarget = 20
	TARGET_UNIT_TARGET_ALLY                     ImplicitTarget = 21
	TARGET_SRC_CASTER                           ImplicitTarget = 22
	TARGET_GAMEOBJECT_TARGET                    ImplicitTarget = 23
	TARGET_UNIT_CONE_ENEMY_24                   ImplicitTarget = 24
	TARGET_UNIT_TARGET_ANY                      ImplicitTarget = 25
	TARGET_GAMEOBJECT_ITEM_TARGET               ImplicitTarget = 26
	TARGET_UNIT_MASTER                          ImplicitTarget = 27
	TARGET_DEST_DYNOBJ_ENEMY                    ImplicitTarget = 28
	TARGET_DEST_DYNOBJ_ALLY                     ImplicitTarget = 29
	TARGET_UNIT_SRC_AREA_ALLY                   ImplicitTarget = 30
	TARGET_UNIT_DEST_AREA_ALLY                  ImplicitTarget = 31
	TARGET_DEST_CASTER_SUMMON                   ImplicitTarget = 32
	TARGET_UNIT_SRC_AREA_PARTY                  ImplicitTarget = 33
	TARGET_UNIT_DEST_AREA_PARTY                 ImplicitTarget = 34
	TARGET_UNIT_TARGET_PARTY                    ImplicitTarget = 35
	TARGET_DEST_CASTER_UNK_36                   ImplicitTarget = 36
	TARGET_UNIT_LASTTARGET_AREA_PARTY           ImplicitTarget = 37
	TARGET_UNIT_NEARBY_ENTRY                    ImplicitTarget = 38
	TARGET_DEST_CASTER_FISHING                  ImplicitTarget = 39
	TARGET_GAMEOBJECT_NEARBY_ENTRY              ImplicitTarget = 40
	TARGET_DEST_CASTER_FRONT_RIGHT              ImplicitTarget = 41
	TARGET_DEST_CASTER_BACK_RIGHT               ImplicitTarget = 42
	TARGET_DEST_CASTER_BACK_LEFT                ImplicitTarget = 43
	TARGET_DEST_CASTER_FRONT_LEFT               ImplicitTarget = 44
	TARGET_UNIT_TARGET_CHAINHEAL_ALLY           ImplicitTarget = 45
	TARGET_DEST_NEARBY_ENTRY                    ImplicitTarget = 46
	TARGET_DEST_CASTER_FRONT                    ImplicitTarget = 47
	TARGET_DEST_CASTER_BACK                     ImplicitTarget = 48
	TARGET_DEST_CASTER_RIGHT                    ImplicitTarget = 49
	TARGET_DEST_CASTER_LEFT                     ImplicitTarget = 50
	TARGET_GAMEOBJECT_SRC_AREA                  ImplicitTarget = 51
	TARGET_GAMEOBJECT_DEST_AREA                 ImplicitTarget = 52
	TARGET_DEST_TARGET_ENEMY                    ImplicitTarget = 53
	TARGET_UNIT_CONE_180_DEG_ENEMY              ImplicitTarget = 54
	TARGET_DEST_CASTER_FRONT_LEAP               ImplicitTarget = 55
	TARGET_UNIT_CASTER_AREA_RAID                ImplicitTarget = 56
	TARGET_UNIT_TARGET_RAID                     ImplicitTarget = 57
	TARGET_UNIT_NEARBY_RAID                     ImplicitTarget = 58
	TARGET_UNIT_CONE_ALLY                       ImplicitTarget = 59
	TARGET_UNIT_CONE_ENTRY                      ImplicitTarget = 60
	TARGET_UNIT_TARGET_AREA_RAID_CLASS          ImplicitTarget = 61
	TARGET_DEST_CASTER_GROUND                   ImplicitTarget = 62
	TARGET_DEST_TARGET_ANY                      ImplicitTarget = 63
	TARGET_DEST_TARGET_FRONT                    ImplicitTarget = 64
	TARGET_DEST_TARGET_BACK                     ImplicitTarget = 65
	TARGET_DEST_TARGET_RIGHT                    ImplicitTarget = 66
	TARGET_DEST_TARGET_LEFT                     ImplicitTarget = 67
	TARGET_DEST_TARGET_FRONT_RIGHT              ImplicitTarget = 68
	TARGET_DEST_TARGET_BACK_RIGHT               ImplicitTarget = 69
	TARGET_DEST_TARGET_BACK_LEFT                ImplicitTarget = 70
	TARGET_DEST_TARGET_FRONT_LEFT               ImplicitTarget = 71
	TARGET_DEST_CASTER_RANDOM                   ImplicitTarget = 72
	TARGET_DEST_CASTER_RADIUS                   ImplicitTarget = 73
	TARGET_DEST_TARGET_RANDOM                   ImplicitTarget = 74
	TARGET_DEST_TARGET_RADIUS                   ImplicitTarget = 75
	TARGET_DEST_CHANNEL_TARGET                  ImplicitTarget = 76
	TARGET_UNIT_CHANNEL_TARGET                  ImplicitTarget = 77
	TARGET_DEST_DEST_FRONT                      ImplicitTarget = 78
	TARGET_DEST_DEST_BACK                       ImplicitTarget = 79
	TARGET_DEST_DEST_RIGHT                      ImplicitTarget = 80
	TARGET_DEST_DEST_LEFT                       ImplicitTarget = 81
	TARGET_DEST_DEST_FRONT_RIGHT                ImplicitTarget = 82
	TARGET_DEST_DEST_BACK_RIGHT                 ImplicitTarget = 83
	TARGET_DEST_DEST_BACK_LEFT                  ImplicitTarget = 84
	TARGET_DEST_DEST_FRONT_LEFT                 ImplicitTarget = 85
	TARGET_DEST_DEST_RANDOM                     ImplicitTarget = 86
	TARGET_DEST_DEST                            ImplicitTarget = 87
	TARGET_DEST_DYNOBJ_NONE                     ImplicitTarget = 88
	TARGET_DEST_TRAJ                            ImplicitTarget = 89
	TARGET_UNIT_TARGET_MINIPET                  ImplicitTarget = 90
	TARGET_DEST_DEST_RADIUS                     ImplicitTarget = 91
	TARGET_UNIT_SUMMONER                        ImplicitTarget = 92
	TARGET_CORPSE_SRC_AREA_ENEMY                ImplicitTarget = 93
	TARGET_UNIT_VEHICLE                         ImplicitTarget = 94
	TARGET_UNIT_TARGET_PASSENGER                ImplicitTarget = 95
	TARGET_UNIT_PASSENGER_0                     ImplicitTarget = 96
	TARGET_UNIT_PASSENGER_1                     ImplicitTarget = 97
	TARGET_UNIT_PASSENGER_2                     ImplicitTarget = 98
	TARGET_UNIT_PASSENGER_3                     ImplicitTarget = 99
	TARGET_UNIT_PASSENGER_4                     ImplicitTarget = 100
	TARGET_UNIT_PASSENGER_5                     ImplicitTarget = 101
	TARGET_UNIT_PASSENGER_6                     ImplicitTarget = 102
	TARGET_UNIT_PASSENGER_7                     ImplicitTarget = 103
	TARGET_UNIT_CONE_CASTER_TO_DEST_ENEMY       ImplicitTarget = 104
	TARGET_UNIT_CASTER_AND_PASSENGERS           ImplicitTarget = 105
	TARGET_DEST_NEARBY_DB                       ImplicitTarget = 106
	TARGET_DEST_NEARBY_ENTRY_2                  ImplicitTarget = 107
	TARGET_GAMEOBJECT_CONE_CASTER_TO_DEST_ENEMY ImplicitTarget = 108
	TARGET_GAMEOBJECT_CONE_CASTER_TO_DEST_ALLY  ImplicitTarget = 109
	TARGET_UNIT_CONE_CASTER_TO_DEST_ENTRY       ImplicitTarget = 110
	// TARGET_UNK_111 ImplicitTarget = 111
	// TARGET_UNK_112 ImplicitTarget = 112
	// TARGET_UNK_113 ImplicitTarget = 113
	// TARGET_UNK_114 ImplicitTarget = 114
	TARGET_UNIT_SRC_AREA_FURTHEST_ENEMY ImplicitTarget = 115
	TARGET_UNIT_AND_DEST_LAST_ENEMY     ImplicitTarget = 116
	// TARGET_UNK_117 ImplicitTarget = 117
	TARGET_UNIT_TARGET_ALLY_OR_RAID         ImplicitTarget = 118
	TARGET_CORPSE_SRC_AREA_RAID             ImplicitTarget = 119
	TARGET_UNIT_CASTER_AND_SUMMONS          ImplicitTarget = 120
	TARGET_CORPSE_TARGET_ALLY               ImplicitTarget = 121
	TARGET_UNIT_AREA_THREAT_LIST            ImplicitTarget = 122
	TARGET_UNIT_AREA_TAP_LIST               ImplicitTarget = 123
	TARGET_UNIT_TARGET_TAP_LIST             ImplicitTarget = 124
	TARGET_DEST_CASTER_GROUND_2             ImplicitTarget = 125
	TARGET_UNIT_CASTER_AREA_ENEMY_CLUMP     ImplicitTarget = 126
	TARGET_DEST_CASTER_ENEMY_CLUMP_CENTROID ImplicitTarget = 127
	TARGET_UNIT_RECT_CASTER_ALLY            ImplicitTarget = 128
	TARGET_UNIT_RECT_CASTER_ENEMY           ImplicitTarget = 129
	TARGET_UNIT_RECT_CASTER                 ImplicitTarget = 130
	TARGET_DEST_SUMMONER                    ImplicitTarget = 131
	TARGET_DEST_TARGET_ALLY                 ImplicitTarget = 132
	TARGET_UNIT_LINE_CASTER_TO_DEST_ALLY    ImplicitTarget = 133
	TARGET_UNIT_LINE_CASTER_TO_DEST_ENEMY   ImplicitTarget = 134
	TARGET_UNIT_LINE_CASTER_TO_DEST         ImplicitTarget = 135
	TARGET_UNIT_CONE_CASTER_TO_DEST_ALLY    ImplicitTarget = 136
	TARGET_DEST_CASTER_MOVEMENT_DIRECTION   ImplicitTarget = 137
	TARGET_DEST_DEST_GROUND                 ImplicitTarget = 138
	// TARGET_UNK_139 ImplicitTarget = 139
	TARGET_DEST_CASTER_CLUMP_CENTROID ImplicitTarget = 140
	// TARGET_UNK_141 ImplicitTarget = 141
	TARGET_DEST_NEARBY_ENTRY_OR_DB ImplicitTarget = 142
	// TARGET_UNK_143 ImplicitTarget = 143
	// TARGET_UNK_144 ImplicitTarget = 144
	// TARGET_UNK_145 ImplicitTarget = 145
	// TARGET_UNK_146 ImplicitTarget = 146
	// TARGET_UNK_147 ImplicitTarget = 147
	TARGET_DEST_DEST_TARGET_TOWARDS_CASTER ImplicitTarget = 148
	// TARGET_UNK_149 ImplicitTarget = 149
	TARGET_UNIT_OWN_CRITTER ImplicitTarget = 150
	TARGET_UNK_151          ImplicitTarget = 151
	// TARGET_UNK_152 ImplicitTarget = 152
	// TARGET_153 ImplicitTarget = 153
)
