// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
//
// Do not edit. These mirror sim/core, and a Go test fails if they drift:
// TestMechanicsConstantsMatchTheUI in sim/core/mechanics_mirror_test.go.
// **************************************

export const CHARACTER_LEVEL = 60;
export const BOSS_LEVEL = CHARACTER_LEVEL + 3;

export const EXPERTISE_RATING_PER_EXPERTISE_PERCENT = 10;
export const PHYSICAL_HASTE_RATING_PER_HASTE_PERCENT = 10;
export const SPELL_HASTE_RATING_PER_HASTE_PERCENT = 10;
export const SPELL_CRIT_RATING_PER_CRIT_PERCENT = 14;
export const PHYSICAL_CRIT_RATING_PER_CRIT_PERCENT = 14;
export const SPELL_HIT_RATING_PER_HIT_PERCENT = 10;
export const PHYSICAL_HIT_RATING_PER_HIT_PERCENT = 10;
export const DODGE_RATING_PER_DODGE_PERCENT = 12;
export const PARRY_RATING_PER_PARRY_PERCENT = 15;
export const DEFENSE_RATING_PER_DEFENSE_LEVEL = 1;
export const BLOCK_RATING_PER_BLOCK_PERCENT = 5;

export const MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE = 0.04;
