syntax = "proto3";
package proto;

option go_package = "./proto";
// DO NOT REMOVE THE COMMENTS
// BEGIN GENERATED
// PaladinTalents message.
message PaladinTalents {
    // Holy
    int32 divine_strength = 1;
    int32 divine_intellect = 2;
    int32 healing_light = 3;
    int32 spiritual_focus = 4;
    int32 improved_seals = 5;
    int32 unyielding_faith = 6;
    bool voice_of_truth = 7;
    int32 reverence = 8;
    int32 purifying_power = 9;
    int32 infusion_of_light = 10;
    int32 illumination = 11;
    bool divine_favor = 12;
    int32 divine_precision = 13;
    bool holy_shock = 14;
    int32 consecrated_ground = 15;
    int32 holy_power = 16;
    bool lights_vigil = 17;
    // Protection
    int32 toughness = 18;
    int32 redoubt = 19;
    int32 precision = 20;
    int32 guardians_favor = 21;
    int32 anticipation = 22;
    bool improved_seal_of_fury = 23;
    int32 improved_righteous_fury = 24;
    int32 shield_specialization = 25;
    int32 sacred_duty = 26;
    bool swift_judgement = 27;
    int32 one_handed_weapon_specialization = 28;
    int32 improved_hammer_of_justice = 29;
    bool templars_bulwark = 30;
    int32 reckoning = 31;
    int32 iron_creed = 32;
    bool holy_shield = 33;
    // Retribution
    int32 deflection = 34;
    int32 benediction = 35;
    int32 improved_judgement = 36;
    int32 holy_conduit = 37;
    int32 conviction = 38;
    int32 vindication = 39;
    int32 sanctified_judgement = 40;
    bool seal_of_command = 41;
    int32 pursuit_of_justice = 42;
    int32 eye_for_an_eye = 43;
    bool sacred_arbiter = 44;
    int32 two_handed_weapon_specialization = 45;
    int32 vengeance = 46;
    bool repentance = 47;
    int32 champion_of_the_light = 48;
    int32 instrument_of_law = 49;
    bool twist_of_light = 50;
}

// END GENERATED

enum PaladinJudgement {
	JudgementNone = 0;
	JudgementOfLight = 1;
	JudgementOfWisdom = 2;
}

enum PaladinAura {
	AuraNone = 0;
	DevotionAura = 1;
	RetributionAura = 2;
	ConcentrationAura = 3;
	FireResistanceAura = 4;
	FrostResistanceAura = 5;
	ShadowResistanceAura = 6;
}

message PaladinOptions {
}

message RetributionPaladin {
	message Rotation {
		bool useExorcism = 1;
		int32 consecrationRank = 2;
		int32 delayMajorCDs = 3;
		bool prepullSotC = 4;
		PaladinAura aura = 5;
	}

	message Options {
		PaladinOptions class_options = 1;
	}
	Options options = 3;
}

message ProtectionPaladin {
	message Rotation {
		bool prioritizeHolyShield = 1;
		int32 consecrationRank = 2;
		bool useExorcism = 3;
		PaladinJudgement maintainJudgement = 5;
		PaladinAura aura = 6;
		bool useHammerOfWrath = 8;
	}

	message Options {
		PaladinOptions class_options = 1;
	}
	Options options = 3;
}

message HolyPaladin {
	message Rotation {}

	message Options {
		PaladinOptions class_options = 2;
	}
	Options options = 3;
}
