// Code generated by tools/database/gen_spelldata. DO NOT EDIT.
//
// The aura and effect names the generated spell data tables reference, mirrored from
// sim/core/dbcenums. Only the values the tables use are emitted, and every name is the one
// dbcenums declares, so a name here cannot drift from the one the extractor reads.

package shared

// What the effect does - E_SCHOOL_DAMAGE, E_APPLY_AURA.
const (
	E_NONE                  SpellDataEffectKind = 0
	E_INSTAKILL             SpellDataEffectKind = 1
	E_SCHOOL_DAMAGE         SpellDataEffectKind = 2
	E_DUMMY                 SpellDataEffectKind = 3
	E_APPLY_AURA            SpellDataEffectKind = 6
	E_HEAL                  SpellDataEffectKind = 10
	E_ADD_EXTRA_ATTACKS     SpellDataEffectKind = 19
	E_ENERGIZE              SpellDataEffectKind = 30
	E_WEAPON_PERCENT_DAMAGE SpellDataEffectKind = 31
	E_APPLY_AREA_AURA_PARTY SpellDataEffectKind = 35
	E_DISPEL                SpellDataEffectKind = 38
	E_TRIGGER_SPELL         SpellDataEffectKind = 64
	E_APPLY_AREA_AURA_RAID  SpellDataEffectKind = 65
	E_HEAL_MAX_HEALTH       SpellDataEffectKind = 67
	E_SCRIPT_EFFECT         SpellDataEffectKind = 77
	E_SANCTUARY             SpellDataEffectKind = 79
	E_ATTACK_ME             SpellDataEffectKind = 114
	E_NORMALIZED_WEAPON_DMG SpellDataEffectKind = 121
	E_ENERGIZE_PCT          SpellDataEffectKind = 137
	E_UPDATE_PLAYER_PHASE   SpellDataEffectKind = 167
	E_CREATE_AREATRIGGER    SpellDataEffectKind = 179
	E_329                   SpellDataEffectKind = 329
)

// Which aura it applies, when the effect is E_APPLY_AURA.
const (
	A_NONE                              SpellDataAura = 0
	A_DUMMY                             SpellDataAura = 4
	A_MOD_FEAR                          SpellDataAura = 7
	A_MOD_ATTACKSPEED                   SpellDataAura = 9
	A_MOD_THREAT                        SpellDataAura = 10
	A_MOD_TAUNT                         SpellDataAura = 11
	A_MOD_STUN                          SpellDataAura = 12
	A_MOD_DAMAGE_TAKEN                  SpellDataAura = 14
	A_DAMAGE_SHIELD                     SpellDataAura = 15
	A_MOD_RESISTANCE                    SpellDataAura = 22
	A_PERIODIC_ENERGIZE                 SpellDataAura = 24
	A_MOD_PACIFY                        SpellDataAura = 25
	A_MOD_SKILL                         SpellDataAura = 30
	A_MOD_INCREASE_SPEED                SpellDataAura = 31
	A_SCHOOL_IMMUNITY                   SpellDataAura = 39
	A_PROC_TRIGGER_SPELL                SpellDataAura = 42
	A_PROC_TRIGGER_DAMAGE               SpellDataAura = 43
	A_TRACK_CREATURES                   SpellDataAura = 44
	A_MOD_PARRY_PERCENT                 SpellDataAura = 47
	A_MOD_BLOCK_PERCENT                 SpellDataAura = 51
	A_MOD_WEAPON_CRIT_PERCENT           SpellDataAura = 52
	A_MOD_HIT_CHANCE                    SpellDataAura = 54
	A_MOD_SPELL_HIT_CHANCE              SpellDataAura = 55
	A_SCHOOL_ABSORB                     SpellDataAura = 69
	A_MECHANIC_IMMUNITY                 SpellDataAura = 77
	A_MOD_DAMAGE_PERCENT_DONE           SpellDataAura = 79
	A_MOD_DAMAGE_PERCENT_TAKEN          SpellDataAura = 87
	A_PREVENTS_FLEEING                  SpellDataAura = 92
	A_MOD_UNATTACKABLE                  SpellDataAura = 93
	A_MOD_ATTACK_POWER                  SpellDataAura = 99
	A_ADD_FLAT_MODIFIER                 SpellDataAura = 107
	A_ADD_PCT_MODIFIER                  SpellDataAura = 108
	A_MOD_HEALING_PCT                   SpellDataAura = 118
	A_MOD_RANGED_ATTACK_POWER           SpellDataAura = 124
	A_MOD_MANA_REGEN_INTERRUPT          SpellDataAura = 134
	A_MOD_TOTAL_STAT_PERCENTAGE         SpellDataAura = 137
	A_MOD_BASE_RESISTANCE_PCT           SpellDataAura = 142
	A_REDUCE_PUSHBACK                   SpellDataAura = 149
	A_MOD_MOUNTED_SPEED_NOT_STACK       SpellDataAura = 172
	A_MOD_SPELL_DAMAGE_OF_STAT_PERCENT  SpellDataAura = 174
	A_MOD_SPELL_HEALING_OF_STAT_PERCENT SpellDataAura = 175
	A_PERIODIC_DUMMY                    SpellDataAura = 226
	A_PROC_TRIGGER_SPELL_WITH_VALUE     SpellDataAura = 231
	A_MECHANIC_DURATION_MOD             SpellDataAura = 232
	A_MOD_BLOCK_VALUE_PCT               SpellDataAura = 272
	A_OVERRIDE_ACTIONBAR_SPELLS         SpellDataAura = 332
	A_MOD_BONUS_ARMOR_PCT               SpellDataAura = 466
	A_SPLIT_DAMAGE_FLAT                 SpellDataAura = 562
)
