#!/usr/bin/python

import csv
import os
import re
import sqlite3

# Generates sim/core/base_stats_auto_gen.go from the extracted client data.
#
# Two sources, both produced by `make db` from the Forever beta client:
#
#   tools/database/wowsims.db     PlayerExpectedStat -- base mana and the
#                                 crit-per-agility / crit-per-intellect slopes
#   assets/db_inputs/basestats/   the CombatRatings gametable, plus the two
#                                 base-crit tables described below
#
# The per-level crit slope tables (chancetomeleecrit / chancetospellcrit) and
# octbasempbyclass used to supply the first three quantities, but the beta
# client does not ship those gametables -- PlayerExpectedStat replaced them,
# and it disagrees: Forever retuned crit-per-agility for seven of the nine
# classes (hunter 0.0189 where the old tables said 0.0301).

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/basestats/"
OUTPUT_PATH = "sim/core/"
TS_OUTPUT_PATH = "ui/sim/constants/mechanics.ts"
CONSTANTS_PATH = "sim/core/constants.go"
DB_PATH = "tools/database/wowsims.db"

# The beta does not ship the two base-crit gametables either, so these stay
# checked in by hand. Their values are the flat per-class crit a character has
# before any agility/intellect contribution, and nothing here can confirm them
# for Forever. What is known: they are unchanged from the TBC sim, the MoP-era
# extraction they came from carries them verbatim, and the placeholder 0.2 in
# its Death Knight and Monk columns shows that table was inherited rather than
# refitted. wowsims' vanilla sim independently carries per-class base crit in
# the same range -- its spell column agrees within about a tenth of a percent
# for most classes (hunter 3.6 against 3.602, warlock 1.7 exactly), though its
# melee column differs, notably a 0 where this table has warrior 1.14.
MELEE_CRIT_BASE = "chancetomeleecritbase.txt"
SPELL_CRIT_BASE = "chancetospellcritbase.txt"
COMBAT_RATINGS = "combatratings.txt"

# Read out of sim/core/constants.go rather than repeated here, so there is one place
# that says what level this sim runs at.
def GoConstant(name: str):
    text = open(BASE_DIR + CONSTANTS_PATH).read()
    return float(re.search(rf"^const {name} = ([\d.]+)$", text, re.M).group(1))


BASE_LEVEL = int(GoConstant("CharacterLevel"))

# The boss is three levels above the player; see defaultRaidBossLevel in sim/core/target.go.
BOSS_LEVEL_OFFSET = 3

# ChrClasses.ID -> the proto.Class suffix. Hardcoded rather than read from the
# client so the generated identifiers cannot silently follow a renumbering.
CLASS_IDS = {
    1: "Warrior",
    2: "Paladin",
    3: "Hunter",
    4: "Rogue",
    5: "Priest",
    7: "Shaman",
    8: "Mage",
    9: "Warlock",
    11: "Druid",
}

CLASSES = ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Shaman", "Mage", "Warlock", "Druid"]


# Returns {row key: {column name: value}}. Indexing by header name rather than
# by position survives the column order changes the client makes between
# expansions -- the beta's SpellScaling grew Evoker/Adventurer/Traveler columns.
def GenNameIndexedDb(file: str):
    db = {}
    with open(file) as tsv:
        rows = list(csv.reader(tsv, delimiter="\t"))
    header = rows[0]
    for row in rows[1:]:
        db[row[0]] = dict(zip(header[1:], row[1:]))
    return db


def GenExpectedStats(dbPath: str, level: int):
    conn = sqlite3.connect(dbPath)
    rows = conn.execute(
        """SELECT ClassID, BaseMana, CritPerAgility, SpellCritPerIntellect
           FROM PlayerExpectedStat WHERE Level = ? AND ContentSetID = 0""",
        (level,),
    ).fetchall()
    conn.close()

    stats = {}
    for classID, baseMana, critPerAgi, critPerInt in rows:
        if classID not in CLASS_IDS:
            continue
        stats[CLASS_IDS[classID]] = {
            "Mana": baseMana,
            # The client stores these as a fraction per point (0.0005 = one
            # percent per 20 agility); the sim's stat dependencies are in
            # percent per point.
            "CritPerAgi": critPerAgi * 100,
            "CritPerInt": critPerInt * 100,
        }

    missing = [c for c in CLASSES if c not in stats]
    if missing:
        raise SystemExit(f"PlayerExpectedStat has no level {level} row for: {', '.join(missing)}")
    return stats


class ClassStats:
    Expected: dict
    MCritBase: dict
    SCritBase: dict
    CombatRatings: dict


def GenExtraStatsGoFile(cs: ClassStats):
    header = '''
package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
    "github.com/wowsims/forever/sim/core/proto"
    "github.com/wowsims/forever/sim/core/stats"
)

'''
    output = header
    ratings = cs.CombatRatings[str(BASE_LEVEL)]

    # Rating per whole percent, like the hit and crit constants below. ExpertiseRating feeds
    # ExpertisePercent through a stat dependency; there is no quarter-point rounding in Forever.
    output += f"const ExpertiseRatingPerExpertisePercent = {float(ratings['Expertise']):f}\n"
    output += f"const DefenseRatingPerDefenseLevel = {float(ratings['Defense Skill']):f}\n"
    output += f"const DodgeRatingPerDodgePercent = {float(ratings['Dodge']):f}\n"
    output += f"const ParryRatingPerParryPercent = {float(ratings['Parry']):f}\n"
    output += f"const BlockRatingPerBlockPercent = {float(ratings['Block']):f}\n"
    output += f"const PhysicalHitRatingPerHitPercent = {float(ratings['Hit - Melee']):f}\n"
    output += f"const SpellHitRatingPerHitPercent = {float(ratings['Hit - Spell']):f}\n"
    output += f"const PhysicalCritRatingPerCritPercent = {float(ratings['Crit - Melee']):f}\n"
    output += f"const SpellCritRatingPerCritPercent = {float(ratings['Crit - Spell']):f}\n"
    output += f"const PhysicalHasteRatingPerHastePercent = {float(ratings['Haste - Melee']):f}\n"
    output += f"const SpellHasteRatingPerHastePercent = {float(ratings['Haste - Spell']):f}\n"

    output += '''var CritPerAgiMaxLevel = map[proto.Class]float64{
proto.Class_ClassUnknown: 0.0,'''
    for c in CLASSES:
        output += f"\nproto.Class_Class{c}: {cs.Expected[c]['CritPerAgi']:.8f},"
    output += "\n}\n"

    output += '''var CritPerIntMaxLevel = map[proto.Class]float64{
proto.Class_ClassUnknown: 0.0,'''
    for c in CLASSES:
        output += f"\nproto.Class_Class{c}: {cs.Expected[c]['CritPerInt']:.8f},"
    output += "\n}\n"

    output += '''var ExtraClassBaseStats = map[proto.Class]stats.Stats{
proto.Class_ClassUnknown: {},'''
    for c in CLASSES:
        output += f"\nproto.Class_Class{c}: {{"
        output += f"\n stats.Mana: {float(cs.Expected[c]['Mana']):.4f},"
        output += f"\n stats.SpellCritPercent: {float(cs.SCritBase['1'][c]) * 100:.4f},"
        output += f"\n stats.PhysicalCritPercent: {float(cs.MCritBase['1'][c]) * 100:.4f},"
        output += "\n},"
    output += "\n}\n"
    return output


# ui/sim/constants/mechanics.ts used to be a hand-kept copy of these numbers, and it drifted:
# it was still converting spell hit at 8 and defense at 1.5 after the client moved both. It is
# generated from the same values as the Go file now, so the two cannot disagree.
def GenMechanicsTsFile(cs: ClassStats):
    ratings = cs.CombatRatings[str(BASE_LEVEL)]

    def num(value):
        return f"{float(value):g}"

    lines = [
        "// **************************************",
        "// AUTO GENERATED BY BASE_STATS_PARSER.PY",
        "//",
        "// Do not edit. These mirror sim/core, and a Go test fails if they drift:",
        "// TestMechanicsConstantsMatchTheUI in sim/core/mechanics_mirror_test.go.",
        "// **************************************",
        "",
        f"export const CHARACTER_LEVEL = {BASE_LEVEL};",
        f"export const BOSS_LEVEL = CHARACTER_LEVEL + {BOSS_LEVEL_OFFSET};",
        "",
        f"export const EXPERTISE_RATING_PER_EXPERTISE_PERCENT = {num(ratings['Expertise'])};",
        f"export const PHYSICAL_HASTE_RATING_PER_HASTE_PERCENT = {num(ratings['Haste - Melee'])};",
        f"export const SPELL_HASTE_RATING_PER_HASTE_PERCENT = {num(ratings['Haste - Spell'])};",
        f"export const SPELL_CRIT_RATING_PER_CRIT_PERCENT = {num(ratings['Crit - Spell'])};",
        f"export const PHYSICAL_CRIT_RATING_PER_CRIT_PERCENT = {num(ratings['Crit - Melee'])};",
        f"export const SPELL_HIT_RATING_PER_HIT_PERCENT = {num(ratings['Hit - Spell'])};",
        f"export const PHYSICAL_HIT_RATING_PER_HIT_PERCENT = {num(ratings['Hit - Melee'])};",
        f"export const DODGE_RATING_PER_DODGE_PERCENT = {num(ratings['Dodge'])};",
        f"export const PARRY_RATING_PER_PARRY_PERCENT = {num(ratings['Parry'])};",
        f"export const DEFENSE_RATING_PER_DEFENSE_LEVEL = {num(ratings['Defense Skill'])};",
        f"export const BLOCK_RATING_PER_BLOCK_PERCENT = {num(ratings['Block'])};",
        "",
        f"export const MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE = {num(GoConstant('MissDodgeParryBlockCritChancePerDefense'))};",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    args = ClassStats()
    args.Expected = GenExpectedStats(BASE_DIR + DB_PATH, BASE_LEVEL)
    args.MCritBase = GenNameIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT_BASE)
    args.SCritBase = GenNameIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT_BASE)
    args.CombatRatings = GenNameIndexedDb(BASE_DIR + DIR_PATH + COMBAT_RATINGS)

    output = GenExtraStatsGoFile(args)
    fname = BASE_DIR + OUTPUT_PATH + "base_stats_auto_gen.go"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
    os.system(f"gofmt -w {fname}")

    tsname = BASE_DIR + TS_OUTPUT_PATH
    print(f"Writing mechanics to: {tsname}")
    with open(tsname, "w") as tsfile:
        tsfile.write(GenMechanicsTsFile(args))
