// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package priest

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Blessed Recovery: effect 1 of spell 27811 has no rank curve and is held at its base points
//   Early Demise: effect 1 of spell 1310076 has no rank curve and is held at its base points
//   Improved Mind Flay: effect 3 of spell 1225139 has no rank curve and is held at its base points
//   Soul Warding: effect 0, 1 of spell 402000 has no rank curve and is held at its base points

type generatedSpellData struct {
	AbolishDisease              spelldata.Ladder
	AbolishDiseaseTriggered     spelldata.Ladder
	BindingHeal                 spelldata.Ladder
	Blackout                    spelldata.Ladder
	BlackoutTriggered           spelldata.Ladder
	BlessedRecovery             spelldata.Ladder
	BlessedRecoveryTriggered    spelldata.Ladder
	Chastise                    spelldata.Ladder
	ConfoundingFlash            spelldata.Ladder
	ContingencyPlan             spelldata.Ladder
	ContingencyPlanTriggered    spelldata.Ladder
	CureDisease                 spelldata.Ladder
	DarkSacrifice               spelldata.Ladder
	Darkness                    spelldata.Ladder
	DesperatePrayer             spelldata.Ladder
	DevouringContagion          spelldata.Ladder
	DevouringPlague             spelldata.Ladder
	DispelMagic                 spelldata.Ladder
	DivineAegis                 spelldata.Ladder
	DivineAegisTriggered        spelldata.Ladder
	DivineFury                  spelldata.Ladder
	DivineGrace                 spelldata.Ladder
	DivineSpirit                spelldata.Ladder
	EarlyDemise                 spelldata.Ladder
	ElunesGrace                 spelldata.Ladder
	Fade                        spelldata.Ladder
	FearWard                    spelldata.Ladder
	Feedback                    spelldata.Ladder
	FeedbackTriggered           spelldata.Ladder
	FlashHeal                   spelldata.Ladder
	FocusedCasting              spelldata.Ladder
	ForceOfWill                 spelldata.Ladder
	GreaterHeal                 spelldata.Ladder
	Heal                        spelldata.Ladder
	HexOfWeakness               spelldata.Ladder
	HolyFire                    spelldata.Ladder
	HolyNova                    spelldata.Ladder
	HolyNovaTriggered           spelldata.Ladder
	HolyPrecision               spelldata.Ladder
	HolyReach                   spelldata.Ladder
	HolySpecialization          spelldata.Ladder
	ImprovedFade                spelldata.Ladder
	ImprovedHealing             spelldata.Ladder
	ImprovedInnerFire           spelldata.Ladder
	ImprovedManaBurn            spelldata.Ladder
	ImprovedMindBlast           spelldata.Ladder
	ImprovedMindFlay            spelldata.Ladder
	ImprovedPowerWordFortitude  spelldata.Ladder
	ImprovedPowerWordShield     spelldata.Ladder
	ImprovedPsychicScream       spelldata.Ladder
	ImprovedRenew               spelldata.Ladder
	ImprovedShadowWordPain      spelldata.Ladder
	IncreasedFortitude          spelldata.Ladder
	InnerFire                   spelldata.Ladder
	InnerFocus                  spelldata.Ladder
	Inspiration                 spelldata.Ladder
	InspirationTriggered        spelldata.Ladder
	LesserHeal                  spelldata.Ladder
	Levitate                    spelldata.Ladder
	Lightwell                   spelldata.Ladder
	LightwellTriggered          spelldata.Ladder
	LightwellRenew              spelldata.Ladder
	LitanyOfLight               spelldata.Ladder
	ManaBurn                    spelldata.Ladder
	Martyrdom                   spelldata.Ladder
	MartyrdomTriggered          spelldata.Ladder
	Meditation                  spelldata.Ladder
	MentalAgility               spelldata.Ladder
	MentalStrength              spelldata.Ladder
	MindBlast                   spelldata.Ladder
	MindControl                 spelldata.Ladder
	MindFlay                    spelldata.Ladder
	MindSoothe                  spelldata.Ladder
	MindVision                  spelldata.Ladder
	Penance                     spelldata.Ladder
	PenanceTriggered            spelldata.Ladder
	PowerInfusion               spelldata.Ladder
	PowerWordFortitude          spelldata.Ladder
	PowerWordShield             spelldata.Ladder
	PowerWordShieldTriggered    spelldata.Ladder
	PowerInLight                spelldata.Ladder
	PrayerOfFortitude           spelldata.Ladder
	PrayerOfHealing             spelldata.Ladder
	PrayerOfMending             spelldata.Ladder
	PrayerOfMendingTriggered    spelldata.Ladder
	PrayerOfShadowProtection    spelldata.Ladder
	PrayerOfSpirit              spelldata.Ladder
	PsychicScream               spelldata.Ladder
	Renew                       spelldata.Ladder
	RenewedHope                 spelldata.Ladder
	Resurrection                spelldata.Ladder
	SearingLight                spelldata.Ladder
	SearingLightTriggered       spelldata.Ladder
	ShackleUndead               spelldata.Ladder
	ShadowAffinity              spelldata.Ladder
	ShadowFocus                 spelldata.Ladder
	ShadowProtection            spelldata.Ladder
	ShadowReach                 spelldata.Ladder
	ShadowWeaving               spelldata.Ladder
	ShadowWeavingTriggered      spelldata.Ladder
	ShadowWordDeath             spelldata.Ladder
	ShadowWordPain              spelldata.Ladder
	Shadowfiend                 spelldata.Ladder
	ShadowfiendTriggered        spelldata.Ladder
	Shadowform                  spelldata.Ladder
	Shadowguard                 spelldata.Ladder
	ShadowguardTriggered        spelldata.Ladder
	Silence                     spelldata.Ladder
	SilenceTriggered            spelldata.Ladder
	SilentResolve               spelldata.Ladder
	Smite                       spelldata.Ladder
	SoulWarding                 spelldata.Ladder
	SpellWarding                spelldata.Ladder
	SpiritTap                   spelldata.Ladder
	SpiritTapTriggered          spelldata.Ladder
	SpiritOfRedemption          spelldata.Ladder
	SpiritOfRedemptionTriggered spelldata.Ladder
	SpiritualGuidance           spelldata.Ladder
	SpiritualHealing            spelldata.Ladder
	Starshards                  spelldata.Ladder
	TouchOfWeakness             spelldata.Ladder
	TouchOfWeaknessTriggered    spelldata.Ladder
	TwilightFocus               spelldata.Ladder
	TwinDisciplines             spelldata.Ladder
	VampiricEmbrace             spelldata.Ladder
	WandSpecialization          spelldata.Ladder
}

var spellData = generatedSpellData{
	AbolishDisease:              spelldata.Ranked(552),
	AbolishDiseaseTriggered:     spelldata.Ranked(10872),
	BindingHeal:                 spelldata.Ranked(401937, 1240770, 1240771, 1240772, 1240773, 1240774),
	Blackout:                    spelldata.Ranked(15268, 15323, 15324, 15325, 15326),
	BlackoutTriggered:           spelldata.Ranked(15269),
	BlessedRecovery:             spelldata.Talent(27811, 3),
	BlessedRecoveryTriggered:    spelldata.Ranked(27813),
	Chastise:                    spelldata.Ranked(1277331, 1277332, 1277333, 1277334, 1277335),
	ConfoundingFlash:            spelldata.Ranked(1277455),
	ContingencyPlan:             spelldata.Ranked(1277462, 1277634, 1277638, 1277639, 1277640),
	ContingencyPlanTriggered:    spelldata.Ranked(1277456, 1277457, 1277458, 1277459, 1277460, 1277463, 1277464, 1277465, 1277466, 1277467),
	CureDisease:                 spelldata.Ranked(528),
	DarkSacrifice:               spelldata.Ranked(1277324, 1277325, 1277326, 1277327, 1277328),
	Darkness:                    spelldata.Talent(15259, 5),
	DesperatePrayer:             spelldata.Ranked(13908, 19236, 19238, 19240, 19241, 19242, 19243),
	DevouringContagion:          spelldata.Talent(1309950, 2),
	DevouringPlague:             spelldata.Ranked(2944, 19276, 19277, 19278, 19279, 19280),
	DispelMagic:                 spelldata.Ranked(527, 988),
	DivineAegis:                 spelldata.Talent(431622, 3),
	DivineAegisTriggered:        spelldata.Ranked(431624),
	DivineFury:                  spelldata.Talent(18530, 5),
	DivineGrace:                 spelldata.Ranked(1277370, 1277371, 1277372, 1277374, 1277376, 1277377, 1277378),
	DivineSpirit:                spelldata.Ranked(14752, 14818, 14819, 27841),
	EarlyDemise:                 spelldata.Talent(1310076, 2),
	ElunesGrace:                 spelldata.Ranked(2651),
	Fade:                        spelldata.Ranked(586, 9578, 9579, 9592, 10941, 10942),
	FearWard:                    spelldata.Ranked(6346),
	Feedback:                    spelldata.Ranked(13896, 19271, 19273, 19274, 19275),
	FeedbackTriggered:           spelldata.Ranked(6347, 19267, 19268, 19269, 19270),
	FlashHeal:                   spelldata.Ranked(2061, 9472, 9473, 9474, 10915, 10916, 10917),
	FocusedCasting:              spelldata.Ranked(27828),
	ForceOfWill:                 spelldata.Ranked(18544, 18547, 18548, 18549, 18550),
	GreaterHeal:                 spelldata.Ranked(2060, 10963, 10964, 10965, 25314),
	Heal:                        spelldata.Ranked(2054, 2055, 6063, 6064),
	HexOfWeakness:               spelldata.Ranked(9035, 19281, 19282, 19283, 19284, 19285),
	HolyFire:                    spelldata.Ranked(14914, 15262, 15263, 15264, 15265, 15266, 15267, 15261),
	HolyNova:                    spelldata.Ranked(15237, 15430, 15431, 27799, 27800, 27801),
	HolyNovaTriggered:           spelldata.Ranked(23455, 23458, 23459, 27803, 27804, 27805),
	HolyPrecision:               spelldata.Talent(1309957, 3),
	HolyReach:                   spelldata.Talent(27789, 2),
	HolySpecialization:          spelldata.Talent(14889, 5),
	ImprovedFade:                spelldata.Talent(15274, 2),
	ImprovedHealing:             spelldata.Talent(14912, 3),
	ImprovedInnerFire:           spelldata.Talent(14747, 3),
	ImprovedManaBurn:            spelldata.Talent(14750, 2),
	ImprovedMindBlast:           spelldata.Talent(15273, 5),
	ImprovedMindFlay:            spelldata.Talent(1225139, 2),
	ImprovedPowerWordFortitude:  spelldata.Ranked(14749, 14767),
	ImprovedPowerWordShield:     spelldata.Talent(14748, 3),
	ImprovedPsychicScream:       spelldata.Talent(15392, 2),
	ImprovedRenew:               spelldata.Talent(14908, 3),
	ImprovedShadowWordPain:      spelldata.Talent(15275, 2),
	IncreasedFortitude:          spelldata.Ranked(436951),
	InnerFire:                   spelldata.Ranked(588, 7128, 602, 1006, 10951, 10952),
	InnerFocus:                  spelldata.Ranked(14751),
	Inspiration:                 spelldata.Talent(14892, 3),
	InspirationTriggered:        spelldata.Ranked(14893),
	LesserHeal:                  spelldata.Ranked(2050, 2052, 2053),
	Levitate:                    spelldata.Ranked(1706),
	Lightwell:                   spelldata.Ranked(724, 27870, 27871),
	LightwellTriggered:          spelldata.Ranked(7001, 27873, 27874),
	LightwellRenew:              spelldata.Ranked(7001, 27873, 27874),
	LitanyOfLight:               spelldata.Talent(1317006, 2),
	ManaBurn:                    spelldata.Ranked(8129, 8131, 10874, 10875, 10876),
	Martyrdom:                   spelldata.Talent(14531, 2),
	MartyrdomTriggered:          spelldata.Ranked(27828),
	Meditation:                  spelldata.Talent(14521, 3),
	MentalAgility:               spelldata.Talent(14520, 3),
	MentalStrength:              spelldata.Talent(18551, 5),
	MindBlast:                   spelldata.Ranked(8092, 8102, 8103, 8104, 8105, 8106, 10945, 10946, 10947),
	MindControl:                 spelldata.Ranked(605, 10911, 10912),
	MindFlay:                    spelldata.Ranked(15407, 17311, 17312, 17313, 17314, 18807),
	MindSoothe:                  spelldata.Ranked(453, 8192, 10953),
	MindVision:                  spelldata.Ranked(2096, 10909),
	Penance:                     spelldata.Ranked(402174, 1240720, 1240721, 1316995),
	PenanceTriggered:            spelldata.Ranked(402261, 402284, 402289, 1240723, 1240724, 1240727, 1240730, 1316991, 1316993),
	PowerInfusion:               spelldata.Ranked(10060),
	PowerWordFortitude:          spelldata.Ranked(1243, 1244, 1245, 2791, 10937, 10938),
	PowerWordShield:             spelldata.Ranked(17, 592, 600, 3747, 6065, 6066, 10898, 10899, 10900, 10901),
	PowerWordShieldTriggered:    spelldata.Ranked(6788, 14748),
	PowerInLight:                spelldata.Talent(1309969, 5),
	PrayerOfFortitude:           spelldata.Ranked(21562, 21564),
	PrayerOfHealing:             spelldata.Ranked(596, 996, 10960, 10961, 25316),
	PrayerOfMending:             spelldata.Ranked(401859, 1240826, 1240827),
	PrayerOfMendingTriggered:    spelldata.Ranked(401877, 401880),
	PrayerOfShadowProtection:    spelldata.Ranked(27683),
	PrayerOfSpirit:              spelldata.Ranked(27681),
	PsychicScream:               spelldata.Ranked(8122, 8124, 10888, 10890),
	Renew:                       spelldata.Ranked(139, 6074, 6075, 6076, 6077, 6078, 10927, 10928, 10929, 25315),
	RenewedHope:                 spelldata.Talent(425280, 5),
	Resurrection:                spelldata.Ranked(2006, 2010, 10880, 10881, 20770),
	SearingLight:                spelldata.Talent(14909, 2),
	SearingLightTriggered:       spelldata.Ranked(1284536),
	ShackleUndead:               spelldata.Ranked(9484, 9485, 10955),
	ShadowAffinity:              spelldata.Talent(15318, 3),
	ShadowFocus:                 spelldata.Talent(15260, 5),
	ShadowProtection:            spelldata.Ranked(976, 10957, 10958),
	ShadowReach:                 spelldata.Talent(17322, 2),
	ShadowWeaving:               spelldata.Talent(15257, 3),
	ShadowWeavingTriggered:      spelldata.Ranked(15258),
	ShadowWordDeath:             spelldata.Ranked(1309595, 1309633, 1309635, 1309636),
	ShadowWordPain:              spelldata.Ranked(589, 594, 970, 992, 2767, 10892, 10893, 10894),
	Shadowfiend:                 spelldata.Ranked(401977),
	ShadowfiendTriggered:        spelldata.Ranked(401988),
	Shadowform:                  spelldata.Ranked(15473),
	Shadowguard:                 spelldata.Ranked(18137, 19308, 19309, 19310, 19311, 19312),
	ShadowguardTriggered:        spelldata.Ranked(28376, 28377, 28378, 28379, 28380, 28381, 28382),
	Silence:                     spelldata.Ranked(15487),
	SilenceTriggered:            spelldata.Ranked(1241057),
	SilentResolve:               spelldata.Talent(14523, 3),
	Smite:                       spelldata.Ranked(585, 591, 598, 984, 1004, 6060, 10933, 10934),
	SoulWarding:                 spelldata.Talent(402000, 1),
	SpellWarding:                spelldata.Talent(27900, 5),
	SpiritTap:                   spelldata.Talent(15270, 5),
	SpiritTapTriggered:          spelldata.Ranked(15271),
	SpiritOfRedemption:          spelldata.Ranked(20711),
	SpiritOfRedemptionTriggered: spelldata.Ranked(27827),
	SpiritualGuidance:           spelldata.Talent(14901, 5),
	SpiritualHealing:            spelldata.Talent(14898, 3),
	Starshards:                  spelldata.Ranked(10797, 19296, 19299, 19302, 19303, 19304, 19305),
	TouchOfWeakness:             spelldata.Ranked(2652, 19261, 19262, 19264, 19265, 19266),
	TouchOfWeaknessTriggered:    spelldata.Ranked(2943, 19249, 19251, 19252, 19253, 19254, 28598),
	TwilightFocus:               spelldata.Talent(14913, 3),
	TwinDisciplines:             spelldata.Talent(1225132, 5),
	VampiricEmbrace:             spelldata.Ranked(15286),
	WandSpecialization:          spelldata.Talent(14524, 2),
}
