// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package rogue

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Improved Expose Armor: effect 2 of spell 14168 has no rank curve and is held at its base points
//   Quietus: effect 1 of spell 1310728 has no rank curve and is held at its base points

type generatedSpellData struct {
	AdrenalineRush              spelldata.Ladder
	Aggression                  spelldata.Ladder
	Ambush                      spelldata.Ladder
	Backstab                    spelldata.Ladder
	BladeFlurry                 spelldata.Ladder
	Blind                       spelldata.Ladder
	Camouflage                  spelldata.Ladder
	CheapShot                   spelldata.Ladder
	ColdBlood                   spelldata.Ladder
	CoupDeGrace                 spelldata.Ladder
	Cutthroat                   spelldata.Ladder
	CutthroatTriggered          spelldata.Ladder
	DefensiveState              spelldata.Ladder
	DefensiveStateTriggered     spelldata.Ladder
	Deflection                  spelldata.Ladder
	DirtyDeeds                  spelldata.Ladder
	DirtyTricks                 spelldata.Ladder
	DisarmTrap                  spelldata.Ladder
	Distract                    spelldata.Ladder
	DualWieldSpecialization     spelldata.Ladder
	Elusiveness                 spelldata.Ladder
	Endurance                   spelldata.Ladder
	Evasion                     spelldata.Ladder
	Eviscerate                  spelldata.Ladder
	ExposeArmor                 spelldata.Ladder
	Feint                       spelldata.Ladder
	FistWeaponSpecialization    spelldata.Ladder
	FlawlessExecution           spelldata.Ladder
	Garrote                     spelldata.Ladder
	GhostlyStrike               spelldata.Ladder
	Gouge                       spelldata.Ladder
	HackAndSlash                spelldata.Ladder
	HeightenedSenses            spelldata.Ladder
	Hemorrhage                  spelldata.Ladder
	ImprovedAmbush              spelldata.Ladder
	ImprovedDistract            spelldata.Ladder
	ImprovedEviscerate          spelldata.Ladder
	ImprovedExposeArmor         spelldata.Ladder
	ImprovedGouge               spelldata.Ladder
	ImprovedKick                spelldata.Ladder
	ImprovedKickTriggered       spelldata.Ladder
	ImprovedKidneyShot          spelldata.Ladder
	ImprovedPoisons             spelldata.Ladder
	ImprovedSap                 spelldata.Ladder
	ImprovedSapTriggered        spelldata.Ladder
	ImprovedSinisterStrike      spelldata.Ladder
	ImprovedSliceAndDice        spelldata.Ladder
	ImprovedSprint              spelldata.Ladder
	ImprovedSprintTriggered     spelldata.Ladder
	Initiative                  spelldata.Ladder
	InitiativeTriggered         spelldata.Ladder
	Kick                        spelldata.Ladder
	KidneyShot                  spelldata.Ladder
	Lethality                   spelldata.Ladder
	LightningReflexes           spelldata.Ladder
	Malice                      spelldata.Ladder
	MasterOfDeception           spelldata.Ladder
	Murder                      spelldata.Ladder
	Mutilate                    spelldata.Ladder
	MutilateTriggered           spelldata.Ladder
	Opportunity                 spelldata.Ladder
	PickPocket                  spelldata.Ladder
	Precision                   spelldata.Ladder
	Premeditation               spelldata.Ladder
	Preparation                 spelldata.Ladder
	PuncturingWounds            spelldata.Ladder
	PuncturingWoundsTriggered   spelldata.Ladder
	Quietus                     spelldata.Ladder
	Redirect                    spelldata.Ladder
	RelentlessStrikes           spelldata.Ladder
	RelentlessStrikesTriggered  spelldata.Ladder
	RemorselessAttacks          spelldata.Ladder
	RemorselessAttacksTriggered spelldata.Ladder
	Riposte                     spelldata.Ladder
	RoguePassive                spelldata.Ladder
	Rupture                     spelldata.Ladder
	Ruthlessness                spelldata.Ladder
	RuthlessnessTriggered       spelldata.Ladder
	Sap                         spelldata.Ladder
	SealFate                    spelldata.Ladder
	SerratedBlades              spelldata.Ladder
	Setup                       spelldata.Ladder
	SetupTriggered              spelldata.Ladder
	SinisterStrike              spelldata.Ladder
	SliceAndDice                spelldata.Ladder
	Sprint                      spelldata.Ladder
	Stealth                     spelldata.Ladder
	ThousandCuts                spelldata.Ladder
	ThousandCutsTriggered       spelldata.Ladder
	Vanish                      spelldata.Ladder
	VanishTriggered             spelldata.Ladder
	Vanished                    spelldata.Ladder
	Venom                       spelldata.Ladder
	Vigor                       spelldata.Ladder
	VilePoisons                 spelldata.Ladder
	WeaponExpertise             spelldata.Ladder
}

var spellData = generatedSpellData{
	AdrenalineRush:              spelldata.Ranked(13750),
	Aggression:                  spelldata.Talent(18427, 3),
	Ambush:                      spelldata.Ranked(8676, 8724, 8725, 11267, 11268, 11269),
	Backstab:                    spelldata.Ranked(53, 2589, 2590, 2591, 8721, 11279, 11280, 11281, 25300),
	BladeFlurry:                 spelldata.Ranked(13877),
	Blind:                       spelldata.Ranked(2094),
	Camouflage:                  spelldata.Talent(13975, 5),
	CheapShot:                   spelldata.Ranked(1833),
	ColdBlood:                   spelldata.Ranked(14177),
	CoupDeGrace:                 spelldata.Ranked(1310709),
	Cutthroat:                   spelldata.Talent(462708, 5),
	CutthroatTriggered:          spelldata.Ranked(462707),
	DefensiveState:              spelldata.Ranked(16092),
	DefensiveStateTriggered:     spelldata.Ranked(5302),
	Deflection:                  spelldata.Talent(13713, 3),
	DirtyDeeds:                  spelldata.Talent(14082, 2),
	DirtyTricks:                 spelldata.Talent(1224782, 2),
	DisarmTrap:                  spelldata.Ranked(1842),
	Distract:                    spelldata.Ranked(1725),
	DualWieldSpecialization:     spelldata.Talent(13715, 5),
	Elusiveness:                 spelldata.Talent(13981, 2),
	Endurance:                   spelldata.Talent(13742, 2),
	Evasion:                     spelldata.Ranked(5277),
	Eviscerate:                  spelldata.Ranked(2098, 6760, 6761, 6762, 8623, 8624, 11299, 11300, 31016),
	ExposeArmor:                 spelldata.Ranked(8647, 8649, 8650, 11197, 11198),
	Feint:                       spelldata.Ranked(1966, 6768, 8637, 11303, 25302),
	FistWeaponSpecialization:    spelldata.Ranked(13707, 13966, 13967, 13968, 13969),
	FlawlessExecution:           spelldata.Ranked(1310711),
	Garrote:                     spelldata.Ranked(703, 8631, 8632, 8633, 11289, 11290),
	GhostlyStrike:               spelldata.Ranked(14278),
	Gouge:                       spelldata.Ranked(1776, 1777, 8629, 11285, 11286),
	HackAndSlash:                spelldata.Talent(13960, 5),
	HeightenedSenses:            spelldata.Talent(30894, 2),
	Hemorrhage:                  spelldata.Ranked(16511),
	ImprovedAmbush:              spelldata.Talent(14079, 3),
	ImprovedDistract:            spelldata.Talent(14084, 2),
	ImprovedEviscerate:          spelldata.Talent(14162, 3),
	ImprovedExposeArmor:         spelldata.Talent(14168, 2),
	ImprovedGouge:               spelldata.Talent(13741, 3),
	ImprovedKick:                spelldata.Talent(13754, 2),
	ImprovedKickTriggered:       spelldata.Ranked(18425),
	ImprovedKidneyShot:          spelldata.Talent(14174, 2),
	ImprovedPoisons:             spelldata.Talent(14113, 5),
	ImprovedSap:                 spelldata.Ranked(14076, 14094, 14095),
	ImprovedSapTriggered:        spelldata.Ranked(14093),
	ImprovedSinisterStrike:      spelldata.Talent(13732, 2),
	ImprovedSliceAndDice:        spelldata.Talent(14165, 3),
	ImprovedSprint:              spelldata.Talent(13743, 2),
	ImprovedSprintTriggered:     spelldata.Ranked(30918),
	Initiative:                  spelldata.Talent(13976, 3),
	InitiativeTriggered:         spelldata.Ranked(13977),
	Kick:                        spelldata.Ranked(1766, 1767, 1768, 1769),
	KidneyShot:                  spelldata.Ranked(408, 8643),
	Lethality:                   spelldata.Talent(14128, 5),
	LightningReflexes:           spelldata.Talent(13712, 5),
	Malice:                      spelldata.Talent(14138, 5),
	MasterOfDeception:           spelldata.Talent(13958, 3),
	Murder:                      spelldata.Talent(14158, 2),
	Mutilate:                    spelldata.Ranked(1310707, 399956, 1241582, 1241584),
	MutilateTriggered:           spelldata.Ranked(399960, 399961, 1241585, 1241586, 1241588, 1241590, 1310705, 1310706),
	Opportunity:                 spelldata.Talent(14057, 2),
	PickPocket:                  spelldata.Ranked(921),
	Precision:                   spelldata.Talent(13705, 3),
	Premeditation:               spelldata.Ranked(14183),
	Preparation:                 spelldata.Ranked(14185),
	PuncturingWounds:            spelldata.Talent(1224716, 3),
	PuncturingWoundsTriggered:   spelldata.Ranked(1310710),
	Quietus:                     spelldata.Talent(1310728, 5),
	Redirect:                    spelldata.Ranked(438040),
	RelentlessStrikes:           spelldata.Ranked(14179),
	RelentlessStrikesTriggered:  spelldata.Ranked(14181),
	RemorselessAttacks:          spelldata.Talent(14144, 2),
	RemorselessAttacksTriggered: spelldata.Ranked(14143),
	Riposte:                     spelldata.Ranked(14251),
	RoguePassive:                spelldata.Ranked(21184),
	Rupture:                     spelldata.Ranked(1943, 8639, 8640, 11273, 11274, 11275),
	Ruthlessness:                spelldata.Talent(14156, 3),
	RuthlessnessTriggered:       spelldata.Ranked(14157),
	Sap:                         spelldata.Ranked(6770, 2070, 11297),
	SealFate:                    spelldata.Talent(14186, 5),
	SerratedBlades:              spelldata.Talent(14171, 3),
	Setup:                       spelldata.Talent(13983, 3),
	SetupTriggered:              spelldata.Ranked(15250),
	SinisterStrike:              spelldata.Ranked(1752, 1757, 1758, 1759, 1760, 8621, 11293, 11294),
	SliceAndDice:                spelldata.Ranked(5171, 6774),
	Sprint:                      spelldata.Ranked(2983, 8696, 11305),
	Stealth:                     spelldata.Ranked(1784, 1785, 1786, 1787),
	ThousandCuts:                spelldata.Talent(1310721, 1),
	ThousandCutsTriggered:       spelldata.Ranked(1310723),
	Vanish:                      spelldata.Ranked(1856, 1857),
	VanishTriggered:             spelldata.Ranked(11327, 11329, 18461),
	Vanished:                    spelldata.Ranked(14093),
	Venom:                       spelldata.Ranked(1310703),
	Vigor:                       spelldata.Talent(14983, 2),
	VilePoisons:                 spelldata.Talent(16513, 5),
	WeaponExpertise:             spelldata.Talent(30919, 2),
}
